### ISSUE TITLE
[Bug-Candidate]: Shrinking extremely slow in some rare situations

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#1028]
### Describe the issue:

In some rare situations shrinking can be really slow. I can work around this by setting `shrinkLimit` really high but it would be nice to have a real fix.

@arcz has access to a private repo where this can be reproduced.

### Version:

Many

### Relevant log output:

![image](https://user-images.githubusercontent.com/1430820/232536075-94aeb0d9-37cc-4c54-824b-2efb8becce29.png)

This `1` can shrink to a `0`:
![image](https://user-images.githubusercontent.com/1430820/232536167-488b4343-11d1-413e-86dc-a0c0b2f3d154.png)

**Comment by samalws-tob** [comment]
I think the problem here is that echidna tries to shrink all the values at once. So in the `(1,128,2)` example, the 128 and the 2 need to remain the same but this only has a 1 in 256 chance of happening. See #1192 for a fix
