### ISSUE TITLE
[Bug-Candidate]: Echidna crashed with an error: Call target doesn't exist

### ISSUE THREAD

**Issue by webthethird** [crytic/echidna#1037]
### Describe the issue:

I'm not sure what's going on, just found this error when I woke up after leaving the fuzzer running overnight. 
For what it's worth, I was doing on-chain fuzzing of Compound on a fork at a particular block in the past. And I was using the experimental `hevm.createFork()` and `hevm.selectFork(forkId)` cheat codes.

![image](https://user-images.githubusercontent.com/6509209/233861029-3d658a13-9fa2-4105-8039-efff8d4f34ee.png)

If it would be helpful, I can share the either my entire corpus directory or just the reproducers.

### Code example to reproduce the issue:

[Config file](https://github.com/webthethird/solidity-diff-fuzz-upgrades/blob/5f23d79c726f0891bd474645bb284a232c9f1bab/contracts/test/compound/CryticConfig.yaml)
[Test contract](https://github.com/webthethird/solidity-diff-fuzz-upgrades/blob/5f23d79c726f0891bd474645bb284a232c9f1bab/contracts/test/compound/DiffFuzzUpgrades.sol)
- This test contract creates two forks at block 13332796, and interacts directly with the following contracts:
    - Unitroller at 0x3d9819210A31b4961b30EF54bE2aeD79B9c9Cd3B with implementations:
        - 0x75442Ac771a7243433e033F3F8EaB2631e22938f
        - 0x374ABb8cE19A73f2c4EFAd642bda76c797f19233
    - COMP token at 0xc00e94Cb662C3520282E6f5717214004A7f26888
    - cBAT CToken at 0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E

### Version:

2.1.1

**Comment by webthethird** [comment]
Any idea what causes this? I keep running into this error

**Comment by the-caliber** [comment]
Hi @webthethird 
Maybe I don't have a complete answer for this but in my case deleting the `corpus/` dir and running echidna again works.

**Comment by webthethird** [comment]
> Hi @webthethird Maybe I don't have a complete answer for this but in my case deleting the `corpus/` dir and running echidna again works.

Yes, I think this is the solution. I solved it the same way, just forgot to close this issue.
