### ISSUE TITLE
Echidna: Deploying the contract failure error

### ISSUE THREAD

**Issue by AbigailTCameron** [crytic/echidna#1043]
I have written a contract that was meant to test another contract which takes a few arguments. It looks something like this: 

```
import "./interfaces/IVault.sol";
import "./VaultContract.sol";

contract VaultFuzzer is VaultContract {
    address public constant vault = 0x0aaa;

    constructor()
    VaultContract(
      0x0arg1,
      0x0arg2,
      0x0arg3,
      0x0arg4
    )
    {}

    function deposit_check(uint256 amount) public{
      uint256 previousBal = IVault(vault).balanceOf(msg.sender); 
      deposit(amount);

      uint256 currentBal = previousBal + amount; 

      assert(currentBal == IVault(vault).balanceOf(msg.sender)); 
    } 
}
```

I am trying to use the assert method as a means of testing, however, I keep getting the following deployment failure: 

`echidna: Deploying the contract 0x0aaa failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.):`

I am not really sure what the issue is. Any ideas on how I can go about fixing it?

**Comment by ggrieco-tob** [comment]
We don't have access to the complete code, but it looks like your contract tries to execute code that was not there (e.g. a contract that was not deployed yet).

**Comment by AbigailTCameron** [comment]
@ggrieco-tob The other codes that are directly referenced are the `VaultContract`, and its interface `(IVault)`. 

The code for the `VaultContract` has been deployed at the address `0x8CdF8d10ea6Cd3492e67C4250481A695c2a75C4a`. This is the address being referenced in the VaultFuzzer as `address public constant vault = 0x0aaa` (I just replaced it in the explanation). 


  
Likewise, the interface being inherited is: 
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.4;

import "../lib/erc20.sol";

interface IVault is IERC20 {
    function token() external view returns (address);
    
    function reward() external view returns (address);

    function claimInsurance() external; // NOTE: Only yDelegatedVault implements this

    function getRatio() external view returns (uint256);

    function depositAll() external;
    
    function balance() external view returns (uint256);

    function deposit(uint256) external;

    function withdrawAll() external;

    function withdraw(uint256) external;

    function earn() external;

    function decimals() external view returns (uint8);

    function governance() external view returns (address);
}
```

**Comment by AbigailTCameron** [comment]
@elopez I modified the constructor so that it is now payable. My constructor now looks like this: 

```
   ...
    constructor () payable
    VaultContract(
      0x0arg1,
      0x0arg2,
      0x0arg3,
      0x0arg4
    )
    {}
   ...
```

My config file also has the following: 
```
testLimit: 100
testMode: assertion
balanceContract: 10000
```

Nothing has changed in the error message. 

N.B. In case this is important, the VaultContract has already been deployed and the value being represented by `address public constant vault = 0x0aaa` exists on the blockchain. I quoted the actual address above in my previous reply.

**Comment by AbigailTCameron** [comment]
@elopez So for that second point would I just need to include an RPC endpoint, for e.g. `rpcUrl: "https://arb1.arbitrum.io/rpc"` in the config file, as well as the block number, `rpcBlock: 88982648`, of the current block on which the VaultContract is deployed?

**Comment by elopez** [comment]
@AbigailTCameron For the current stable version of Echidna, I think you would need to define `ECHIDNA_RPC_URL` and `ECHIDNA_RPC_BLOCK` variables in your environment. `rpcUrl` and `rpcBlock` options are only available on the echidna development branch, and not yet on a stable release.

For the RPC URL, it would probably be best to use something that can take many requests without rate limiting -- e.g. Infura and others offer RPC services with API keys that you can use. For block number, it doesn't need to be the exact block you deployed the contracts, it can be any later block as well, where the contracts are deployed and working. Keep in mind that the contract state is also pulled from that block, so e.g. accounts may have balances and such if people were already using the contracts.

**Comment by ggrieco-tob** [comment]
@AbigailTCameron Any updates from your side?

**Comment by ggrieco-tob** [comment]
It looks like this issue can be solved using RPC. Let's close this issue but @AbigailTCameron feel free to reopen if you need.
