### ISSUE TITLE
[Bug-Candidate]: :Cannot execute `npx`, is it installed and in PATH?

### ISSUE THREAD

**Issue by the-caliber** [crytic/echidna#1044]
### Describe the issue:

I was using the latest docker image https://github.com/crytic/echidna/pkgs/container/echidna%2Fechidna/83222271?tag=latest  
  
I am getting the following issue "echidna-test: Couldn't compile given file + ERROR:CryticCompile:Cannot execute `npx`, is it installed and in PATH?" as mentioned below in detail as log output.  
while using trailofbits/eth-security-toolbox (uses echidna 2.0.1) it works fine.

### Code example to reproduce the issue:

//I am testing properties but i think running other properties will give same issue.  

pragma solidity ^0.8.0;  
import "@crytic/properties/contracts/ERC20/internal/properties/ERC20BasicProperties.sol";  
import "./ERC20Token.sol";  
contract CryticERC20InternalHarness is ERC20Mock, CryticERC20BasicProperties {  

    constructor() {
        // Setup balances for USER1, USER2 and USER3:
        _mint(USER1, INITIAL_BALANCE);
        _mint(USER2, INITIAL_BALANCE);
        _mint(USER3, INITIAL_BALANCE);
        // Setup total supply:
        initialSupply = totalSupply();
    }
}

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract ERC20Mock is ERC20 {
    constructor() ERC20("ERC20Mock", "E20M") {}

    // function mint(address account, uint256 amount) external {
    //     _mint(account, amount);
    // }

    // function burn(address account, uint256 amount) external {
    //     _burn(account, amount);
    // }
}

### Version:

Echidna 2.1.1 and slither 0.9.2  

### Relevant log output:

```shell
echidna-test . --contract CryticERC20InternalHarness --config contracts/ERC20Test/tests/config.yaml
[2023-05-11 05:04:38.46] Compiling .... Done! (0.4347906s)
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Cannot execute `npx`, is it installed and in PATH?
ERROR:CryticCompile:Cannot execute `npx`, is it installed and in PATH?
INFO:CryticCompile:Problem executing hardhat to fetch configuration, using defaults: [Errno 2] No such file or directory: 'npx'
INFO:CryticCompile:'npx hardhat compile --force' running
Traceback (most recent call last):
  File "/venv/bin/crytic-compile", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.8/site-packages/crytic_compile/__main__.py", line 193, in main
    compilations = compile_all(**vars(args))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 620, in compile_all
    compilations.append(CryticCompile(target, **kwargs))
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 110, in __init__
    self._compile(**kwargs)
  File "/venv/lib/python3.8/site-packages/crytic_compile/crytic_compile.py", line 530, in _compile
    self._platform.compile(self, **kwargs)
  File "/venv/lib/python3.8/site-packages/crytic_compile/platform/hardhat.py", line 177, in compile
    with subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npx'
```

**Comment by elopez** [comment]
Hi! This error is shown because the docker container does not have Node installed by default. The container does have [nvm](https://github.com/nvm-sh/nvm) preinstalled though, so it should be easy for you to install and use a suitable node version; for example:

```shell
nvm install 16
nvm use 16
echidna ....
```

**Comment by the-caliber** [comment]
It worked! thanks @elopez .
