### ISSUE TITLE
How to detect contracts of different compiled versions in large batches

### ISSUE THREAD

**Issue by EgbertTtTt** [crytic/echidna#1050]
Hello everyone, I am planning to use echidna to do large-scale (about 1200) smart contract vulnerability detection as a reference for the experimental data of the paper. But these contracts all require different versions of the solidity compiler (for example: ^0.4.20, ^0.6.4). Is there any way to automatically batch detect these contracts without manually switching the solc version?
Thank you very much!

**Comment by ggrieco-tob** [comment]
Hi, it seems that you could try to do [a slither ](https://github.com/crytic/slither) script for that since Echidna by itself will not allow this. Please open an issue in the slither issue tracker to get help for this.

Thanks!

**Comment by ggrieco-tob** [comment]
This was a slither/crytic-compile discussion, so I'm closing this.
