### ISSUE TITLE
Improve help if the wrong test-mode is used

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#1056]
A lot of users are using the assertion mode now. Maybe we should replace
the message `echidna: No tests found in ABI`, to something like `echidna: No tests found in ABI. If you are using assert(), use --test-mode assertion`, or something similar

**Comment by Saniabuh** [comment]
Please can you like provide example of " --test-mode assertion " thanks

**Comment by Saniabuh** [comment]
@montyly, Please can you like provide example of " --test-mode assertion " thanks

**Comment by Saniabuh** [comment]
@arcz ,Please can you like provide example of " --test-mode assertion " thanks
