### ISSUE TITLE
[Bug-Candidate]: On-chain fuzzing of Compound cTokens is very slow

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#1061]
### Describe the issue:

On-chain fuzzing of Compound cTokens is very slow

### Code example to reproduce the issue:

```solidity
interface IHevm {
    function roll(uint256) external;
    function prank(address) external;
}

interface IUSDC {
    function mint(address, uint256) external;
    function masterMinter() external view returns (address);
    function configureMinter(address, uint256) external;
}

interface ICErc20 {
    function mint(uint256) external;
}

contract Echidna {
    IHevm hevm = IHevm(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);

    IUSDC usdc = IUSDC(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48);
    ICErc20 cUsdc = ICErc20(0x39AA39c021dfbaE8faC545936693aC917d5E7563);

    constructor() payable {
        hevm.roll(17349860);

        hevm.prank(usdc.masterMinter());
        usdc.configureMinter(address(this), type(uint256).max);
    }

    // this one is fast
    function mintUsdc() public {
        usdc.mint(address(this), 1);
    }

    // this one is slow
    function mintCUsdc() public {
        cUsdc.mint(1);
    }
}
```

```yaml
workers: 2
testMode: assertion
prefix: echidna_
corpusDir: echidna-corpus
```

### Version:

Echidna 2.2.0 & 2.1.1
Slither 0.9.3

### Relevant log output:

![image](https://github.com/crytic/echidna/assets/1430820/d2bfebd4-ed06-4c7f-8b41-bff50aec437f)

**Comment by siraben** [comment]
@rappie I tried to reproduce this example given the Solidity and YAML file, but after 9 elapsed seconds I have around 8.5k total calls. Could you provide more information on your system and environment? This is what `uname -a` reports:
```
cortex:echidna siraben$ uname -a
Darwin cortex.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64 arm Darwin
```

**Comment by siraben** [comment]
@rappie I tried to reproduce this example given the Solidity and YAML file, but after 9 elapsed seconds I have around 8.5k total calls. Could you provide more information on your system and environment? This is what `uname -a` reports:
```
$ uname -prv
22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm
```

**Comment by rappie** [comment]
```shell
$ uname -a
Linux manjaropc 5.15.112-1-MANJARO #1 SMP PREEMPT Wed May 17 11:11:32 UTC 2023 x86_64 GNU/Linux
```

Let me know if you need anything else.

**Comment by rappie** [comment]
```
$ export ECHIDNA_RPC_URL="https://eth-mainnet.alchemyapi.io/v2/..."
$ export ECHIDNA_RPC_BLOCK=17349860
$ echidna . --contract Echidna --config echidna-config.yaml
```

This is how I run Echidna. I've also tried a different RPC (ankr).

**Comment by siraben** [comment]
This is what I see. Do you still experience the same issue at around 110 calls/s?
<img width="858" alt="Screenshot 2023-06-06 at 16 31 45" src="https://github.com/crytic/echidna/assets/8219659/cf0a6109-015e-4e9d-869f-8f00685c0e1c">

**Comment by siraben** [comment]
Can you run this?
```ShellSession
$ cabal run --enable-profiling echidna -- +RTS -p -RTS ctokens.sol --test-limit 100000 --config ctokens.yaml --seed 2394853914143933278
```

**Comment by rappie** [comment]
I'm getting this error. Do I have to manually compile echidna first?

```
cabal: Cannot run the package echidna, it is not in this project (either
directly or indirectly). If you want to add it to the project then edit the
cabal.project file.
```

**Comment by rappie** [comment]
Sure. I will look into this later today. Thanks :slightly_smiling_face:

**Comment by siraben** [comment]
Ok, let me know how it goes. It might just be a matter of running the command in the root of the repository as well (after cabal update). If that works, let me know also.

**Comment by rappie** [comment]
I got it :smile: 

I installed echidna using `nix` like this:
```shell
nix-env -i -f https://github.com/crytic/echidna/tarball/master
```

It's now available in my path
```
$ which echidna
/home/rappie/.nix-profile/bin/echidna
```

It's the same version (2.2.0) but it is way faster!

Now that I think of it, I've had issues like this before, where manually compiling solved problems.

I'll still do the profiling.

**Comment by ggrieco-tob** [comment]
Do you know which commit version you were using before?

**Comment by rappie** [comment]
Here is the profile log. Hope it helps :smile: 

[profile.zip](https://github.com/crytic/echidna/files/11666766/profile.zip)

**Comment by rappie** [comment]
I did some more testing. It's faster but it doesn't seem to be able to find the bug that the slower one does.

I will do more research later.

**Comment by rappie** [comment]
My bad. I still had old RPC environment variables set :sweat_smile: 

It is fast now for the example in this issue. However, it is still really slow in my real setup.

I have to work on some other stuff right now but I'll get back to this issue once i have more time.

Thanks so far for all the help!
