### ISSUE TITLE
[Bug-Candidate]: Echidna doesn't ignore folders generated by other tools

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/echidna#1087]
### Describe the issue:

If there is a folder under `crytic-export` such as `flattening`, Echidna errors:
`echidna: crytic-export/flattening: openFile: inappropriate type (is a directory)`

This makes it difficult to fuzz flattened contracts, and I think it can be ignored. This is also true if the crytic-export directory has a folder from running slither on Etherscan.

### Code example to reproduce the issue:

`contract A`

### Version:

0.2.2 0.9.4

### Relevant log output:

```shell
`echidna: crytic-export/flattening: openFile: inappropriate type (is a directory)`
```

**Comment by samalws-tob** [comment]
I think PR #1098 accidentally fixed this by filtering out files that don't end in `.json`. When I do `mkdir crytic-export/flattening; echidna ...` it doesn't error. Would you mind trying it out to see if this is still a problem for you?
