### ISSUE TITLE
Add Linux Package Managers Installation Support for Echidna

### ISSUE THREAD

**Issue by aviggiano** [crytic/echidna#1095]
### Describe the desired feature

Currently, installing Echidna on MacOS is straightforward using Homebrew with `brew install echidna`. 

On the other hand, on Linux the easiest way seems to be manually downloading the binary and moving it to the `/usr/bin` directory. This process can be a bit more burdensome and might discourage some Linux users.

It would be better if Linux users could also have a simple one-line installation command, such as `apt install echidna` or `yum install echidna`.

Note: this issue was raised at the DeFi Security 101 workshop, where some folks seated near me didn't have Echidna and had to look through the docs to install it.

**Comment by ggrieco-tob** [comment]
Hi!,

We have #1082. Do you think you can quickly test it to see if this fits your use case?

Thanks!

**Comment by aviggiano** [comment]
Hey
Nice, I didn't see that new feature. I think it is perfect, I'll close this issue now
