### ISSUE TITLE
[Bug-Candidate]: Segmentation Fault

### ISSUE THREAD

**Issue by aviggiano** [crytic/echidna#1104]
### Describe the issue:

Segmentation Fault when running echidna:

![Screenshot 2023-08-07 at 13 56 30](https://github.com/crytic/echidna/assets/3029017/67b779f6-5f35-4c4a-8772-2271a01bfe7c)

Answering the questions asked here #899

- hardware you are using, hardware architecture (x86_64/ARM), OS, OS version: MacBook Air M1 with MacOS 13.3.1 (22E261) 
- echidna version, and how you got it installed: 2.2.0, homebrew
- does this happen only on the graphical mode or also if you use the --format text option? this does not happen when I use `--format text`, but the problem seems intermittent. It happened twice, and then it stopped after I tried using `--format text`
- is your computer working fine otherwise, or are you seeing other crashes lately? (there's a slim chance that issues like these could be caused by a hardware issue): yes it's fine
- if you can share the project you're fuzzing to try and reproduce the issue on our side, that would be great too: it's closed source, unfortunately, I'll try to create an MWE later

### Code example to reproduce the issue:

N/A

### Version:

Echidna 2.2.0
Slither 0.9.2

**Comment by elopez** [comment]
Hi! There may be some more crash information in the Console app (not the terminal, the one named Console with this logo ![Screenshot 2023-08-07 at 14 22 56](https://github.com/crytic/echidna/assets/2642849/13d5afdc-5548-4090-993b-119f2fadd5ba) ). If you can see anything useful there please also share it on here.

Were you using one of the newer features? (e.g. the RPC support, or multi-core fuzzing?)

**Comment by aviggiano** [comment]
> Can you try to reproduce it using 2.2.1?

I'll try it out

> There may be some more crash information in the Console app (not the terminal, the one named Console with this logo

I can't understand the output, but maybe these are helpful:

https://gist.github.com/aviggiano/b5397153ed27298945df392d1b4f9058
https://gist.github.com/aviggiano/78066768c430014ab2d25b8f2646dd9e
https://gist.github.com/aviggiano/629ce99b0c32db8c07f8e4c265d78485

> Were you using one of the newer features? (e.g. the RPC support, or multi-core fuzzing?)

No

**Comment by aviggiano** [comment]
2.2.1 also crashes, now while shrinking

![Screenshot 2023-08-07 at 20 57 30](https://github.com/crytic/echidna/assets/3029017/069458c1-4f72-4e3a-a38d-4eed88cece18)

**Comment by aviggiano** [comment]
JFTR, clearing the corpus makes the issue disappear. It might be a specific transaction that's triggering this segfault?

**Comment by ggrieco-tob** [comment]
It is unclear to say. Since you found a workaround, I will close this. Please reopen if you find some reproducible example.
