### ISSUE TITLE
[Bug-Candidate]: Echidna multicore produces slower shrinking behavior

### ISSUE THREAD

**Issue by aviggiano** [crytic/echidna#1105]
### Describe the issue:

I am running echidna with 8 workers, but I am getting unexpected/unwanted results for the shrinking step when a bug is found:

Instead of shrinking _faster_, when I add more workers the process is significantly _slower_.

Sometimes I see the shrink step go down, and then up, then down, and then up. It seems like increasing the number of workers adds a bunch of (duplicate) transactions that do not contribute to the smallest sequence possible.

I did a small 1-min test, reutilizing the corpus, with 1 worker vs 8 workers. You can see below that using more workers makes echidna run much slower when a bug is found.

### 1 worker

<img width="1109" alt="Screenshot 2023-08-16 at 15 52 02" src="https://github.com/crytic/echidna/assets/3029017/b5ea3351-8472-423a-8a57-e5cf3f830608">

### 8 workers

<img width="1319" alt="Screenshot 2023-08-16 at 15 49 21" src="https://github.com/crytic/echidna/assets/3029017/f12ea6f8-e482-4225-99e5-3356b1df0561">

### Code example to reproduce the issue:

N/A

### Version:

Echidna 2.2.1
slither 0.9.2

### Relevant log output:

```shell
N/A
```

**Comment by rappie** [comment]
I often encounter the same thing. I think this is because the different workers can overwrite each others "best shrunk" version and kind of work against each other that way.

**Comment by arcz** [comment]
Yes, this is a known issue to be fixed
