### ISSUE TITLE
echidna-test: command not found

### ISSUE THREAD

**Issue by BilalXulfiqar** [crytic/echidna#1139]
### Describe the desired feature

I am using echidna first time, after installation when I try to run echidna-test , I get this error . not sure what I did wrong. Using eth-security-toolbox

**Comment by glarregay-tob** [comment]
The command was changed from `echidna-test` to `echidna`. 
Did you see `echidna-test` in the documentation? If so, can you please tell us where, to update it?

**Comment by BilalXulfiqar** [comment]
may bad I was following spearbit echidna tutorial.
