### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by 0xneves** [crytic/echidna#1141]
### Describe the issue:

I would like to run all possible tests in the repository without constantly needing to close the UI to proceed with each test.
According to: https://github.com/crytic/echidna/wiki/Config
You can deactivate the dashboard by setting it to false in the config yaml file. But the dashboard stays persistent:

![image](https://github.com/crytic/echidna/assets/90667119/c6f0bc22-d420-4547-a8f5-ac303fec1f5d)

### Code example to reproduce the issue:

dashboard: false

### Version:

Echidna 2.2.1

**Comment by rappie** [comment]
The `dashboard` setting doesn't seem to be working for me either.

You can also disable it by using the `--format text` option

> I would like to run all possible tests in the repository without constantly needing to close the UI to proceed with each test.

Could you elaborate on this? What do you mean with proceeding to another test?
