### ISSUE TITLE
[Bug-Candidate]: Incorrect wiki entry

### ISSUE THREAD

**Issue by VeryMilkyJoe** [crytic/echidna#1191]
### Describe the issue:

In the wiki the config entry `solc-args` is defined as `[String]` while what is actually expected is a `String`.

### Code example to reproduce the issue:

The wiki entry can be found [here](https://github.com/crytic/echidna/wiki/Config#parameters-in-the-configuration-file).

### Version:

2.2.2

**Comment by arcz** [comment]
@VeryMilkyJoe you are right, I updated the wiki page.
