### ISSUE TITLE
Enable TUI on Windows

### ISSUE THREAD

**Issue by arcz** [crytic/echidna#1198]
Brick supports Windows as of version 2.0 - https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md#20.

This requires bumping deps, blocked on https://github.com/NixOS/nixpkgs/pull/279413

**Comment by ggrieco-tob** [comment]
I think #1096 will solve this one.

**Comment by elopez** [comment]
I think you meant #1245, that one has Windows builds with UI support in case anyone is interested in trying them in the meantime.
