### ISSUE TITLE
Show coverage on constructors 

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/echidna#1208]
### Describe the desired feature

Currently, there is no coverage output for constructors on Echidna, which makes it challenging to determine what contracts failed during execution, and debug what arguments need to be changed when setting up the system. Would be fantastic to incorporate coverage on constructors, as this would allow us to remove the current logs that are necessary to determine where the constructions of contracts had failed. 

```solidity
        emit LogString("DEPLOYED: centralRegistry");
        _deployCentralRegistry();
```

**Comment by ggrieco-tob** [comment]
Duplicated of #539
