### ISSUE TITLE
Consider printing out hexadecimal representation of panics and the error msg for a specific panic

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/echidna#1210]
### Describe the desired feature

Consider displaying the hexadecimal value of the panic opcode or the [specific error messages](https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require) that are represented by the `Panic(17)`. Since this number is technically in decimal, it needs to be converted into hex for `Panic(0x11)`, thereby allowing us to determine that it is due to an arithmetic operation causing underflow. 

```
 └╴error Revert Panic(17) <no source map>
```

**Comment by 0xalpharush** [comment]
looks like it was removed in https://github.com/crytic/echidna/pull/1157 for context

**Comment by arcz** [comment]
Can you open an issue in hevm for this?

**Comment by 0xicingdeath** [comment]
@arcz done

**Comment by ggrieco-tob** [comment]
Let's check if this was fixed

**Comment by ggrieco-tob** [comment]
Already fixed
