### ISSUE TITLE
Opcode "mcopy" not implemented

### ISSUE THREAD

**Issue by 0xCheetah** [crytic/echidna#1218]
### Describe the issue:

The "mcopy" opcode in inline assembly reverts and produces an "e" in the corpus coverage report.

### Code example to reproduce the issue:

assembly ("memory-safe") {
  mcopy(0, 32, 32)
}

### Version:

echidna: 2.2.3
slither: 0.10.1

### Relevant log output:

```shell
"*e" in corpus coverage report.
```

**Comment by arcz** [comment]
Tracked in https://github.com/ethereum/hevm/issues/469.

**Comment by ggrieco-tob** [comment]
This was fixed, please test the latest release in `master`.
