### ISSUE TITLE
Improve UX around configuring Etherscan API key

### ISSUE THREAD

**Issue by devdacian** [crytic/echidna#1226]
### Describe the desired feature

Neither `echidna --help` nor the [example config](https://github.com/crytic/echidna/wiki/Config) provide a way to set the etherscan api key. Apparently it can be set by setting an environment variable `ETHERSCAN_API_KEY` but ideally this would be mentioned somewhere in the `--help` output.

**Comment by ggrieco-tob** [comment]
https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/advanced/state-network-forking.md#coverage-and-etherscan-integration

**Comment by rappie** [comment]
Making this available as a setting in the yaml config file would be great

**Comment by arcz** [comment]
We should also improve the error message to provide help right away

**Comment by elopez** [comment]
@arcz was there anything else you wanted to tackle in this issue other than the config file?
