### ISSUE TITLE
Support `startPrank` and `stopPrank` 

### ISSUE THREAD

**Issue by 0xicingdeath** [crytic/echidna#1229]
### Describe the desired feature

Echidna supports prank, only for the call immediately after the `hevm.prank` call. It would save a lot of time on setup to have a `startPrank` and `stopPrank` to wrap blocks of calls that we want to prank together in a file 

from chats with @glarregay-tob

**Comment by ggrieco-tob** [comment]
This was merged into hevm recently so it is coming.

**Comment by ggrieco-tob** [comment]
Let's close this one, since it is already working.
