### ISSUE TITLE
Improve error message on MaxInitCodeSizeExceeded issue

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#1242]
```
echidna: VM failed for unhandled reason, MaxInitCodeSizeExceeded 0xc000 (Lit 0x1d8ea). This shouldn't happen. Please file a ticket with this error message and steps to reproduce!
```

We should recommend to do `codeSize: 0xffffffff`

**Comment by ggrieco-tob** [comment]
Added a quick note in the Echidna FAQ: https://github.com/crytic/building-secure-contracts/pull/355

**Comment by Renzo1** [comment]
What's the fix for this error? I am having thesame issue.

**Comment by ggrieco-tob** [comment]
@Renzo1 Add `codeSize: 0xffffffff` to your config file
