### ISSUE TITLE
Improve error message if the function hashmap is not detected

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#1246]
https://github.com/crytic/echidna/blob/03787217d8a5af6bbc07f0ed36ca8a35436db898/lib/Echidna/Solidity.hs#L349-L361

If the user provides a wrong `filterFunctions`, echidna crashes and the error message is not really clear:
<img width="584" alt="image" src="https://github.com/crytic/echidna/assets/13798342/0b0a87ec-13f7-4ee3-987b-827620d63915">

We should change `Error processing function hashmaps` to something like `Please verify the "filterFunctions" option` or something like that, and ideally shows the ones that not found

**Comment by ggrieco-tob** [comment]
Good catch, we should fix this

**Comment by ggrieco-tob** [comment]
This should be fixed in https://github.com/crytic/echidna/pull/1258
