### ISSUE TITLE
[Bug-Candidate]: echidna: thread blocked indefinitely in an MVar operation

### ISSUE THREAD

**Issue by algobotishere** [crytic/echidna#1266]
### Describe the issue:

After getting to the falsified assumption, echidna stuck on shrinking 0/5000. Only thing that helps is exit, and the message is ```echidna: thread blocked indefinitely in an MVar operation```. 

Issue is connected to this: https://github.com/crytic/echidna/issues/1219 and this: https://github.com/crytic/echidna/issues/1209

The difference is in a persistency of a bug. 

Tried dev-ghc-9.6, and 2.2.1 without success. 

### Version:

2.2.3

**Comment by ggrieco-tob** [comment]
Do you have some code to reproduce this ?

**Comment by algobotishere** [comment]
Its a pretty big suit, can share in private
