### ISSUE TITLE
[Bug-Candidate]: General Malfunction

### ISSUE THREAD

**Issue by Renzo1** [crytic/echidna#1296]
### Describe the issue:

I've noticed a couple of issues, with the main one being that the test contract doesn't deploy, as shown in the snippet below. The first image is from a campaign run with an older version.

![CryticTester_Old](https://github.com/user-attachments/assets/2543d6c4-9df3-4710-bfb2-7ef0826fa2a3)
[Image 1: Screen shot of old fuzz campaign]

![CryticTester_New](https://github.com/user-attachments/assets/e08e4a0c-8d8e-41b3-b821-4ce05322dbf5)
[Image 2: Screen shot with latest Medusa (version 0.1.5)]

Additionally, the corpus for the Target Functions is misleading. It indicates that the tested contract is called, but there is no real effect because even the simplest assertions that should break by calling the contract pass.

This issue initially appeared with Medusa, which gave this runtime error:

```
panic: runtime error: invalid memory address or nil pointer dereference

    panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca727b]

```

The contract compiles and shows signs that it is about to start fuzzing, but it doesn't progress beyond zero sequences. Something like this: `⇾ fuzz: elapsed: 6s, calls: 4 (50/sec), seq/s: 0, coverage: 3`.

When I tried Echidna, it ran, but the corpus shows that the test contract constructor is never called. The `targetFunctions` still show as green, but there is no real effect, as mentioned earlier.

Initially, I suspected it might be an issue with my tested contract or setup, but after hours of reviewing my code and confirming that Foundry is working fine, I suspect it might be related to recent upgrades in the fuzzers. To verify, I fuzzed an old project, which confirmed the issue for me.

I tested this on several projects, and the problem persists. I even cloned and built the default Recon-Foundry project without making any changes, and the issue persisted -- test contract constructor is not hit.

You can try it yourself:

```
forge init --template https://github.com/Recon-Fuzz/create-chimera-app
```

I'd like to know if anyone else has experienced this issue and, if so, how you resolved it, or if there's a recommended stable version to downgrade to.

### Code example to reproduce the issue:

forge init --template https://github.com/Recon-Fuzz/create-chimera-app

### Version:

Echidna version: 2.2.4

Slither version: 0.10.3

### Relevant log output:

```shell
panic: runtime error: invalid memory address or nil pointer dereference

    panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca727b]
```

**Comment by ggrieco-tob** [comment]
Hi!,

Regarding echidna, the tool does not record coverage during deployment, so it will not be in the report, but it should work fine. This is a known issue (#539). Regarding the medusa crash, you will need to open a issue report in the medusa issue tracker so we can discuss it there.  

Closing this, as a duplicate of an issue we already have.

**Comment by Renzo1** [comment]
Opened the medusa issue: https://github.com/crytic/medusa/issues/410
