### ISSUE TITLE
[Bug-Candidate]: vm.startPrank() not working

### ISSUE THREAD

**Issue by 0xJoichiro** [crytic/echidna#1308]
### Describe the issue:

VM failed for unhandled reason, BadCheatCode 0x6447d56. This shouldn't happen. Please file a ticket with this error message and steps to reproduce! Stack trace: call HEVM::startPrankXD(0x000000000000000000000000000000000001E240)

### Code example to reproduce the issue:

any basic code that uses vm.startPrank()

### Version:

Echidna 2.2.4

### Relevant log output:

```shell
VM failed for unhandled reason, BadCheatCode 0x6447d56. This shouldn't happen. Please file a ticket with this error message and steps to reproduce! Stack trace: call HEVM::startPrankXD(0x000000000000000000000000000000000001E240)
```

**Comment by ggrieco-tob** [comment]
`startPrank` support is coming. It is implemented in hevm, but we haven't upgraded yet.

**Comment by 0xJoichiro** [comment]
@ggrieco-tob undertood,actually is saw #1229 and it was ended with as it works therefore had to ask.We can close this if you want now

**Comment by arcz** [comment]
Are you sure you are calling `startPrank`? The trace shows `startPrankXD`.

**Comment by 0xJoichiro** [comment]
@arcz yes sir I did call startPrank(),as i saw the same trace message.Cross checked on my part have been fuzzing using echidna and its been an issue converting foundry tests into echidna ones

**Comment by ggrieco-tob** [comment]
Can you try using echidna from `master`?

**Comment by elopez** [comment]
Echidna 2.2.5 should have startPrank, with the caveat that CREATEs don't get pranked yet, hevm upstream is tracking it in https://github.com/ethereum/hevm/pull/564 -- let us know if you still experience issues after you upgrade though!
