### ISSUE TITLE
[Bug-Candidate]: `abi.encodePacked` failing with solc 0.8.25 and cancun evm version

### ISSUE THREAD

**Issue by shaka0x** [crytic/echidna#1315]
### Describe the issue:

I was getting the `Deploying the contract * failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)` error in my project. Unfortunately this error is quite hard to debug. After long time changing my code and commenting out stuff I realized the problem was in the execution of `abi.encodePacked` in my setup function.

My foundry.toml file includes the following:
```toml
evm_version = "cancun"
solc = "0.8.25"
```

Commenting out the evm_version or lowering solc to 0.8.24 removed the issue. So the problem seems to be using `abi.encodePacked` in the constructor when I am using cancun evm version and solc 0.8.25.

Same error appears if I use `abi.encode`.

### Code example to reproduce the issue:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

contract Tester {
    constructor() payable {
        bytes memory b = bytes("foo");
        abi.encodePacked(b);
    }

    function foo() public {}
}
```

### Version:

2.2.4

### Relevant log output:

```shell
echidna: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.):
```

**Comment by wardahub-design** [comment]
maybe this will help
https://bit.ly/3XQLHlH
If you don't have the c compliator, install it.(gcc or clang)

**Comment by elopez** [comment]
Hi! Echidna 2.2.4 does not have full support for Cancun, so maybe you're hitting one of the limitations there. Do you see the same issue if you run with solc 0.8.24? Alternatively, try updating to a newer echidna build from the master branch, we recently updated hevm and that should hopefully mean it supports Cancun fully.

**Comment by elopez** [comment]
This should be working now with the release of Echidna 2.2.5, but let us know if you still have issues!
