### ISSUE TITLE
Automated build on Docker Hub

### ISSUE THREAD

**Issue by pot8to** [crytic/echidna#134]
The repository owner can configure [automated builds](https://docs.docker.com/docker-hub/builds/) so that users can download it from Docker Hub instead of building it manually!

**Comment by ggrieco-tob** [comment]
That's a great idea. I will take a look to this during the week.

**Comment by japesinator** [comment]
we actually don't have automated builds, I've been getting stuff up manually

**Comment by ggrieco-tob** [comment]
This is done.
