### ISSUE TITLE
How do I add new addresses?

### ISSUE THREAD

**Issue by mirathewhite** [crytic/echidna#135]
I want to write solidity tests to use with echidna-test, and I need to use more than 3 addresses. Questions:
1. In what file(s) do I define the new addresses?  I see addrList in several *.yaml files in the project.
2. Is there a special utility for generating addresses, or do I just add random ethereum addresses?  Do I need to add private keys somewhere?
3. If I want to test how two contracts interact, can I just deploy the second contract within the constructor?

It would be helpful if this information was added to the README file.  Thank you.

**Comment by incertia** [comment]
1. the `senders` field of the config file. the defaults can be found [here](https://github.com/crytic/echidna/blob/master/examples/solidity/basic/default.yaml)
2. you just need random ethereum addresses
3. you should be able to deploy the second contract within the constructor
