### ISSUE TITLE
Add documentation about effectively using asserts to the docs

### ISSUE THREAD

**Issue by dguido** [crytic/echidna#145]
https://blog.regehr.org/archives/1091

**Comment by ggrieco-tob** [comment]
Please let me know if this looks like what you expected: https://github.com/crytic/echidna/wiki/Assertion-checking-with-Echidna

**Comment by ggrieco-tob** [comment]
We already have this in [building-secure-contracts](https://github.com/crytic/building-secure-contracts/).
