### ISSUE TITLE
Add an example that uses the "Master Contract" pattern

### ISSUE THREAD

**Issue by ESultanik** [crytic/echidna#155]
Add an example that uses the pattern in which the "master" Echidna test contract instantiates two or more other contracts that are the ones actually being tested.

**Comment by bandrebandrebandre** [comment]
Any way this could get added? Would be really helpful.

**Comment by ggrieco-tob** [comment]
https://github.com/crytic/echidna/wiki/How-to-use-Echidna-with-multiple-contracts
