### ISSUE TITLE
Unable to execute example in readme file: "commitBuffer: invalid argument"

### ISSUE THREAD

**Issue by ealmansi** [crytic/echidna#159]
Hi,

I'm running the following steps from the readme file:

1. `docker pull trailofbits/echidna`
2. `docker run -v `pwd`:/src trailofbits/echidna echidna-test /src/solidity/cli.sol`

And I'm getting the following output displaying an error:

```
"Analyzing contract: /src/solidity/cli.sol:Test"
echidna-test: <stdout>: commitBuffer: invalid argument (invalid character)
```

---

Additional details:
- I'm running this from echidna's root directory.
- Ubuntu 18.04.1 LTS
- Docker version 18.09.1, build 4c52b90

**Comment by Sprimage** [comment]
Hi, i believe the wiki will be updated soon. But you might want to try pulling the `eth-security-toolbox` docker as it might be a better option

``` 
     $ docker pull trailofbits/eth-security-toolbox
     $ docker run -it trailofbits/eth-security-toolbox
```

**Comment by ggrieco-tob** [comment]
Hi @ealmansi, can you re-try with a the latest echidna docker container? Take a look to the updated README because we included some new flags:

```
$ docker run -t -v `pwd`:/src trailofbits/echidna echidna-test /src/examples/solidity/basic/flags.sol
```

**Comment by ggrieco-tob** [comment]
Closing this inactive bug. Please re-open if when you try the new docker.
