### ISSUE TITLE
Eliminate view and pure functions from call sequences

### ISSUE THREAD

**Issue by mrice32** [crytic/echidna#161]
It seems that `view` (and I assume `pure`) functions are part of Echidna's call sequences (I noticed a public getter was being included in many sequences, for instance). Is this intended behavior? Since these functions can't change the state of the contract and, therefore, can't affect the result of any future invariant checks, shouldn't Echidna prune these functions from its list of callable functions?

**Comment by ggrieco-tob** [comment]
I think this won't be an issue if #197 is merged. What do you think @agroce ?

**Comment by agroce** [comment]
It won't be as critical, it'll still lower the effectiveness, and increase the `seqLen` needed for same test effectiveness.   If it's a giant pain to do, then #197 is enough for now, but if it's moderately easy it'd certainly increase efficiency a decent amount for contracts with lots of `view`/`pure` functions, I would guess.

**Comment by ggrieco-tob** [comment]
This can be fixed with a proper slither integration. However, there is an interesting point here. Removing the view/pure function will lower the collected coverage, which is one measure to check how good a contract was tested. Perhaps we should execute these functions once?

**Comment by agroce** [comment]
True.  Also, is it guaranteed such fns do not ever cause bad opcode (assert etc.)?

**Comment by ggrieco-tob** [comment]
#396 should fix this (`view`/`pure` functions are considered low priority, unless they contain an explicit `assert`).

**Comment by ggrieco-tob** [comment]
This is already done.
