### ISSUE TITLE
Address literals do not respect EIP-55

### ISSUE THREAD

**Issue by Xenomega** [crytic/echidna#176]
Echidna documentation often references an address literal, and echidna itself often outputs an address literal during execution.

These addresses are not EIP-55 compliant, see here:  https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md.

As such, copying any addresses from documentation or echidna output directly into your tests will make newer `solc` versions error, complaining  that the address has an invalid checksum.

Moving forward, all addresses output by echidna + mentioned in documentation should be EIP-55 complaint. 

Side note: I have updated this wiki page for reference (others still remain outdated): https://github.com/trailofbits/echidna/wiki/Tutorial:-How-to-test-a-property

**Comment by ggrieco-tob** [comment]
This is correctly handled by hevm already. Sorry it took so long @Xenomega
