### ISSUE TITLE
What types of vulnerability does Echidna support? 

### ISSUE THREAD

**Issue by ReeceNee** [crytic/echidna#190]
such as: re-entreny, integer overflow etc.

**Comment by ggrieco-tob** [comment]
Echidna can help to discover any issue in your contracts as long as you can write a Solidity property to express it (e.g. the balance of tokens of a user cannot decrease). Please join the [Slack channel](https://empirehacking.slack.com/messages/C7KKY517H/) to continue this discussion.

**Comment by ReeceNee** [comment]
> Echidna can help to discover any issue in your contracts as long as you can write a Solidity property to express it (e.g. the balance of tokens of a user cannot decrease). Please join the [Slack channel](https://empirehacking.slack.com/messages/C7KKY517H/) to continue this discussion.

Thanks for your quik replay! How should I join the slack channel with none permission?
