### ISSUE TITLE
Add Embark support

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#203]
Similarly to Truffle, we should support [Embark](https://embark.status.im/).

We can use our [embark plugin](https://github.com/crytic/embark-contract-info/) to extract the ABI and the bytecode of each contract, and loads the info into echidna.

**Comment by ggrieco-tob** [comment]
This should be covered by #204 using `crytic-compile`, right?

**Comment by ggrieco-tob** [comment]
I can confirm #204 works with Embark, however we are still refactoring that PR.

**Comment by ggrieco-tob** [comment]
Fixed in the latest release.
