### ISSUE TITLE
Support properties that SHOULD revert

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#214]
If property name has _reverts in it, consider result false/failed unless the transaction reverts.

Distinct from config-level allowing all props to revert or return true:

- per property avoids danger of accidental vacuity

- forces, vs. allows, revert (can simulate with return false at config level of course)

**Comment by ggrieco-tob** [comment]
While the return value equal to `false` can be implemented right now, the revert is undetected. I propose to make `_revert` transaction *only* to succeed in revert. What do you think?

**Comment by agroce** [comment]
Yeah, that's ideal.  Good!
