### ISSUE TITLE
Investigate more intelligent constant mining

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#216]
- Use SlithIR to improve the ease of improving this?

- Invert simple arithmetic operations, without using symbolic execution or anything costly/fancy.  E.g., mine "4" (and nearby constants 3 and 5) from "if (x * 2) == 8".

- It's NOT a good idea to extend current mining of i-1, i, i+1 to, e.g., i-8, i, i+8 -- we don't have weights on constants right now, and you need a decay with distance, or cases like `single.sol` where you need to hit several exact constants become too hard.  i is most valuable constant, i-1 and i+1 are worth having to handle inequalities, but further out requires weighting

- so, investigate value of weighting mined constants; right now, I think we "weight" a constant we see multiple times, since the dictionary is not a set, at least

**Comment by agroce** [comment]
Long-term, we just want to ask Slither for good constants, get them via json or something

**Comment by montyly** [comment]
That should be trivial to get with Slither.

We can either have an ad-hoc script, or create a slither util for that (`slither-constant-extraction`).
Example of ad-hoc script:

```python
import json
from slither import Slither
from slither.visitors.expression.expression import ExpressionVisitor
from slither.slithir.variables import Constant

# Note: expressions initializing state variables are not yet converted to slithIR
class ExportLiteral(ExpressionVisitor):

    def result(self):
        return self._result

    def _post_literal(self, expression):
        # Convert to Constant to get the conversion between int and string
        constant = Constant(expression.value)
        if self._result is None:
            self._result = [constant]
        else:
            self._result.append(constant)

slither = Slither('constant.sol')

constants = []

for contract in slither.contracts:
    for variable in contract.state_variables:
        if variable.initialized:
            ev = ExportLiteral(variable.expression)
            res = ev.result()
            constants += res

    for function in contract.functions_and_modifiers:
        for ir in function.slithir_operations:
            for read in ir.read:
                if isinstance(read, Constant):
                    constants.append(read)

json_output = list(set([x.value for x in constants]))

print(json.dumps(json_output))
```

Which will output for:
```
contract C{

    uint a = 10;

    string st = "this_is_a_test";

    function f() public{
        uint l;
        require(l == 20);
    }

}
```
```
[10, 20, "this_is_a_test"]
```

We can do more advanced stuff, like:
- extracting the number of occurrences of each constant, 
- adding a flag if the constant is directly used in a comparison, 
- adding a flag if the constant is used in loop comparison (which could indicate its the size of an array)
- if the constant is used in a direct binary operation (*, +, -, ...), we can extract the binary operator
- ..

**Comment by ggrieco-tob** [comment]
There is [a PR to integrate the use of crytic-compile](https://github.com/crytic/echidna/pull/204). Maybe we should add this script/util/feature to that tool, instead of slither itself?

**Comment by agroce** [comment]
I think having slither/crytic-compile produce not just constants but weights, and changing the dictionary to work with weighted sets, is the way to go here, maybe...

**Comment by ggrieco-tob** [comment]
crytic-comple support is merged. Maybe we should integrate this in that tool adding a new field?

**Comment by ggrieco-tob** [comment]
This feature can be improved after merging the Slither integration (#396).

**Comment by ggrieco-tob** [comment]
This is already done, moving the discussion to another issue
