### ISSUE TITLE
Integrate coverage/mutation code

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#218]
Right now, `spliceTxs` in `Transaction.hs` is never called, so nothing much happens with mutation of new-cov transactions

**Comment by ggrieco-tob** [comment]
Please take a look to #246

**Comment by agroce** [comment]
Do we have/need tests of this?

**Comment by ggrieco-tob** [comment]
We need to test and discuss it. This is only the first approach.

**Comment by agroce** [comment]
Did we actually finish this?

**Comment by ggrieco-tob** [comment]
After merging #353 and #357, I will work on this.

**Comment by ggrieco-tob** [comment]
We already have some mutations based on the corpus collected, and we are reviewing some more (#372). Please test the latest revision and suggest more improvements.
