### ISSUE TITLE
Support timeout

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#226]
Define testing period by wall clock time, not number of tests.  Better for mutation testing/CI.

**Comment by ggrieco-tob** [comment]
Please test #251

**Comment by agroce** [comment]
Will do, probably tomorrow (on NAU and DARPA stuff today)

**Comment by agroce** [comment]
This is in master/release now, and works fine

**Comment by agroce** [comment]
Never mind, still not done

**Comment by agroce** [comment]
In with PR #320
