### ISSUE TITLE
Missing Contributing.md

### ISSUE THREAD

**Issue by johnsoncarl** [crytic/echidna#229]
The library is missing a proper `contributing.md` file, to help the developers to participate in and develop the library/tool to the best.

Developers, please try a little to add it. 

Many Thanks!

**Comment by ggrieco-tob** [comment]
I created this draft PR to start the discussion: https://github.com/crytic/echidna/pull/231 

Feel free to comment any improvements there.

**Comment by ggrieco-tob** [comment]
Fixed.
