### ISSUE TITLE
Ether holding contract and Multi contract not supported.

### ISSUE THREAD

**Issue by johnsoncarl** [crytic/echidna#232]
I have looked into some missing functionality in echidna. 
It has some incomplete/ongoing work in implementing the following functionalities.

- [x] The ability of a contract to hold ether
- [x] Ability of the tool to deploy multiple contracts and transact between them

**Comment by ggrieco-tob** [comment]
> The ability of a contract to hold ether

That should be supported in #240, but please test it just to be sure :smile:

**Comment by ggrieco-tob** [comment]
All these functionality are already implemented.
