### ISSUE TITLE
Lost ability to specify solc compiler options 

### ISSUE THREAD

**Issue by elenadimitrova** [crytic/echidna#253]
Reiterating #36 which was solved but since we've lost that ability again. Now running
`echidna-test contracts/ColonyTaskTest.sol --solc-args="--allow-paths=lib/dappsys/*.sol"`

returns 

`Invalid option `--solc-args=--allow-paths=lib/dappsys/*.sol'`

**Comment by ggrieco-tob** [comment]
Using `--solc-args` in the command line is deprecated. Please use the `solcArgs` option in a [config file](https://github.com/crytic/echidna/wiki/Config).

**Comment by akugone** [comment]
Have you got any info on how set up the config file for openzeppelin remapping ?
