### ISSUE TITLE
Deploying two blockchains and run the parallel transactions on both to ensure deterministic behaviour of Blockchains

### ISSUE THREAD

**Issue by johnsoncarl** [crytic/echidna#268]
How about giving a parameter to deploy two Blockchain (EVM) instances and running the contracts on them **concurrently/Parallel** . This will help in ensuring the deterministic behaviour of the smart contracts on the blockchain!

**Comment by ggrieco-tob** [comment]
After thinking in this, I'm not completely sure to understand this request. Running code in echidna is completely deterministic, so there is no way execute the same function with the same parameters and obtain two different results (given that the state of the blockchain is the same)

**Comment by johnsoncarl** [comment]
I agree with you @ggrieco-tob .
But there are really interesting use cases to it. I'll try to get it done and get back to you soon. 


Closing this issue for now. I'll reopen it as things work.
