### ISSUE TITLE
Echidna does not work with solc >= 0.5.5

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#278]
Tested with echidna from eth-security-toolbox: 

```solidity
contract Test{

    function nothing() public{

    }

    function echidna_test() public view returns(bool){
        return true;
    }
}
```

If this contract is compiled with solc >=0.5.5, echidna fails:
```
echidna_test: failed with no transactions made ⁉️  
```

[`0.5.5`](https://github.com/ethereum/solidity/releases/tag/v0.5.5) was the first version using `petersburg` as the default EVM set, most likely hevm does not support properly the new ocpodes?

**Comment by ggrieco-tob** [comment]
0.5.7 works for me locally (Ubuntu 18.04). I will investigate why it fails in eth-security-toolbox.

**Comment by montyly** [comment]
This seems to work on the latest version of echidna (eth-security-toolbox was updated)
