### ISSUE TITLE
Feature request: finding worst-case execution gas with echidna

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#286]
We could use echidna to provide a summary of the worst-case execution gas of each function (not just the properties).

That would help to find out-of-gas issues, and to profile which functions need to be optimized.

**Comment by yxliang01** [comment]
@montyly Just a question (possibly out of scope), how can echidna a fuzzer find the worst-case execution gas? I believe this is going to be an estimation. Would you like to comment on how close such estimation you are thinking it's going to be? Thanks.

**Comment by montyly** [comment]
Yes it's going to be an estimation and not a guarantee.

The precision will depend on the complexity of the contracts, and the capacity for echidna to explore the states, so it's hard to say. The goal here would not be to ensure a bound on the gas consumption but to find bad gas usage with a best approach effort, in a minimal amount of time.

We can start with a naive version which just fuzz randomly all the functions.Then we can probably tune the exploration with some heuristics (ex: by locating targets with Slither)

**Comment by yxliang01** [comment]
Just curious, how are you planning to deal with paths containing external contract calling while the external contract is not accessible(e.g. its address can dynamically be set)?

**Comment by montyly** [comment]
Well, I guess it's not a problem related to the gas estimation, but a general concern for echidna exploration?

But in that case, you can just fuzz all the addresses parameters with all known addresses (including all the contracts created)

**Comment by ggrieco-tob** [comment]
Fixed in #355 (this needs some documentation, but I will do that soon).
