### ISSUE TITLE
Echidna shrinker (too) often fails to remove un-needed gas price

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#308]
Example contract:

```
contract TEST {
  uint256 constant A = 999120;
  uint256 n = 0;

  function f (uint256 newn) external {
    n = newn;
  }

  function echidna_checkIt() external view returns (bool) {
    return (n < A);
  }
}
```

Obviously, you don't need a non-zero delay or any sender changes here.  But running with completely default echidna settings, 17% of the time, echidna reports a non-zero Time or Block delay in the found sequence.

There are no bogus sender values that didn't shrink away, but those can be produced using this contract plus assertion checking, and likely arise from same shrinker inadequacies:

```
contract TEST {
  uint256 constant A = 999120;
  uint256 n = 0;

  function f (uint256 newn) external {
    if (newn >= 0) {
      n = newn;
    }
  }

  function checkIt() external view returns (bool) {
    assert (n < A);
    return true;
  }
  
  function crytic_notrans() external view returns (bool) {
    return false;
  } 
}
```

**Comment by agroce** [comment]
This is moderately important, in that I think crytic users especially may be very confused if a sequence for a property violation includes a time delay or changed sender when this is actually totally irrelevant.  I could see this being a big frustration to understanding a bug (in contract or in a property) if you aren't savvy to echidna internals

**Comment by agroce** [comment]
Does #310 fix this?  Ready to close?

**Comment by arcz** [comment]
@agroce yes, this should be fixed

**Comment by agroce** [comment]
I did a pretty thorough check, it's fixed.

**Comment by agroce** [comment]
Reopening this, with small shrink limits, or detection near timeout, gas prices often stick around, even though 99% of failures don't need gas price changes.  We should probably just deterministically try 0 gas price & delay etc. at the start of reduction, since it usually will work and is cheap

**Comment by incertia** [comment]
are we able to close this now?

**Comment by agroce** [comment]
I haven't tested it out, is everything in master, so I can see if it fails to get rid of gas/delay/sender more than feels right?

**Comment by agroce** [comment]
(or if @arcz tested for this on this contract or similar, we can just close, of course!  I don't know if this was a driving force in his work...)

**Comment by arcz** [comment]
Yes, getting to 0 is faster now.
