### ISSUE TITLE
Clarify `coverage` option meaning

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#325]
At present, if you don't specify `coverage` in the config file, echidna collects and uses coverage to guide testing, but doesn't output the coverage.  `coverage: true` also outputs coverage.  `coverage: false` turns off coverage completely.

This is fairly unobvious to users, and there's no way to lock the three-valued logic 1/2 that is default (also, not sure it's that helpful to compute coverage but hide that from the user).

Plus, `coverage` isn't in `default.yaml`.

**Comment by ReeceNee** [comment]
In the `examples/solidity/coverage/harvey.yaml`, even `coverage: true` set there is still no coverage information output. Where is the coverage info?

**Comment by agroce** [comment]
Good catch.  That's just a bug in the `harvey.yaml` config, it should be `coverage` not `printCoverage`.

**Comment by ReeceNee** [comment]
May I ask that where can I see the coverage info? I can't see any percentage of coverage even if I set `coverage:true` in the config file.

**Comment by agroce** [comment]
Right now it's just:

```
Unique instructions: 193
Unique codehashes: 1
```

Which isn't that informative!

**Comment by ReeceNee** [comment]
> Right now it's just:
> 
> ```
> Unique instructions: 193
> Unique codehashes: 1
> ```
> 
> Which isn't that informative!

Thanks. By the way, is there any way to use echidna to run solidity files without echidna_xx functions?  I just what to evaluate the coverage of echidna.

**Comment by agroce** [comment]
Add `checkAsserts: true` to the config

It'll report assertion violations, other unexpected aborts, but just coverage if nothing fails

**Comment by uhbif19** [comment]
What do "Unique instructions" and "codehashes" mean?

**Comment by ggrieco-tob** [comment]
@uhbif19 sorry for the delay (all the team was in holiday when you posted this). 
* Unique instruction is the amount of EVM addresses with instructions reached by Echidna. 
* Codehashes is the amount of different contracts deployed (each one will have a different hash for their code)

**Comment by uhbif19** [comment]
@ggrieco-tob Is it possible to count `Unique instruction` available, to count percent value of coverage?

**Comment by ggrieco-tob** [comment]
We only provide a raw count of unique instructions (pc), however, the percentage can be computed  using the number of total number of pcs from `slither --print evm contract.sol`.

**Comment by uhbif19** [comment]
@ggrieco-tob Is this commit related to issue? https://github.com/crytic/echidna/commit/ca02d7b8b38a19805b544716dcf7b111c82ee606

**Comment by ggrieco-tob** [comment]
No, that's another thing.
