### ISSUE TITLE
Echidna fails with solc 0.6.x

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#337]
For example with:
```solidity
contract Test{

    bool v = true;

    function set(bool a) external{
        v = a;
    }

    function echidna_test() view external returns(bool){
        return v;
    }

}
```
If echidna is called with 0.5.14, everything works:
```
SOLC_VERSION=0.5.14 echidna-test-1.2.0.0 test.sol
```

But if 0.6.0 is used, echidna crashes:
```
$ SOLC_VERSION=0.6.0 echidna-test-1.2.0.0 test.sol 
echidna-test-1.2.0.0: srcmap: y u ':'?!?
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:175:53 in hevm-0.34-E1OHcXdyucEH4I2ysQZGB6:EVM.Solidity
```

It looks like the src mapping format slightly changed:
```
0.5.14:
"srcmap": "0:176:0:-;;;29:4;20:13;;;;;;;;;;;;;;;;;;;;0:176;8:9:-1;5:2;;;30:1;27;20:12;5:2;0:176:0;;;;;;;",
0.6.0:
"srcmap": "0:176:0:-:0;;;29:4;20:13;;;;;;;;;;;;;;;;;;;;0:176;8:9:-1;5:2;;;30:1;27;20:12;5:2;0:176:0;;;;;;;"
```

The [Solidity 0.6 changelog](https://github.com/ethereum/solidity/releases/tag/v0.6.0) mentions:
```
Source mappings: Add "modifier depth" as a fifth field in the source mappings.
```

Most likely this "modifier depth" is not handled by hevm?

**Comment by ggrieco-tob** [comment]
We should wait for hevm to merge [this](https://github.com/dapphub/dapptools/pull/316).

**Comment by incertia** [comment]
aside: `stripBytecodeMetadata` was also merged into hevm so we should delete our local version when bumping the version.

**Comment by MrChico** [comment]
hevm 0.37 now supports 0.6.x source files

**Comment by ggrieco-tob** [comment]
Thanks a lot @MrChico!. We will prepare a PR to upgrade to hevm 0.37 soon.

**Comment by ggrieco-tob** [comment]
@montyly #383 should fix this. Please test it.

**Comment by ggrieco-tob** [comment]
This is already fixed. Please re-open if some example fails.
