### ISSUE TITLE
Feature request: filtering the functions to be called 

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#341]
Right now Echidna will call all the functions from the contract's ABI. It would be nice to be able to restrict the exploration, either through a whitelist or a blacklist.

For the API, I think we could use the configuration file, with two new fields: `functionsToBeCalledWhitelist`,  `functionsToBeCalledBlacklist` (or with better names).

**Comment by incertia** [comment]
can we just make these a single JSON object which defaults to blacklist

```yaml
filter:
  blacklist: true
  functions: []
```

**Comment by ggrieco-tob** [comment]
Fixed. I'm writing some examples/documentation for this feature.
