### ISSUE TITLE
Emit a warning if a function almost always reverts when called

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#342]
Good coverage is essential to keep fuzzing effective. Unfortunately, in Echidna we have no way to know if the code of a contract is covered or not, without modifying the contract and add a property that fails if it reaches certain point. This could give a false sense of security to users, since they believe their code is secure, if all the tests are passing.
 
One possible way to tackle this is to warn the user if a certain function reverts almost always (maybe less than 10% of the times it was called?).

**Comment by incertia** [comment]
with the advent of `multi-abi` how do you wanna do this? per contract per function or just per function in known abis?

**Comment by ggrieco-tob** [comment]
We have source code integration, there is no need for this.
