### ISSUE TITLE
How can I see more detailed test results?

### ISSUE THREAD

**Issue by AminoACID123** [crytic/echidna#358]
I've just learnt to use Echidna and it seems that it does not present very detailed test info like code coverage. How to configure Echidna so that I can get more informative test results?

**Comment by ggrieco-tob** [comment]
We have in our roadmap a feature to offer more informative test results (e.g. which lines are executed) but it is not implemented yet.

**Comment by ggrieco-tob** [comment]
We are planing to add a [Slither](https://github.com/crytic/slither) printer to know exactly which lines Echidna reached. Is that what you expect for this feature?

**Comment by AminoACID123** [comment]
Yes, that'll be nice.

**Comment by JackHFeng** [comment]
@ggrieco-tob Hello Gus, thank you for your reply in my other post, I was wondering if instruction coverage on opcode is available? I read a few other posts, is the reason for instruction coverage not being available due to the instrumentation Echidna does? Since Echidna adds new codes to the source, it can be difficult to precisely know which opcode belongs to the original contract or not right?

**Comment by ggrieco-tob** [comment]
If you use `format: json` and `coverage: true` you will get, at the end of the campaign a list of `pc` covered by echidna (either in complete or reverted transactions) by each list of transactions in the collected corpus.

> Since Echidna adds new codes to the source, it can be difficult to precisely know which opcode belongs to the original contract or not right?

This is not exactly true. Echidna will compile to test contract normally. If you add `echidna_` functions to test, these are going to be new instructions. But if you use `checkAssertions` or `benchmarkMode`, the contract to test will run as it is.

**Comment by alexon1234** [comment]
Hi, 

I was wondering if there is a way to get the state variables when the test failed? 

Thanks

**Comment by ggrieco-tob** [comment]
Uhm, I think it could be possible, but we have to internally discuss it first. What is the use case exactly?

**Comment by ggrieco-tob** [comment]
Closing in favor of #656
