### ISSUE TITLE
echidna does not handle "push/pop" patterns well

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#361]
consider this contract:
```
contract TEST {

  address [] addrs;

  function push(address a) public {
    addrs.push(a);
  }

  function pop() public {
    if (addrs.length > 0)
      addrs.length--;
  }

  function clear() public {
    addrs.length = 0;
  }

  function traverse() public returns (bool) {
    for (uint i = 0; i < addrs.length; i++)
      for (uint j = 0; j < addrs.length; j++) {
	if ((addrs[i] == addrs[j]) && (i != j)) {
	  return true;
	}
      }
    return false;
  }

  function echidna_grow() public returns (bool) {
    return addrs.length < 20;
  }
}
```

Even at 1M tests, e.g. with this config:
```
testLimit: 1000000
estimateGas: true
```

Echidna will almost certainly fail to falsify the property right now, and will provide a very low estimate on `traverse`'s worst-case gas consumption.  E.g., with 1M tests we get:

`traverse used a maximum of 115832 gas`

but if we remove `pop` and `clear` we get a higher estimate, even with only 1K tests:

`traverse used a maximum of 416218 gas`

https://github.com/crytic/echidna/issues/328 would probably handle this example, but is not the only solution; adding gas high water as a "coverage" event might also work, as would some other strategies.  This issue is for the general problem, not one solution.

**Comment by agroce** [comment]
Note that if you up to 10K tests, the version without pop/clear gets a max of 1597285 gas for traverse; the difference here between an accurate and bad estimate can easily be orders of magnitude.

**Comment by ggrieco-tob** [comment]
#372 should eventually solve this (since we have a suitable mutation that repeats one transaction  from the corpus up to 32 times). Can you re-test with that?

**Comment by agroce** [comment]
Another thing that helps here is if you have any coverage targets that branch on sizes of arrays of interest; those stick around in corpus giving echidna a shortcut to higher length lists, looks like.  @ggrieco-tob how does corpus get used?  Mutation only or do you extend corpus tests to go over seqLen?

**Comment by ggrieco-tob** [comment]
I think echidna-parade is the right tool for this, so I'm closing this issue as out of scope.
