### ISSUE TITLE
Does Echidna uses node RPC or internal EVM?

### ISSUE THREAD

**Issue by pavlovdog** [crytic/echidna#362]
Hi, guys!

I've carefully read the README but it's still not clear for me - can I specify some RPC details to perform fuzzing on the specific network? Or all the method calls are running on some internal Haskell-based EVM implementation?

I'm pretty sure that the second guess is correct, but I'm not a big expert in Haskell to make sure myself 😃

Thanks in advance!

**Comment by ggrieco-tob** [comment]
Hi @pavlovdog 

We are using [HEVM](https://github.com/dapphub/dapptools/tree/master/src/hevm) to emulate the Ethereum Blockchain internally. However, we have some preliminary support for RPC calls, to initialize a contract before a fuzzing campaign. Please take a look to [this tutorial](https://github.com/crytic/echidna/wiki/Deployment-of-a-contract-using-Truffle,-Ganache-and-Etheno-to-test-with-Echidna) if you want to know more.
