### ISSUE TITLE
Coverage collected on large contracts decreased since version 1.2.0.0

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#380]
While micro-benchmarking using CI tests is working great (Echidna can deal with more complicated contracts every day), some preliminary data on coverage collected in a large contract indicates that it is decreasing the number lines reached since version 1.2.0.0:

```
1.1.0.0,  6961
1.2.0.0, 11784
1.3.0.0, 10849
1.4.0.0, 10595
```

The latest release need to adjust some constants, but the big drop on coverage since 1.2.0.0 is still unexplained.

**Comment by incertia** [comment]
do you think this could be due to an adjustment of various `callseq` (now `randseq`) parameters?

**Comment by agroce** [comment]
`fallback` added without seqlen default change?

also, how long are these runs, because that amount of change _could_ be noisy, if you don't have really long/saturating runs or enough to get a good mean...

**Comment by ggrieco-tob** [comment]
I should re-run this and re-open if necessary.
