### ISSUE TITLE
Multi-threaded tests

### ISSUE THREAD

**Issue by nostdm** [crytic/echidna#382]
It seems that by default `echidna-test` uses a single thread at 100% load. 

I checked the configuration options and it doesn't seem that there's an option to allow multi-threaded tests. 

Is this a fundamental limitation of echidna or is this still being worked on?

Given that most fuzzers tend to be concurrent I would've assumed this was also true of echidna.

**Comment by ggrieco-tob** [comment]
You are right, echidna uses a single thread. The use of EVM does not allow to easily multiple threads, however, there is a way to run any number of echidna process in parallel using a single corpus. I will write a tutorial on how to do it soon.

**Comment by ggrieco-tob** [comment]
This already works. Check this tutorial: https://github.com/crytic/building-secure-contracts/pull/55/
