### ISSUE TITLE
How to test contract with large dependencies

### ISSUE THREAD

**Issue by nostdm** [crytic/echidna#401]
I'm trying use echidna to test a contract that depends on ENS resolver, ENS registry, on-chain oracle and few other components. I can't easily mock these large contracts and since most of the setup happens in the constructor, the contract fails to deploy when using `echidna-test` (By the way `echidna-test` doesn't return an error when the deployment of the test contract fails and the exit code is 0). 

What's the standard procedure for mocking dependencies so that the full contract functionality can be tested?

**Comment by nostdm** [comment]
Also it's worth pointing out that due to the gas limit, there is only so much logic one can put in a constructor - especially when deploying contracts. It would be nice if there was a way to deploy a set of contracts prior to running a test so that they can run in a specific context.

**Comment by ggrieco-tob** [comment]
Hi @nostdm!

Regarding the use of large contracts, you are right about the gas limitation in the constructor. In that case, you can use our truffle/etheno support to deploy arbitrary contracts before testing:

https://github.com/crytic/echidna/wiki/Deployment-of-a-contract-using-Truffle,-Ganache-and-Etheno-to-test-with-Echidna

Also, this sounds like a bug:

>  (By the way echidna-test doesn't return an error when the deployment of the test contract fails and the exit code is 0).

We will fix it soon. Thanks for your suggestions and testing!

**Comment by moodysalem** [comment]
seems it would be better to just remove the block gas limit (or increase to a very large number) on the test evm echidna uses, for those of us who are not using truffle and do not write truffle migrations

**Comment by ggrieco-tob** [comment]
We could do that, however there is a risk: if echidna is trapped in a tight loop, the memory can grow exponentially. This is a limitation of HEVM, and the mitigation is to set proper limits for the gas.

**Comment by moodysalem** [comment]
> We could do that, however there is a risk: if echidna is trapped in a tight loop, the memory can grow exponentially. This is a limitation of HEVM, and the mitigation is to set proper limits for the gas.

That risk is acceptable for a user run test imo-can you make it configurable as is the property and test gas limit? I have just hit this limit with 1 contract too many and I am using waffle so the alternative of using truffle/etheno is not very good
