### ISSUE TITLE
Investigate high-memory consumption with coverage enabled

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#424]
[FairWin](https://etherscan.io/address/0x5Ec8515d15C758472f3E1A7B9eCa3e996E8Ba902) contract causes echidna to consume a large amount of memory when coverage is enabled. The amount of memory required seems to be around 10 times more than without coverage.

**Comment by erivas** [comment]
I've started looking at this issue. So far, hacking a bit on `usingCoverage` seems to fix the leak: https://github.com/erivas/echidna/commit/1a4bf8b553aa337c640a2b0c9388515775cbd0e7

**Comment by ggrieco-tob** [comment]
Great! Please let us know if this fix deserves a refactoring on the execution and coverage support.

**Comment by ggrieco-tob** [comment]
This was already improved in several PRs.
