### ISSUE TITLE
Constant extraction broken with long integers

### ISSUE THREAD

**Issue by elopez** [crytic/echidna#440]
If a long integer is present in the Solidity code, current Echidna will only consider a few digits off the start of the number for its constant extraction. I believe this is due to the way the integer is reported in `solc --ast-compact-json`.

```
$ cat constants.sol
pragma solidity ^0.5.0;

contract Constants {
  bool found = false;

  function find(int i) public {
    if (i == 11234567890123456789012345678901234567) {
      found = true;
    }
  }

  function echidna_found() public view returns (bool) {
    return !found;
  }
}

$ solc --version
solc, the solidity compiler commandline interface
Version: 0.5.0+commit.1d4f565a.Linux.g++

$ solc --ast-compact-json constants.sol |grep int_const
(...)	"typeString" : "int_const 1123...(30 digits omitted)...4567"
```

From my understanding of `lib/Echidna/Solidity.hs`, the number is being parsed from the `typeString`. There are nearby fields with the correct, full number that could be used instead of trying to read it from the `typeString`

**Comment by ggrieco-tob** [comment]
We are waiting for Slither to release the new version that will provide a fix for this and then we will fix this issue.
