### ISSUE TITLE
inspecting the balance of fresh addresses fails

### ISSUE THREAD

**Issue by elopez** [crytic/echidna#442]
It appears that echidna has trouble checking the balance of a fresh address. With format: "text" and the following code, I receive "echidna_freshbalance: failed with no transactions made ⁉️".

```solidity
pragma solidity ^0.5.0;

contract FreshBalance {
  address payable public constant owner = address(0xcafe);

  function echidna_freshbalance() public returns (bool) {
    uint a = owner.balance;
    return true;
  }
}
```

If I give some balance to the address beforehand (eg., with sender: ["0xcafe"] in the config, even if balanceAddr == 0), fuzzing works as expected.

**Comment by ggrieco-tob** [comment]
hevm seems to be unexpectedly reverting for some reason.

**Comment by incertia** [comment]
is hevm reverting or is it causing an exception? if accessing a balance goes into `vm ^. env . contracts . at addr` it should be `Nothing` so there will be no balance available.

**Comment by ggrieco-tob** [comment]
I'm not sure, but I think it reverts with `NoSuchContract`.

**Comment by incertia** [comment]
yeah that would follow from trying to access it

i could PR hevm so that there could be some sort of "default contract" which is some toggleable option

**Comment by ggrieco-tob** [comment]
I can't reproduce this bug in `dapp/hevm` so perhaps they have some code already somewhere..

**Comment by incertia** [comment]
have you tried directly calling it from within the VM? maybe the `hevm` binary does some special magic

use `readSolc` and `vmForEthrunCreation` and then set up a call and `exec` it

**Comment by ggrieco-tob** [comment]
It seems that hevm have a thing call "oracle". We need to use the `zero` one:

https://github.com/dapphub/dapptools/blob/e08d412de73f2d38c91ba6c758e3248eacb5a4f2/src/hevm/src/EVM/Fetch.hs#L140-L146

They interpret each evm instruction in this loop, calling the oracle (and re-running the instruction) everytime they need:

https://github.com/dapphub/dapptools/blob/e08d412de73f2d38c91ba6c758e3248eacb5a4f2/src/hevm/src/EVM/UnitTest.hs#L217-L219

**Comment by ggrieco-tob** [comment]
I got a solution for this. Code will be available soon.

**Comment by ggrieco-tob** [comment]
Closing in favor of #653
