### ISSUE TITLE
Print the result if ctrl+c is pressed

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#459]
If I kill  Echidna (with ctrl +c), I lost the current results.

I would be better to print the results in the cli output, at least for the properties that have failed during the campaign

Tested with Echidna 1.5.0

**Comment by ggrieco-tob** [comment]
Duplicated of #435. It is already fixed in master.

**Comment by arcz** [comment]
@montyly do you mean after fuzzing finishes or during?
