### ISSUE TITLE
gasuse.sol test is flaky

### ISSUE THREAD

**Issue by elopez** [crytic/echidna#464]
When running `stack test` several times, `gasuse.sol` fails randomly.

```
...
    basic/darray-mutation.sol:             OK (3.69s)
    basic/gasuse.sol:                      FAIL (27.83s)
      src/test/Common.hs:63:
      g gas estimate wrong
    coverage/boolean.sol:                  OK (5.88s)
...
```

**Comment by incertia** [comment]
we can always relax the gas estimate a bit, but there is currently no way to specifically target for gas usage and we simply report the max gas that was seen during the campaign.

**Comment by arcz** [comment]
It's been quite stable for some time already.
