### ISSUE TITLE
Echidna cannot detect assertion failures in vyper

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#467]
As [stated here](https://github.com/vyperlang/vyper/issues/478), Vyper does not support the use of `assert` as Solidity (there is an `assert` keyword, but it is the same as `require` in Solidity). I wonder if there is need a way to workaround this, if we want to do assertion checking in vyper.

**Comment by erivas** [comment]
A possible workaround might be to use `UNREACHABLE` after `assert`. For example, `assert.sol` could get ported as:
```
$ cat examples/vyper/assert.vy 
@external
def set0(val: int128) -> bool:
  assert val % 100 != 0, UNREACHABLE
  return False

@external
def set1(val: int128) -> bool:
  return False
```
In this case, it gets tested as follows:
```
$ echidna-test examples/vyper/assert.vy --config examples/solidity/basic/assert.yaml 
Analyzing contract: ....../examples/vyper/assert.vy:assert.vy
assertion in set1: passed! 🎉
assertion in set0: failed!💥  
  Call sequence:
    set0(1099100)

Seed: -1315481366970034481
```

I can try to add this example in the tests if this makes sense.

**Comment by ggrieco-tob** [comment]
Neat. If you can, please add a CI test for that in the `exaples/vyper` directory.

**Comment by ggrieco-tob** [comment]
We won't support vyper, so I'm closing this one.
