### ISSUE TITLE
Shift + PageUp/PageDown unexpectedly closes Echidna

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#474]
If the curses dashboard is used, pressing Shift + PageUp/PageDown unexpectedly closes Echidna (same as ESC).

**Comment by erivas** [comment]
The `defaultConfig` for vty doesn't have an input map sequence for "\ESC[5;2~" (Shift + PageUp) and "\ESC[5;2~" (Shift + PageDown), so the first thing parsed is "\ESC", and it leads echidna to halt. I'll submit a patch adding those combinations.

**Comment by ggrieco-tob** [comment]
Fixed. Thanks @erivas !
