### ISSUE TITLE
Tuto complex codebase init/etheno (building secure contract)

### ISSUE THREAD

**Issue by MatthewARinehart** [crytic/echidna#475]
Tuto complex codebase init/etheno (building secure contract)

**Comment by ggrieco-tob** [comment]
For this issue, we need:

- [ ] Review and improve [this Echidna tutorial](https://github.com/crytic/echidna/wiki/Deployment-of-a-contract-using-Truffle,-Ganache-and-Etheno-to-test-with-Echidna).
- [ ] Move it to [building-secure-contracts repository](https://github.com/crytic/building-secure-contracts), including a suitable CI test for that.

**Comment by ggrieco-tob** [comment]
Done.
