### ISSUE TITLE
multicore fuzzing configurable with jobs count

### ISSUE THREAD

**Issue by MatthewARinehart** [crytic/echidna#476]
multicore fuzzing configurable with jobs count

**Comment by ggrieco-tob** [comment]
echidna-parade should be enough (tagging @agroce )

**Comment by agroce** [comment]
Yeah, true multicore internal sounds like it would be a huge pain compared to just AFL-style shared corpus.

**Comment by agroce** [comment]
So Echidna will be getting true internal multicore?

**Comment by ggrieco-tob** [comment]
Yes
