### ISSUE TITLE
Echidna crashes with contracts with immutable variables

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#505]
If you try to run Echidna with this:

```solidity
pragma solidity ^0.6.8;

contract C {

  bytes32 public immutable x = keccak256("");
  function f() public { return; }
  function echidna_test() public returns (bool) { return true; }

}
```

it fails with `echidna-test: NonEmpty.fromList: empty list`.

**Comment by erivas** [comment]
The issue arises when looking up the ABI from contract code in [`Transaction.hs`](https://github.com/crytic/echidna/blob/050e47df41218b26069ef45871f51455f736a3fa/lib/Echidna/Transaction.hs#L71), as no matching ABI is found.

The mapping from contract code to ABI is constructed in [`Solidity.hs`](https://github.com/crytic/echidna/blob/050e47df41218b26069ef45871f51455f736a3fa/lib/Echidna/Solidity.hs#L185), where the compiled contract is used as key. 
When using `immutable` in this way, the constructor code generated by the Solidity compiler patches (with `MSTORE`) the compiled code (originally containing all 0s, and replacing them with `keccak256("")`) before doing `RETURN`, making the contract code in the VM to be patched:
```
053 PUSH1 87
055 MSTORE
056 POP
057 PUSH1 ea
059 PUSH1 00
061 RETURN
```
When this code is looked up in the table for finding its ABI, we get a mismatch between the original compiled code (loaded in the table) and the patched code (in the VM).

I've written a short [fix for it](https://github.com/crytic/echidna/pull/562), that adds the patched code to the mapping (in addition to the original compiled code). It'd be nice to have another way of mapping code/contract addresses to ABIs.

**Comment by ggrieco-tob** [comment]
Very interesting. Thanks a lot @erivas. It seems that we could propose a refactoring/simplification of the ABI mapping. In particular, we would like to have a more robust/tested multi-abi code. What do you think about it @incertia ?
