### ISSUE TITLE
no basic auth credentials

### ISSUE THREAD

**Issue by enderphan94** [crytic/echidna#520]
I've run 

`docker pull docker.pkg.github.com/crytic/echidna/echidna:latest`

and it returned:

`Error response from daemon: Get https://docker.pkg.github.com/v2/crytic/echidna/echidna/manifests/latest: no basic auth credentials
`

Any ideas?

**Comment by ggrieco-tob** [comment]
You can either [authenticate your github user in docker](https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358) or use: `docker pull trailofbits/eth-security-toolbox` which contains the latest version of our tools.
