### ISSUE TITLE
dyld: Library not loaded: libff.dylib

### ISSUE THREAD

**Issue by PaulRBerg** [crytic/echidna#522]
I ran these steps:

1. Download the v1.5.1 release from the [Releases][1] page
2. Unzip the tar.gz archive
3. Open the terminal and run `./echidna-test --version`

And got this error:

> dyld: Library not loaded: libff.dylib
> Referenced from: /Users/paulrberg/Binaries/./echidna-test
> Reason: image not found
> Abort trap: 6

Using macOS@10.15.7.

[1]: https://github.com/crytic/echidna/releases/tag/v1.5.1

**Comment by ggrieco-tob** [comment]
Hi!, thanks for testing our binary for OSX. You should have two additional libraries installed:

* libff (https://github.com/crytic/echidna/blob/master/.github/scripts/install-libff.sh) 
* libsecp256k1 (https://github.com/crytic/echidna/blob/master/.github/scripts/install-libsecp256k1.sh)

Can you run these scripts to check if it solves this. Otherwise, you can use our docker container to run Echidna in OSX.

**Comment by PaulRBerg** [comment]
Thanks @ggrieco-tob, I ended up using Docker, it was much easier.

**Comment by PaulRBerg** [comment]
For what it's worth, I just ran both of those scripts:

```sh
HOST_OS=macOS ./.github/scripts/install-libff.sh
HOST_OS=macOS ./.github/scripts/install-libsecp256k1.sh
```

And I reloaded my terminal, but I'm still getting the same error as in my original post.

**Comment by ggrieco-tob** [comment]
Uhm, interesting. We will investigate this issue. Let's keep this issue open. Thanks for the report. :slightly_smiling_face:

**Comment by PaulRBerg** [comment]
Happy to help. Sorry to bug you - but do you happen to know what's going on in this other issue?

https://github.com/crytic/crytic-compile/issues/115

**Comment by ggrieco-tob** [comment]
Sure, let me check that.

**Comment by fabiohild** [comment]
Ran into the same problem today. Installing libff with the bash script or from other sources does not seem to work. I'm on MacOS Mohave. Let me know if I can provide any useful info, will use the Docker container for now. Thanks!

**Comment by elopez** [comment]
@fabiohild @PaulRBerg could you try out the binaries from the draft PR above and see if they work any better? You should not need to build/install libff nor libsecp256k1, as they are bundled in the zip file.

https://github.com/crytic/echidna/actions/runs/323365632

**Comment by fabiohild** [comment]
Hey @elopez ,

It didn't work out of the box, but installing libgmp (through homebrew) was enough to get it working, it might be worth including it along with the binary too.

Thanks a lot!

**Comment by ggrieco-tob** [comment]
@elopez can you modify your PR to include libgmp or detail how to install that library in the README?

**Comment by elopez** [comment]
I've updated the PR and added a copy of libgmp as well, here's a fresh run if you want to try them out again.

https://github.com/crytic/echidna/actions/runs/350638716

**Comment by ggrieco-tob** [comment]
This should be fixed already. We don't have any release, but you can already try the MacOS nightly binaries.
