### ISSUE TITLE
Inconsistency in the config defaults docs

### ISSUE THREAD

**Issue by paulrberg** [crytic/echidna#528]
In the default configuration file mentioned in the README, the deployer account is said to be 0x00a329C0648769a73afAC7F9381e08fb43DBEA70:

https://github.com/crytic/echidna/blob/86b2b574fdfd2c0d9f909d6544d00f307638e054/examples/solidity/basic/default.yaml

But in the [crash course][1], the deployer account is said to be 0x00a329c0648769A73afAc7F9381E08FB43dBEA72, while 0x00a329C0648769a73afAC7F9381e08fb43DBEA70 is just a caller:

> There are some specific addresses in Echidna:
>
> + 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 which calls the constructor.
> + 0x10000, 0x20000, and 0x00a329C0648769a73afAC7F9381e08fb43DBEA70 which randomly calls the other functions.

Which one is correct?

[1]: https://github.com/crytic/building-secure-contracts/blob/a16e43fc5ab189a973fcd3461fdba3398010c2fc/program-analysis/echidna/how-to-test-a-property.md#initiate-a-contract

**Comment by ggrieco-tob** [comment]
This was recently fixed.
