### ISSUE TITLE
Feature request: allow testing of very large contracts

### ISSUE THREAD

**Issue by moodysalem** [crytic/echidna#531]
Per https://github.com/crytic/echidna/issues/401

If you have a test case that depends on a whole bunch of other contracts, you will run into the block gas limit trying to test it with echidna

The recommendation is to use etheno + truffle to create an initialization file https://github.com/crytic/echidna/wiki/Deployment-of-a-contract-using-Truffle,-Ganache-and-Etheno-to-test-with-Echidna

However if you do not use truffle, this is a hassle to set up. Prefer to just be able to configure the block gas limit used in the EVM, so can deploy arbitrarily large contracts.

**Comment by ggrieco-tob** [comment]
Please test #532 that will use a very very large gas limit (over the gas block limit) for deployment.

**Comment by moodysalem** [comment]
the artifact that is built from that pr works for me

**Comment by ggrieco-tob** [comment]
Fixed.
