### ISSUE TITLE
hardhat support

### ISSUE THREAD

**Issue by moodysalem** [crytic/echidna#557]
the latest crytic compile version supports hardhat

however installing crytic locally via pip3 does not enable echidna to work with hardhat

**Comment by moodysalem** [comment]
The error is here:
```
$ echidna-test . --contract MathEchidnaTest --config echidna.config.yml
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:. does not exist (are you in the correct directory?)
```

**Comment by ggrieco-tob** [comment]
crytic-compile already works with hardhat, so I'm closing this issue.
