### ISSUE TITLE
Allow text/interactive UI to dump failing transaction sequences to file

### ISSUE THREAD

**Issue by agroce** [crytic/echidna#586]
Unless I'm missing something, if you use the text or dashboard interfaces, you can't save a failing transaction as JSON.  This would be nice for various uses in toolchains -- text is easy to mine in scripts, but saving the tx sequence in the JSON format we have allows other uses for the transactions.  As I understand, failing txs can't be saved in coverage corpuses, either, so they really are just lost in any "format" choice but json, as machine-readable.

**Comment by ggrieco-tob** [comment]
Is this blocking echidna-parade integration?

**Comment by arcz** [comment]
With https://github.com/crytic/echidna/issues/1045, sequences (in JSON format) will be stored right away when a property is falsified instead of waiting until the end. Let's move to #1045 in case any further discussion is needed.
