### ISSUE TITLE
Document Echidna current limitations

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#587]
For example, Echidna does not work with immutable (https://github.com/crytic/echidna/issues/505), but we cannot expect the users to go through our list of issues to know that.

We should list the features that are not supported in the readme or wiki

**Comment by ggrieco-tob** [comment]
This feature will be supported "soon" when the code for that fix is merged.

**Comment by montyly** [comment]
I think there are a couple of other limitations; the one I can at least think of is for codebase with libraries that need to be manually deployed (https://github.com/crytic/echidna/issues/514).

Having a clear list of limitations that we can update over time will help the usability imho

**Comment by montyly** [comment]
https://github.com/crytic/echidna/issues/601 is another example of limitation that should be easily visible to the users

**Comment by montyly** [comment]
EOAs don't work, unless they are specified in `sender`: https://github.com/crytic/echidna/issues/648

**Comment by hacker-DOM** [comment]
External libraries don't work #649

**Comment by ggrieco-tob** [comment]
A draft to document all these is here: https://github.com/crytic/echidna/pull/655

**Comment by ggrieco-tob** [comment]
This should be up to date here: https://github.com/crytic/echidna#limitations-and-known-issues
