### ISSUE TITLE
Write guidelines on how to debug Echidna

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#588]
If Echidna fails, it is currently really difficult to understand why. We should write a guideline on how to debug Echidna.

For example, adding this undocumented flag in the config file:
```
format: text
```

Helps to identify the issue. I am sure they are other techniques to do.

**Comment by ggrieco-tob** [comment]
This is really an issue in the UI. It should be solved to show the error message instead of hanging.

**Comment by 0xalpharush** [comment]
Ran into issues with this and it wastes a lot of time because the UI will appear as the fuzz test cases aren't progressing but really an error has occurred.

**Comment by ggrieco-tob** [comment]
We had some documentation here: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/frequently_asked_questions.md but needs to be expanded.

**Comment by ggrieco-tob** [comment]
Already documented, hopefully is covers what we need.
