### ISSUE TITLE
Improve etheno error message 

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#598]
`echidna-test: Error parsing Etheno initialization file: Error in $: ',' or ']': not enough input`

I think most likely this means that you did not kill Etheno.  We could improve the error message here

**Comment by ggrieco-tob** [comment]
Uhm, I need to check that, since it looks like an error produced by the code inside the json parser.

**Comment by 0xKarl98** [comment]
it's not , i killed the etheno , 
but the error still exists

**Comment by arcz** [comment]
@0xKarl98 do you have steps to reproduce the issue?

**Comment by ggrieco-tob** [comment]
We will deprecate etheno, so I'm closing this one.
