### ISSUE TITLE
Assertions are not detected in internal transactions

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#601]
For example:
```solidity
contract Test{
    
    function fail() public{
        require(msg.sender == address(this));
        assert(false);
    }

    function should_fail() public{
        this.fail();
    }

}
```
```
checkAsserts: true
multi-abi: true
```
Echidna will not detect the assertion failure in the internal transaction.

This limitation is particularly important as it can give confidence in the codebase, while the assertions fail

**Comment by ggrieco-tob** [comment]
You should use events for that, for instance: https://github.com/crytic/echidna/blob/master/examples/solidity/basic/assert.sol#L3. But I agree, this you should be documented in an example.

**Comment by ggrieco-tob** [comment]
PD: we already have an official example here: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/assertion-checking.md#write-an-assertion

**Comment by montyly** [comment]
Should we recommend to always use events instead of assert? They seem to have the same effects, without the internal transactions limitation (which is a significant one imho)

**Comment by hacker-DOM** [comment]
Wondering why the above code fails.

**Comment by ggrieco-tob** [comment]
My understanding is that every time HEVM makes a (nested) external call, it creates a new "frame". The assert detection works only on the first one, not in any of the following ones. If you want to detect something in the nested external calls, you will need to use events. However, there is one limitation, you will still need to call from a certain contract that you are testing (and it doesn't support multi-contract). That's fixable, of course, but we will need to do a refactoring of a test, something I started to do but I did not have the time to finish.. :cry:

**Comment by hacker-DOM** [comment]
> ```
> checkAsserts: true
> multi-abi: true
> ```

btw, you don't need multi-abi (since it is one contract)

**Comment by ggrieco-tob** [comment]
It seems that assertion failure from internal transactions can be detected if we use solc 0.8.x:

```
$ solc-select use 0.8.1
Switched global version to 0.8.1
$ echidna-test internal.sol --test-mode assertion
Analyzing contract: Test
should_fail(): failed!💥  
  Call sequence:
    should_fail()

Event sequence: Panic(1), merror Revert 0x4e487b710000000000000000000000000000000000000000000000000000000000000001 from: Test
fail():  fuzzing (10847/50000)
AssertionFailed(..):  fuzzing (10847/50000)

Unique instructions: 118
Unique codehashes: 1
Corpus size: 2
Seed: 6322413326626652355
```

It seems that Solidity will forward the revert reason from the internal call up to the EOA that produced the call. However, using older version will NOT catch this. I will clarify this in our documentation.
