### ISSUE TITLE
Change Ubuntu release to be tar.gz which simply expands to echidna-test

### ISSUE THREAD

**Issue by snd** [crytic/echidna#607]
The 1.6.0 ubuntu release was a tar.gz file that simply expanded to `echidna-test`.
The 1.6.1 ubuntu release is a zip file that expands into `echidna-test.tar.gz` which in turn expands into `home/runner/.local/bin/echidna-test`.

Produce tar.gz again and avoid the long path.

**Comment by ggrieco-tob** [comment]
I believe this was fixed by @elopez in the latest github action refactoring.

**Comment by snd** [comment]
for release 1.7.0 the zip file still expands into a tar.gz but the tar.gz expands into the binary directly

**Comment by ggrieco-tob** [comment]
The tar.gz inside a .zip cannot be avoided. GitHub always uses a zip for artifacts, and a tar.gz is required to preserve permissions in *nix, so that's as good as it gets.
