### ISSUE TITLE
uppercase True/False in function names seem to get lowercased

### ISSUE THREAD

**Issue by snd** [crytic/echidna#613]
Running the code below with
```
echidna-test Example.sol --config echidna.yaml
```
produces the following output:
```
echidna_returnsfalse_pass: failed with no transactions made ⁉️  
echidna_returnstrue: failed with no transactions made ⁉️  
echidna_returnsFoo: passed! 🎉
echidna_Bar: passed! 🎉
echidna_returnsfalse: failed with no transactions made ⁉️  
echidna_returnstrue_pass: failed with no transactions made ⁉️  
echidna_A_B_C: passed! 🎉
echidna_foo: passed! 🎉
```

This is strange for the following reasons

- output contains `echidna_returnstrue_pass` instead of `echidna_returnsTrue_pass`
  - same for `echidna_returnsFalse_pass`
- `echidna_returnsTrue_pass` fails despite returning `true`
    - same for `echidna_returnsFalse_pass`
- `returnsTrue` doesn't cause an error despite containing `assert(false)` and `checkAsserts: true`
  - same for `returnsFalse`

This leads me to believe that `true` and `false` and potentially other keywords get lowercased when they appear uppercased in function names. This leads to the bytecode reverting for the lowercased versions (unless a fallback function is present) since they are not found.

I traced this a bit with ghci and it seems to come from `crytic-compile`.
Compiling the ABI with `solc` directly contains the correct uppercased function names.

`Example.sol`
```
pragma solidity ^0.6.12;

contract Test {
    function echidna_returnsTrue_pass() public returns (bool) {
        return true;
    }

    function echidna_returnsFalse_pass() public returns (bool) {
        return true;
    }

    function echidna_returnsTrue() public returns (bool) {
        return true;
    }

    function echidna_returnsFalse() public returns (bool) {
        return true;
    }

    function echidna_returnsFoo() public returns (bool) {
        return true;
    }

    function echidna_A_B_C() public returns (bool) {
        return true;
    }

    function echidna_foo() public returns (bool) {
        return true;
    }

    function echidna_Bar() public returns (bool) {
        return true;
    }

    function CamelCase() public returns (bool) {
        return true;
    }

    function returnsTrue() public {
        assert(false);
    }

    function returnsFalse() public {
        assert(false);
    }
}
```

```
$ crytic-compile --version
0.1.12
$ echidna-test --version
Echidna 1.6.1
```

`echidna.yaml`:
```
checkAsserts: true
```

**Comment by ggrieco-tob** [comment]
This looks like an issue in crytic-compile. Can you open an issue there?

**Comment by snd** [comment]
Done
