### ISSUE TITLE
Events for final call sequence

### ISSUE THREAD

**Issue by dwhjames** [crytic/echidna#62]
It would be great if, after the shrinking phase has completed, the events emitted to the log are output along with the minimized call sequence.

One can obviously replay the execution given the call sequence, but having the logs would likely assist in arriving at an understanding of the failure more quickly.

**Comment by montyly** [comment]
This is old, but I think it would be nice to consider it again

**Comment by ggrieco-tob** [comment]
This feature could be merged soon, @incertia is working on it for this in the `dev-new-failures` branch.

**Comment by ggrieco-tob** [comment]
Closing in favor of #656
