### ISSUE TITLE
Parse error on input while compiling with stack

### ISSUE THREAD

**Issue by cymerrad** [crytic/echidna#626]
I'm trying to compile version 1.7.0 on MacOS. I have the most recent version of stack:
`Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0`

Last blocking error I got which I don't understand at all was:

```
~/C/g/c/echidna (34cf64d ✗)$ stack install                                                                                                                                                                                    [21-03-03T17:20:15][R-0][!8435]
Building all executables for `echidna' once. After a successful build of all of them, only specified executables will be rebuilt.
echidna> configure (lib + exe)
Configuring echidna-1.7.0...
Warning: 'ghc-options: -threaded' has no effect for libraries. It should only
be used for executables.
echidna> build (lib + exe)
Preprocessing library for echidna-1.7.0..
Building library for echidna-1.7.0..
[ 1 of 31] Compiling Echidna.Events
[ 2 of 31] Compiling Echidna.Orphans.JSON

<no location info>: warning: [-Wmissed-extra-shared-lib]
    dlopen(libff.dylib, 5): image not found
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).
[ 3 of 31] Compiling Echidna.Types
[ 4 of 31] Compiling Echidna.Types.Buffer
[ 5 of 31] Compiling Echidna.Types.Random
[ 6 of 31] Compiling Echidna.Mutator.Array
[ 7 of 31] Compiling Echidna.Output.Utils
[ 8 of 31] Compiling Echidna.Types.Signature
[ 9 of 31] Compiling Echidna.ABI
[10 of 31] Compiling Echidna.Processor
[11 of 31] Compiling Echidna.Types.Tx

/Users/rado/Code/github/crytic/echidna/lib/Echidna/Types/Tx.hs:56:14: error: parse error on input ‘}’
   |
56 |              } deriving (Eq, Ord, Show)
   |              ^


--  While building package echidna-1.7.0 (scroll up to its section to see the error) using:
      /Users/rado/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 build lib:echidna exe:echidna-test --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I haven't touched the code, HLS in VSCode also shows the same parsing error, but only for this file.
Commenting-out the `data Tx = { ... }` moves the parsing error down to the comment on line 60 for some reason?

Anyone got any idea what's wrong with my setup?

**Comment by ggrieco-tob** [comment]
That's a very weird. Our MacOS CI tests are still working. Can you check how [these are different from your system](https://github.com/crytic/echidna/blob/master/.github/workflows/ci.yml)?

**Comment by cymerrad** [comment]
Comparing my installed software to:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

I have checked some programs' versions and am now on par with Github Action's software.
Frankly, I don't really know what to look for, but I've picked those:
```
Stack 2.5.1
Cabal 3.4.0.0
GHC 9.0.1
```

**Comment by ggrieco-tob** [comment]
Isn't ghc installed as part of stack? Can you check the output of `stack ghc -- --version` ?

**Comment by cymerrad** [comment]
```
~/C/g/c/echidna (34cf64d ✗)$ stack ghc -- --version                                                                                                                                                                             [21-03-03T18:49:02][1][!8450]
The Glorious Glasgow Haskell Compilation System, version 8.8.3
```

**Comment by ggrieco-tob** [comment]
Can you try removing ghc 9? Perhaps VSCode is forcing stack to use a system installed ghc. Otherwise, feel free to submit a PR to allow Echidna to compile in GHC 9. :smile:

**Comment by cymerrad** [comment]
Reinstalling stack sufficed.

I was really hoping to understand something about the tooling or whatever, but no -- computers are just brittle and broken.
Thank you for your attention ❤️
