### ISSUE TITLE
Self describing test failures

### ISSUE THREAD

**Issue by dwhjames** [crytic/echidna#63]
Consider the following snippet:

```solidity
  …
  function echidna_test() public returns (bool) {
      return (state == 1);
  }
```

When the test fails, we get the failing call sequence and the knowledge that `state != 1`. We need to replay the calls to determine what `state` actually is.

However, if Echidna recognized a special function, say `echidna_failure_log`, and was able to print out the event log (_cf._ Issue https://github.com/trailofbits/echidna/issues/62) then test failure may become easier to understand. For example:

```solidity
  …
  function echidna_test() public returns (bool) {
      return (state == 1);
  }

  event State(uint256 _state);
  function echidna_failure_log() public {
      emit State(state);
  }
```

Echidna would make a final call to `echidna_failure_log` after each minimized failing call sequence for each failing test.

**Comment by ggrieco-tob** [comment]
Hi @dwhjames. Sorry for the long delay to address this issue!  We implemented the printing of the EVM event log when a property fails, so you should be able to see any event that you added. Can you please test PR #131 ?

**Comment by ggrieco-tob** [comment]
Closing in favor of #656
