### ISSUE TITLE
Echidna 1.7.0 is significantly slower than 1.6.1

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#630]
On a private codebase (with the same seed, `--format text`, and `testLimit: 1000`):
- `1.6.1`: 9 seconds
- `1.7.0`: 2 minutes 40 seconds

If I disable the coverage on 1.7.0, I have the same results.

Do we have data to back the choice of the coverage guided by default? My intuition tells me that the coverage will help on contracts with multiple functions and complex interactions, but not might be adapted to fuzz individual components/small codebase.

If this is true, we could maybe rely on slither to estimate what is the best strategy to follow.

Any thoughts?

**Comment by ggrieco-tob** [comment]
Uhm, if you have the same configuration the speed is the same. However, you are right that 1.7.0 is slower by default but we need more information here. Perhaps echidna is reverting 99% of the time in 1.6.1 and getting some interesting coverage in 1.7.0. Perhaps some recent mutation that we introduced is slower than expected. You tried enabling coverage in 1.6.1?

In general if you test a dedicated component that has no state, disabling coverage will be a good idea. IMHO that is not best way to use echidna features, but it should work fine. Using slither to suggest enabling or disabling the state seems like a good idea. Just print a suggestion in the `echidna` printer and we can follow it (allowing the use to override it, of course). There is one catch, it's important know which contract will be tested and right now, only echidna has that information.

**Comment by agroce** [comment]
Yeah, we did benchmarking near release where cover/nocover was only a modest speed change, right?

**Comment by ggrieco-tob** [comment]
Perhaps this should be revisited after #707 is merged.

**Comment by ggrieco-tob** [comment]
Echidna 1.7.4 and 2.0.0 are faster than before so I will be closing this issue.
