### ISSUE TITLE
Need to run `hardhat clean` every time when a test contract is changed.

### ISSUE THREAD

**Issue by krasi-georgiev** [crytic/echidna#631]
It seems the echidna doesn't detect when a test contract has changed so need to clear the cache to enforce recompilation.

Here is an example repo with hardhat
https://github.com/krasi-georgiev/chorus/tree/echidna

**Comment by ggrieco-tob** [comment]
This is an [known crytic-compile/slither issue](https://github.com/crytic/crytic-compile/issues/164). There is little we can do from echidna, but we will keep this issue open to track it down upstream.

**Comment by ggrieco-tob** [comment]
This should be fixed in `master`. Please test and reopen if necessary.
