### ISSUE TITLE
UI: improve output for function with a lot of parameters

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#634]
Running Echidna on

```solidity
contract C{
    bool flag = true;

    function test(uint[100] memory v) public{
        flag = false;
    }

    function echidna_test() public returns(bool){
        return flag;
    }
}
```

Leads to

![image](https://user-images.githubusercontent.com/13798342/113517947-538dfa00-9583-11eb-9233-265a07824b72.png)

The parameters are not all shown. 

We should add a carriage return, or change the UI in a way that all the parameters are displayed.

**Comment by ggrieco-tob** [comment]
This is indeed an issue (however, you should still see the complete information when you exit echidna in your console).

**Comment by montyly** [comment]
Yes, you can see the information once it's complete. This is more an issue during a long run if you want to check the results without killing Echidna
