### ISSUE TITLE
Echidna fails to get certain constants

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#636]
Echidna fails to find the input to break this property:

```solidity
contract C {
    uint x;

    function f(uint i) public {
       x = i;
    }

    function echidna_test() public view returns (bool) {
        return x != uint(-2);
    }
}
```

This [is an slither issue](https://github.com/crytic/slither/issues/465#issuecomment-814819642), originally found by @hacker-dom

**Comment by montyly** [comment]
The slither printer gives:
```
    "constants_used_in_binary": {
        "C": {
            "echidna_test()": {
                "-": [
                    [
                        {
                            "value": "2",
                            "type": "uint256"
                        }
                    ],
                    [
                        {
                            "value": "0",
                            "type": "uint256"
                        }
                    ]
                ]
            }
        }
    },
```

So once Echidna integrates `constants_used_in_binary`, and mixes the different combinations, it should work.

It's similar to something like
```solidity
contract C {
    uint x;

    function f(uint i) public {
       x = i;
    }

    function echidna_test() public view returns (bool) {
        return x != 2 * 2 ether;
    }
}
```

Where slither gives this info
```
        "C": {
            "echidna_test()": {
                "*": [
                    [
                        {
                            "value": "2000000000000000000",
                            "type": "uint256"
                        }
                    ],
                    [
                        {
                            "value": "2",
                            "type": "uint256"
                        }
                    ]
                ]
            }
        }
```
But is not currently used by Echidna

**Comment by ggrieco-tob** [comment]
The negative example is solved, but echidna is still not using `2 * 2 ether` as a constant, so it won't break the second example.

**Comment by ggrieco-tob** [comment]
I think the best way to deal with this is just to precompute the value of binary/unary operations when the operads are constant. This should be done from the slither side, and add the result into `constants_used`. Echidna should be able to pick them without any modification.

**Comment by ggrieco-tob** [comment]
@agroce said in a previous issue:

> Invert simple arithmetic operations, without using symbolic execution or anything costly/fancy. E.g., mine "4" (and nearby constants 3 and 5) from "if (x * 2) == 8".

**Comment by arcz** [comment]
Echidna can now break all the examples mentioned here.
