### ISSUE TITLE
Problem with external libraries

### ISSUE THREAD

**Issue by hacker-DOM** [crytic/echidna#649]
I have [a very simple example](https://github.com/hacker-DOM/hardhat-echidna-starting-up-please-wait-minimal-example) with one external library. Running `echidna-test . --contract EchidnaTest --config echidna.config.yml`, I would expect the fuzzing to begin. Instead, the UI starts but the program hands on "Startin up, please wait...".

**Comment by ggrieco-tob** [comment]
Using `format: text` reveals the error, right?

**Comment by ggrieco-tob** [comment]
Closing in favor of #651
