### ISSUE TITLE
Dump EVM state on test failures

### ISSUE THREAD

**Issue by dwhjames** [crytic/echidna#65]
Related to issue https://github.com/trailofbits/echidna/issues/63

One of the files that Manticore outputs for each test case that it generates is a `.summary` file that lists: addresses, balances, code and storage for contracts, and hashes for known input.

It would be great if Echidna could dump its EVM state on test failures, showing similar output to Manticore.

**Comment by ggrieco-tob** [comment]
Closing in favor of #656
