### ISSUE TITLE
Unresolved target while running through docker

### ISSUE THREAD

**Issue by sunbeam891** [crytic/echidna#658]
![errors](https://user-images.githubusercontent.com/20522941/116970347-21df8e80-acfb-11eb-88d2-fde4dbbf7b1c.PNG)
Getting this error after following docker container steps in the readme file. Any help to make this run would be really appreciated.

**Comment by Robsonsjre** [comment]
I had the same issue...Just tried with the latest version 1.7.2
Using MacOS Catalina

**Comment by elopez** [comment]
Thanks for the report! Judging by the screenshot, it looks like you are binding the wrong folder from your host system to inside the container, so the solidity files are not found when echidna runs. Your terminal shows you being in `~` (your home folder), so the command you are running maps that home folder to `/src` inside the docker container. You should instead map the echidna git repo folder to `/src`. You can achieve that by first moving to the repo folder (`cd ~/path/to/echidna`) before running the docker command.
