### ISSUE TITLE
Fail to pull with docker

### ISSUE THREAD

**Issue by little-petrol** [crytic/echidna#671]
Windows 10
> docker pull docker.pkg.github.com/crytic/echidna/echidna:latest

error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/images/create?fromImage=docker.pkg.github.com%2Fcrytic%2Fechidna%2Fechidna&tag=latest": open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by elopez** [comment]
Hi! Thanks for the report. I'm closing this issue as this looks unrelated to echidna, it sounds like Docker Desktop was not running when you attempted to pull the image.
