### ISSUE TITLE
Add native M1 support

### ISSUE THREAD

**Issue by incertia** [crytic/echidna#692]
Users are able to use Rosetta binary translation to build on Apple M1 but providing some level of native M1 support may be good once the relevant distributions offer M1 packages.

**This issue has a $5,000 USD bounty thanks to an anonymous contributor**. Exit criteria to satisfy the bounty requires a maintainable, non-hacky, solution. Any changes required to fix dependencies should be PR'd upstream, e.g., to HEVM.

None of the Echidna development team has access to an M1 Mac right now (@incertia, @ggrieco-tob, or @arcz). As a result, we're not certain of the exact level of effort required to close this issue. Some dependencies have only ever been tested on x86-64 and compiling them may not be trivial. Specifically, xbyak is an x86 JIT required by ate-pairing, and finding a solution may require creativity.

Here is a non-exhaustive list of what we know will require changes:

* [ ] Building [HEVM](https://github.com/dapphub/dapptools/tree/master/src/hevm). This is by far the largest dependency echidna has and it depends on some external libraries.
* [ ] Investigate building [ate-pairing](https://github.com/herumi/ate-pairing) and [xbyak](https://github.com/herumi/xbyak) for M1 as they are dependencies of [libff](https://github.com/scipr-lab/libff), a dependency of HEVM (this is the issue the anonymous contributor is blocked on)
* [x] ~~Investigate building [boolector](https://github.com/Boolector/boolector), a dependency of [sbv](https://github.com/LeventErkok/sbv), which is in turn a dependency of HEVM~~ (not required according to [this](https://github.com/crytic/echidna/issues/692#issuecomment-979444449))
* [ ] M1 stack binaries (probably optional, because Rosetta stack can install M1 GHCs)

**Comment by incertia** [comment]
There are a few things that are required to get echidna to build properly. @arcz, @ggrieco-tob, and I are currently not in possession of any M1 hardware so it is not so simple for us to get this to build properly. I will update this comment with more checklist items as they are discovered.

* [ ] Building [HEVM](https://github.com/dapphub/dapptools/tree/master/src/hevm). This is by far the largest dependency echidna has and it depends on some external libraries.
* [ ] Investigate building [ate-pairing](https://github.com/herumi/ate-pairing) and [xbyak](https://github.com/herumi/xbyak) for M1 as they are dependencies of [libff](https://github.com/scipr-lab/libff), a dependency of HEVM (this is the issue the anonymous contributor is blocked on)
* [ ] Investigate building [boolector](https://github.com/Boolector/boolector), a dependency of [sbv](https://github.com/LeventErkok/sbv), which is in turn a dependency of HEVM
* [ ] M1 stack binaries (probably optional, because Rosetta stack can install M1 GHCs)

**Comment by ggrieco-tob** [comment]
Btw, we don't really need anything from sbv, so building boolector could be avoided if hevm allowed us to disable it when compiling (tagging @mrchico in case he has any ideas)

**Comment by MrChico** [comment]
hevm is not using boolector, just cvc4 and z3, I don't think you'll ever need boolector

**Comment by MrChico** [comment]
btw: https://gist.github.com/adietrichs/2ad35e57290a9b16359ea5f8f2f310bd#file-hevm-md

**Comment by ggrieco-tob** [comment]
We already have natives M1 binaries (and @elopez is keeping them up to date)
