### ISSUE TITLE
Handling constructor arguments

### ISSUE THREAD

**Issue by 0xfoobar** [crytic/echidna#693]
What's the best practice for these contracts?

Read through [this link](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/how-to-test-a-property.md), which says you can't.

But most smart contracts require some sort of initialization, and I'd like to run fuzzing on as close to the real thing as possible without maintaining a completely separate library. Any tips?

**Comment by 0xalpharush** [comment]
Great question! 
You can seed Echidna's with an initialization file by specifying it in the configuration file.

To generate the initialization file, begin by writing a deployment script and capturing the info with etheno.

Using hardhat (this should work for other platforms, too)
```
npx hardhat compile
etheno --ganache --ganache-args "--gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000" -x ./setup.json
```
In another terminal
```
npx hardhat run --network localhost scripts/deploy.js
```
Then, kill Etheno when the testing finishes (via Ctrl+C)

```
echo initialize: setup.json >> test.yaml
```
Finally, run 
```
echidna-test . --contract Test--config test.yaml
```

**Comment by incertia** [comment]
with respect to constructor arguments, when most people deploy contracts with constructor arguments, they provide known data to the constructor

echidna has no way to know what it should pass to the constructor in order to correctly initialize it the way it would be on chain. this is why we use etheno to record a mock deployment and replay the transactions onto our own test chain. an alternative method would be to use a proxy contract which has a constructor with no arguments that correctly deploys the desired contracts which then proxies the various calls you would like to fuzz to the correct contract.

**Comment by CodeGodz** [comment]
For me deploying on ganache works fine with the constructor arguments yet echidna will throw `"Deploying the contract 0x.... failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)"`

Lets use this contract as example, **Test.sol**
```
pragma solidity >=0.8.0;
contract Wow{
    int8 private wow;
    constructor(int8 test) {
        wow = test; 
    }
    function echidna_test() public returns(bool) {
        return wow == 2;
    }
}
```
Then put this in `contracts/Test.sol` and add a basic hardhat config, `hardhat.config.js`
```
require("@nomiclabs/hardhat-waffle");
/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.8.8",
};
```
Then we run `npx hardhat compile` and create the `deploy.js`:
```
async function main() {

  const Token = await ethers.getContractFactory("Wow");
  const token = await Token.deploy(2);
  await token.deployed();

}
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```
Then running ganache as above and `npx hardhat run scripts/deploy.js --network localhost` will give the following setup.json:

```
[
{"event": "AccountCreated", "address": "5409ed021d9299bf6814279a6a1411a7e866a631"},
{"event": "ContractCreated", "from": "0x5409ed021d9299bf6814279a6a1411a7e866a631", "contract_address": "0x1dc4c1cefef38a777b15aa20260a54e584b16c48", "gas_used": "0x1d81b", "gas_price": "0x4a817c800", "data": "0x608060405234801561001057600080fd5b5060405161019838038061019883398181016040528101906100329190610093565b806000806101000a81548160ff021916908360000b60ff160217905550506100c0565b600080fd5b60008160000b9050919050565b6100708161005a565b811461007b57600080fd5b50565b60008151905061008d81610067565b92915050565b6000602082840312156100a9576100a8610055565b5b60006100b78482850161007e565b91505092915050565b60ca806100ce6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806317bf8bac14602d575b600080fd5b60336047565b604051603e9190607b565b60405180910390f35b6000600260008054906101000a900460000b60000b14905090565b60008115159050919050565b6075816062565b82525050565b6000602082019050608e6000830184606e565b9291505056fea26469706673582212202816e6f3f82cf58a0b8c616767ae7d590e3b69d7227e3f584f03eb0116c95a0864736f6c634300080800330000000000000000000000000000000000000000000000000000000000000002", "value": "0x0"}
]
```
Then `echo initialize: setup.json >> test.yaml` and `../echidna-test . --contract Wow --config test.yaml` will throw the error:

> Analyzing contract: /home/rick/echidna/test/contracts/Test.sol:Wow
> echidna-test: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)

Am I missing something here to make it work?

**Comment by ggrieco-tob** [comment]
It seems that ganache worked fine to deploy `WoW`, but then you are asking Echidna to re-deply it. That will fail, but it is easy to solve. Just create a new contract for testing:

```
contract TestWow{
    address private addr = ..;
    function echidna_test() public returns(bool) {
        return Wow(addr).test();
    }
}
```

and then use: `echidna-test . --contract TestWow --config test.yaml`. You will need to use the correct address that ganache deploy (`0x1dc4c1cefef38a777b15aa20260a54e584b16c48` in this case, but this can change if you modify it).

**Comment by ggrieco-tob** [comment]
It seems this is already solved, so I'm closing it.

**Comment by asmitadhungana** [comment]
> It seems that ganache worked fine to deploy `WoW`, but then you are asking Echidna to re-deply it. That will fail, but it is easy to solve. Just create a new contract for testing:
> 
> ```
> contract TestWow{
>     address private addr = ..;
>     function echidna_test() public returns(bool) {
>         return Wow(addr).test();
>     }
> }
> ```
> 
> and then use: `echidna-test . --contract TestWow --config test.yaml`. You will need to use the correct address that ganache deploy (`0x1dc4c1cefef38a777b15aa20260a54e584b16c48` in this case, but this can change if you modify it).

While I try to do the same in my repo, the deployment scripts don't throw any error, but the contracts' deployments are not recorded. My `setup.json` file looks like this:
`[
{"event": "AccountCreated", "address": "5409ed021d9299bf6814279a6a1411a7e866a631"},
{"event": "AccountCreated", "address": "6ecbe1db9ef729cbe972c83fb886247691fb6beb"},
{"event": "AccountCreated", "address": "e36ea790bc9d7ab70c55260c66d52b1eca985f84"},
{"event": "AccountCreated", "address": "e834ec434daba538cd1b9fe1582052b880bd7e63"},
{"event": "AccountCreated", "address": "78dc5d2d739606d31509c31d654056a45185ecb6"},
{"event": "AccountCreated", "address": "a8dda8d7f5310e4a9e24f8eba77e091ac264f872"},
{"event": "AccountCreated", "address": "06cef8e666768cc40cc78cf93d9611019ddcb628"},
{"event": "AccountCreated", "address": "4404ac8bd8f9618d27ad2f1485aa1b2cfd82482d"},
{"event": "AccountCreated", "address": "7457d5e02197480db681d3fdf256c7aca21bdc12"},
{"event": "AccountCreated", "address": "91c987bf62d25945db517bdaa840a6c661374402"}
]`

And the error that follows while running `echidna-test` is the same as @CodeGodz 's error.

**Comment by zakrad** [comment]
I have the same error as yours, no error in deployment and no event in json file. then the redeploy gives the same error

> > It seems that ganache worked fine to deploy `WoW`, but then you are asking Echidna to re-deply it. That will fail, but it is easy to solve. Just create a new contract for testing:
> > ```
> > contract TestWow{
> >     address private addr = ..;
> >     function echidna_test() public returns(bool) {
> >         return Wow(addr).test();
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then use: `echidna-test . --contract TestWow --config test.yaml`. You will need to use the correct address that ganache deploy (`0x1dc4c1cefef38a777b15aa20260a54e584b16c48` in this case, but this can change if you modify it).
> 
> While I try to do the same in my repo, the deployment scripts don't throw any error, but the contracts' deployments are not recorded. My `setup.json` file looks like this: `[ {"event": "AccountCreated", "address": "5409ed021d9299bf6814279a6a1411a7e866a631"}, {"event": "AccountCreated", "address": "6ecbe1db9ef729cbe972c83fb886247691fb6beb"}, {"event": "AccountCreated", "address": "e36ea790bc9d7ab70c55260c66d52b1eca985f84"}, {"event": "AccountCreated", "address": "e834ec434daba538cd1b9fe1582052b880bd7e63"}, {"event": "AccountCreated", "address": "78dc5d2d739606d31509c31d654056a45185ecb6"}, {"event": "AccountCreated", "address": "a8dda8d7f5310e4a9e24f8eba77e091ac264f872"}, {"event": "AccountCreated", "address": "06cef8e666768cc40cc78cf93d9611019ddcb628"}, {"event": "AccountCreated", "address": "4404ac8bd8f9618d27ad2f1485aa1b2cfd82482d"}, {"event": "AccountCreated", "address": "7457d5e02197480db681d3fdf256c7aca21bdc12"}, {"event": "AccountCreated", "address": "91c987bf62d25945db517bdaa840a6c661374402"} ]`
> 
> And the error that follows while running `echidna-test` is the same as @CodeGodz 's error.

**Comment by Danila-cloud** [comment]
> > It seems that ganache worked fine to deploy `WoW`, but then you are asking Echidna to re-deply it. That will fail, but it is easy to solve. Just create a new contract for testing:
> > ```
> > contract TestWow{
> >     address private addr = ..;
> >     function echidna_test() public returns(bool) {
> >         return Wow(addr).test();
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then use: `echidna-test . --contract TestWow --config test.yaml`. You will need to use the correct address that ganache deploy (`0x1dc4c1cefef38a777b15aa20260a54e584b16c48` in this case, but this can change if you modify it).
> 
> While I try to do the same in my repo, the deployment scripts don't throw any error, but the contracts' deployments are not recorded. My `setup.json` file looks like this: `[ {"event": "AccountCreated", "address": "5409ed021d9299bf6814279a6a1411a7e866a631"}, {"event": "AccountCreated", "address": "6ecbe1db9ef729cbe972c83fb886247691fb6beb"}, {"event": "AccountCreated", "address": "e36ea790bc9d7ab70c55260c66d52b1eca985f84"}, {"event": "AccountCreated", "address": "e834ec434daba538cd1b9fe1582052b880bd7e63"}, {"event": "AccountCreated", "address": "78dc5d2d739606d31509c31d654056a45185ecb6"}, {"event": "AccountCreated", "address": "a8dda8d7f5310e4a9e24f8eba77e091ac264f872"}, {"event": "AccountCreated", "address": "06cef8e666768cc40cc78cf93d9611019ddcb628"}, {"event": "AccountCreated", "address": "4404ac8bd8f9618d27ad2f1485aa1b2cfd82482d"}, {"event": "AccountCreated", "address": "7457d5e02197480db681d3fdf256c7aca21bdc12"}, {"event": "AccountCreated", "address": "91c987bf62d25945db517bdaa840a6c661374402"} ]`
> 
> And the error that follows while running `echidna-test` is the same as @CodeGodz 's error.

Looks like you didn't run deploy script in another terminal until Etheno worked.
