### ISSUE TITLE
Echidna GitHub Action Location

### ISSUE THREAD

**Issue by naszam** [crytic/echidna#694]
Hi,

I'd like to know if there are any plans to move the echidna action into a separate repo (e.g. actions) as recommended [here](https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action) for custom actions, to allow release versioning and tracking.

This should also allow to reference the echidna action in the workflow job as follow:
```
steps:
	- uses: crytic/actions/echidna
```
and ease action discovery for the community (it could also be published to the GitHub Marketplace).

Thanks!

**Comment by ggrieco-tob** [comment]
@smoelius what is your view on this?
