### ISSUE TITLE
Add wiki page for seeding echidna with deployment script

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/echidna#698]
The README links to a non-existent wiki page: https://github.com/crytic/echidna/wiki/Deployment-of-a-contract-using-Truffle,-Ganache-and-Etheno-to-test-with-Echidna

This is a FAQ, so I think adding a wiki page or linking to [this building secure smart contracts section](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/end-to-end-testing.md) would be helpful.

https://github.com/crytic/echidna/issues/693#issuecomment-975142943

**Comment by ggrieco-tob** [comment]
Fixed
