### ISSUE TITLE
Question: How to do remappings for Solc compiler?

### ISSUE THREAD

**Issue by jrocco2** [crytic/echidna#708]
Typically when dealing with Solc you can use remapping to solve any path issues that might be encountered. 

For example you can add a remapping for OpenZeppelin using:

 `@openzeppelin/=$(pwd)/node_modules/@openzeppelin/` 

as stated [here](https://docs.soliditylang.org/en/v0.6.2/using-the-compiler.html#using-the-commandline-compiler).

However with Echidna, when I specify solcArgs it prepends "--" before my remapping to something like this:
 `--@openzeppelin/=$(pwd)/node_modules/@openzeppelin/` 

which is invalid. 

So what is the best way to do remapping in Echidna for solc?

**Comment by ggrieco-tob** [comment]
Hi,

Why do you need remappings in echidna exactly? If you using a compilation framework like Truffle or Hardhat, these are automatically handled by such tools and you don't need to configure them manually.

**Comment by jrocco2** [comment]
I'm trying to run Echidna from within Docker. When I do this Solc is unable to detect the OpenZeppelin libraries when Echidna is run.

**Comment by ggrieco-tob** [comment]
This is not an issue of echidna, nor something you should solve manually using remappings. The correct way to do it is to make sure you can properly compile your contracts using Docker. @elopez can you give @jrocco2 some pointers about it?

**Comment by jrocco2** [comment]
I would love some pointers for sure! I was just following the tutorial that suggested doing this when I hit the error

`
docker pull trailofbits/eth-security-toolbox
`
`docker run -it -v "$PWD":/home/training trailofbits/eth-security-toolbox`

If there is something else I need to do please let me know.

**Comment by elopez** [comment]
What framework are you using @jrocco2? Are the contracts you're trying to test public? I can give you some more detailed pointers if you let me know, but the general idea is that you should not do `echidna-test foo/Contract.sol` when you have a complex project, but instead leverage the compilation framework to handle the compilation step. You can do so by running something like `echidna-test folder/ --contract Contract`, where `folder/` is the folder that contains your project (i.e. where you would usually run `hardhat compile` or similar) and `Contract` is the contract you'd like to test.

Depending on what your compilation framework is, you might need to either install some more dependencies in the Docker container, or compile your project outside of the Echidna Dockerfile and then make use of the `--ignore-compile` option via `cryticArgs` option.

**Comment by jrocco2** [comment]
@elopez Thank you so much this was enough information to fix the problem. Im using hardhat. In the end all i needed to do was change this:

`# echidna-test $ECHIDNAPATH/EchidnaTest.sol --contract EchidnaTest --config echidna.config.yaml `

to this:

`echidna-test ./ --contract EchidnaTest --config echidna.config.yaml `

One question: It looks like the crytic-export folder is acting as some caching of the contracts. I fixed an error causing a crash but this didnt fix the problem in echidna until I deleted the crytic-export folder. Is there an argument I can add to `cryticArgs` to refresh the cache on every test?

**Comment by ggrieco-tob** [comment]
> I fixed an error causing a crash but this didnt fix the problem in echidna until I deleted the crytic-export folder. Is there an argument I can add to cryticArgs to refresh the cache on every test?

Which version of echidna are you using?

**Comment by jrocco2** [comment]
Inside the Docker container its Echidna 1.7.2

**Comment by ggrieco-tob** [comment]
Oh, then that issue was fixed in [1.7.3](https://github.com/crytic/echidna/releases/tag/v1.7.3) in case you want to upgrade. In any case, since this is already solved, I will close the issue.

**Comment by jrocco2** [comment]
Ok thank you!

**Comment by eriktoor** [comment]
Same here ^^ has anyone gotten to the bottom of this?

**Comment by eriktoor** [comment]
Cool thanks a bunch for the info. I'm pretty new to web3 and just doing this with an express api in JS.

Right now the workflow is we have an express API, we have an endpoint that compiles the user contract (**which we fail at right now** when we try to add support for problems that use these imports like openzeppelin), and then we send it to a ganache node and we make a bunch of calls against it. 

```
  const input = {
    language: "Solidity",
    sources: {
      "MyContract.sol": {
        content: source,
      },
    },
    settings: {
      outputSelection: {
        "*": {
          "*": ["*"],
        },
      },
    },
  };

  const output = JSON.parse(solc.compile(JSON.stringify(input)));
```

Would that fit in my current setup and would the remaps from that config go somewhere in my input struct? 

project -- https://www.wriggly.io/problems/simple-hash/

Thanks a bunch for the help!

**Comment by elopez** [comment]
I'm not sure I follow, how does Echidna come into play on your project?

**Comment by eriktoor** [comment]
Oh I guess I was asking if I can use echidna for this use case.

**Comment by elopez** [comment]
Echidna is a fuzzer, not a tool to compile contracts. Look into e.g. Hardhat, Foundry, Truffle, Brownie, Dapp if you need a tool to assist in compilation and testing 👍

**Comment by tinmyowin7** [comment]
It's that okay if only use the echidna tools for testing purpose... Not depends on other framework.

**Comment by tinmyowin7** [comment]
It's mean used like cryticArgs: ["--solc-remaps", "@magic/=bar/ @foo/=baz/"].
So, we can use like 
cryticArgs: ["--solc-remaps", "@openzepplin/=lib/ @solmate/=lib/"] something like that....
