### ISSUE TITLE
See why a contract deployment failed

### ISSUE THREAD

**Issue by sjkelleyjr** [crytic/echidna#720]
I'm trying to run echidna against a contract that contains a bunch of mock contracts but I'm getting the following error:

```
echidna-test: Deploying the contract failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)
```

Is there a way to see why the deployment failed?

I'm also curious to _where_ echidna deploys the contract (is it ganache?), and what is used to do the deployment (is the repo's build system used?).

**Comment by ggrieco-tob** [comment]
> Is there a way to see why the deployment failed?

Not really, but this feature is on our TODO list already :smile: 

> I'm also curious to where echidna deploys the contract (is it ganache?), and what is used to do the deployment (is the repo's build system used?).

Normally, Echidna deploys the specified contracts inside its simulated blockchain (which is powered by hevm). If you want to use ganache and your deployment scripts to deploy something for Echidna, check this tutorial:

https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/end-to-end-testing.md

**Comment by sjkelleyjr** [comment]
thank you @ggrieco-tob! ❤️

**Comment by rickbeeloo** [comment]
A bit more detail when throwing the error would be awesome! I also encounter the error when investigating this scam contract ([pastebin](https://pastebin.com/mSGipm7J)). I called `./echidna-test mint.sol --contract Ninjacat` and tried increaseing the codesize in a config.yaml which did fail

**Comment by ggrieco-tob** [comment]
What do you mean, there is no Ninjacat contract there:

```
echidna-test: Given contract "Ninjacat" not found in given file
```

**Comment by rickbeeloo** [comment]
Would be amazing if it can detect the function like `gfwzlc` that mints tokens. I tried looking at it with Slither however that will require quite some extra work to go through the IRs and call graph. Not sure how/if I can do this with Echidna but for now still stuck at actually running it :(

**Comment by ggrieco-tob** [comment]
Testing this requires to deploy a Uniswap router at 0x10ED43C718714eb63d5aA57B78B54704E256024E:

```
   constructor () {
        _tOwned[_msgSender()] = _tTotal;

        IUniswapV2Router02 _uniswapV2Router = IUniswapV2Router02(0x10ED43C718714eb63d5aA57B78B54704E256024E);
        // Create a uniswap pair for this new token
        address _uniswapV2Pair = IUniswapV2Factory(_uniswapV2Router.factory()).createPair(address(this), _uniswapV2Router.WETH());
```

That is why this reverts. Regarding your slither question, feel free to start a discussion in the slither github, if you have some idea for a tool or new specific use case.
