### ISSUE TITLE
Error when following the example from README

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [crytic/echidna#724]
1. I've installed the `echidna` binary on a MacOS BigSur (Intel CPU)
2. `git cloned` the repository
3. Running `echidna-test tests/solidity/basic/flags.sol` returns:
```
echidna-test: crytic-export: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

Context:
echidna version -> 2.0.0
crytic-compile -> 0.1.0

**Comment by ggrieco-tob** [comment]
Can you try running: `crytic-compile tests/solidity/basic/flags.sol` ? If you don't have it installed, use: `pip install slither_analyzer` to install it)

**Comment by ggrieco-tob** [comment]
Which version of solidity are you using?

**Comment by ggrieco-tob** [comment]
It seems solc 0.8.11 works fine here (with exactly that example). Can you please open an issue in https://github.com/crytic/crytic-compile/issues?

**Comment by Daniel-K-Ivanov** [comment]
Just noticed that my version if `0.1.0` so I've updated to the latest one (0.2.2). Now the compilation works but when I run `echidna-test tests/solidity/basic/flags.sol` I get:
```bash
MacBook-Pro-3:echidna danielivanov$ echidna-test tests/solidity/basic/flags.sol
Analyzing contract: /Users/danielivanov/limechain/echidna/tests/solidity/basic/flags.sol:Test
echidna-test: Error running slither:
Traceback (most recent call last):
  File "/usr/local/bin/slither", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 459, in main
    main_impl(all_detector_classes=detectors, all_printer_classes=printers)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 472, in main_impl
    printer_classes = choose_printers(args, all_printer_classes)
  File "/usr/local/lib/python3.7/site-packages/slither/__main__.py", line 213, in choose_printers
    raise Exception('Error: {} is not a printer'.format(p))
Exception: Error: echidna is not a printer


```

**Comment by elopez** [comment]
Do you have the latest `slither-analyzer` installed? `slither --version` should be 0.8.2

**Comment by Daniel-K-Ivanov** [comment]
> Do you have the latest `slither-analyzer` installed? `slither --version` should be 0.8.2

oh... thank you very much! I had 0.6.2 installed. Going to `0.8.2` resolved my problem! 🙏
