### ISSUE TITLE
Echidna cannot fail invariant `example1` from "Building Secure Contracts"

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [crytic/echidna#727]
Solidity file to test:
```Solidity
pragma solidity 0.8.10;

contract Token {

    mapping(address => uint) public balances;

    function transfer(address to, uint value) public {
        balances[msg.sender] -= value;
        balances[to] += value;
    }
}

```

Echidna test file:
```Solidity
pragma solidity 0.8.10;

import "./Token.sol";

contract TestToken is Token {

    address echidna_caller = 0x00a329C0648769a73afAC7F9381e08fb43DBEA70;

    constructor() public{
        balances[echidna_caller] = 10000;
    }

    // add the property
    function echidna_test_balance() view public returns(bool){
        return balances[echidna_caller] <= 10000;
    }

}
```

Echidna is not able to break the invariant when running  `echidna-test ./TestToken.sol`. I've tried to configure the send to be another address through a config file but with the same effect.

**Comment by ggrieco-tob** [comment]
Thanks for the report. We are still adjusting the code of building secure smart contracts to match the latest echidna release. However, where exactly you found that code? None of the examples we have use solidity 0.8.10;

**Comment by Daniel-K-Ivanov** [comment]
> Thanks for the report. We are still adjusting the code of building secure smart contracts to match the latest echidna release. However, where exactly you found that code? None of the examples we have use solidity 0.8.10;

I changed the code to solidity version 0.8.10, but kept the same logic.

**Comment by ggrieco-tob** [comment]
Which example or exercise exactly you used? Btw, Solidity 0.8.x will enforce a revert if there is a overflow or underflow, so I cannot see a way to break the property.

**Comment by Daniel-K-Ivanov** [comment]
I used this one:
https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/Exercise-1.md

At first I used the original with solidity 0.8.11, but then when I noticed that the property cannot be broken, I wanted to simplify the code and post it as an issue.

Maybe I do not understand, but in the example above, shouldn't it fail the first time echidna invokes `transfer(0x00a329C0648769a73afAC7F9381e08fb43DBEA70, any uint)`? or Echidna will never do such a call since the `msg.sender` is always `0x00a329C0648769a73afAC7F9381e08fb43DBEA70` ?

**Comment by elopez** [comment]
`transfer(0x00a329C0648769a73afAC7F9381e08fb43DBEA70, any uint > 0)` will revert when compiled with Solidity 0.8.x because there is [a math operation underflowing](https://docs.soliditylang.org/en/v0.8.11/080-breaking-changes.html#solidity-v0-8-0-breaking-changes). You would need to use `unchecked { ... }` in `transfer` for it to be vulnerable when compiled with Solidity 0.8.x.

This is not the case with earlier Solidity, which let the math operation wrap without reverting -- so the code is vulnerable "out of the box" when you use the original pragma with the older Solidity.

**Comment by ggrieco-tob** [comment]
> At first I used the original with solidity 0.8.11, but then when I noticed that the property cannot be broken, I wanted to simplify the code and post it as an issue.

We should improve the explanation to make sure people understand that solc 0.4.x is required for this.

> Maybe I do not understand, but in the example above, shouldn't it fail the first time echidna invokes transfer(0x00a329C0648769a73afAC7F9381e08fb43DBEA70, any uint) from an address different than 0x00a329C0648769a73afAC7F9381e08fb43DBEA70? or Echidna will never do such a call since the msg.sender is always 0x00a329C0648769a73afAC7F9381e08fb43DBEA70 ?

This token is created using only the address `0x00a329C0648769a73afAC7F9381e08fb43DBEA70` to have a balance of `10000`. Every other user will have no balance at all, and therefore, won't be able to transfer anything.

**Comment by Daniel-K-Ivanov** [comment]
Thank you for the explanations. My fault

**Comment by Daniel-K-Ivanov** [comment]
Actually, I've changed the code to:
File to be tested:
```Solidity
pragma solidity 0.8.10;

contract Token {

    mapping(address => uint) public balances;

    function transfer(address to, uint value) public {
        balances[msg.sender] -= value;
        balances[to] += value;
    }
}
```


```Solidity
pragma solidity 0.8.10;

import "./Token.sol";

contract TestToken is Token {

    address echidna_caller = 0x00a329C0648769a73afAC7F9381e08fb43DBEA70;

    constructor() public{
        balances[echidna_caller] = 10000;
    }

    function echidna_test_balance() view public returns(bool){
        return balances[echidna_caller] == 10000;
    }
}
```

and it does not the fail the property as-well. The reason is that all of the 50k fuzzings are performed with:
- `msg.sender` as `0x00a329C0648769a73afAC7F9381e08fb43DBEA70` (this is okay)
- `to` is always `0x00a329C0648769a73afAC7F9381e08fb43DBEA70` -> wonder why is that the case?
Obviously one transfer with `to` != `0x00a329C0648769a73afAC7F9381e08fb43DBEA70` will fail the invariant, but echidna does not execute it. I am struggling to understand why.

**Comment by elopez** [comment]
From what I can tell [looking at the code](https://github.com/crytic/echidna/blob/31034fbf8d147911ba2176522dc11d3a0a490a35/lib/Echidna/Config.hs#L147), Echidna 2 will only initiate transactions (`sender` config) from one of the following addresses by default: [0x10000, 0x20000, deployer]. The new `deployer` address is 0x30000 (breaking change mentioned in the release notes for echidna v2)

If you let Echidna send transactions from `0x00a329c0648769a73afac7f9381e08fb43dbea70` it will break the property. You can do so by creating a `sender.conf` config file with the following:

```ini
sender: ["0x10000", "0x20000", "0x00a329c0648769a73afac7f9381e08fb43dbea70"]
```

And running `echidna-test ./TestToken.sol --config sender.conf`

```text
% ./echidna-test TestToken.sol --config sender.conf --format text
Multiple contracts found, only analyzing the first
Analyzing contract: <snip>/TestToken.sol:TestToken
echidna_test_balance: failed!💥  
  Call sequence:
    transfer(0x20000,549) Time delay: 369938 seconds Block delay: 45885



Unique instructions: 459
Unique codehashes: 1
Corpus size: 1
Seed: 6746206514043095611
```

I feel this is a sign that the docs need some more work, what do you think @ggrieco-tob?

**Comment by ggrieco-tob** [comment]
This is correct. As I said, our documentation should be updated to match the latest release.
