### ISSUE TITLE
Mac OS, Couldn't look up terminfo entry

### ISSUE THREAD

**Issue by DanielVF** [crytic/echidna#729]
I'm on Mac OS 11.4, and have just downloaded the latest 2.0.0 release of echidna. I'm running the new executable in place of my existing echidna 1.x setup. However when I run the new echidna, it errors with:

```
Analyzing contract: [..snip..]
echidna-test: setupTerm: Couldn't look up terminfo entry "xterm-256color"
```

I've also tried:
- running it tmux, which changes the error to not being able to look up "screen".
- running it in different kind of shell (fish vs bash)
- export TERMINFO=/usr/share/terminfo/78/xterm-256color

I'm using the stock Mac OS Terminal program.

Any pointers for debugging this?

**Comment by ggrieco-tob** [comment]
@incertia any idea about this? :point_up:

**Comment by anishnaik** [comment]
For a short term fix append `--format text` to your command and it should work.

Example (with Echidna 2.0):
`$ echidna-test MyToken.sol --test-mode property --format text`

**Comment by DanielVF** [comment]
This does work! Thanks, @anishnaik.

I'm running into an unrelated issue now, but I'll mess with it a bit first before reporting.

**Comment by elopez** [comment]
Hi @DanielVF ! Are you using a M1 Mac by chance? Could you run `export TERMINFO=/usr/share/terminfo` and try running echidna again?

I suspect this is related to the way the M1 binaries are built. If you can help me confirm my suspicions that would be awesome 😄

**Comment by DanielVF** [comment]
Yes, M1 MacBook Pro.

And not only does `export TERMINFO=/usr/share/terminfo` fix the first issue, it also fixes the second issue I was seeing as well!
