### ISSUE TITLE
ERC1820 support 

### ISSUE THREAD

**Issue by hellwolf** [crytic/echidna#739]
https://eips.ethereum.org/EIPS/eip-1820 uses a specific deployment method, that guarantees the "Registry Contract Address" to be deployed to the same address 0xa990077c3205cbDf861e17Fa532eeB069cE9fF96.

The notable use case of this standard is the ERC777 compatible tokens.

But it is not clear how to write a echidna test that have those registry contract to be deployed at the same address without having to instrument the code directly to abstract the EIP-1820 away from the core logic.

Please advise!

**Comment by ggrieco-tob** [comment]
You should able to deploy EIP-1820 using 2.0.2. Please reopen if you have issues with that.

**Comment by hellwolf** [comment]
GREAT!
