### ISSUE TITLE
Add testMode to config in wiki

### ISSUE THREAD

**Issue by Namaskar-1F64F** [crytic/echidna#748]
The [config page](https://github.com/crytic/echidna/wiki/Config) of the wiki does not include `testMode` which I found peculiar. Below is what I'm using in my config taken mostly from the [Simplified Test Configuration](https://github.com/crytic/echidna/releases/tag/v2.0.0) and organized in the same order of the [`validateTestModeError` ](https://github.com/crytic/echidna/blob/v2.0.0/lib/Echidna/Test.hs#L59) string.

- `testMode`
  - Type: String
  - Default: `"property"`
  - Description: The test mode to run.
    - `"property"`: Run user-defined property tests.
    - `"assertion"`: Detect assertion failures (previously checkAsserts).
    - `"optimization"`: Find the maximum value for a function.
    - `"overflow"`: Detect integer overflows (Solidity 0.8.x+).
    - `"exploration"`: Execute every line of code without any testing target ("unconstrained execution").

**Comment by ggrieco-tob** [comment]
Good catch, I will update the wiki page soon.

**Comment by ggrieco-tob** [comment]
Fixed. Thanks!
