### ISSUE TITLE
Enable FFI cheatcode

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#749]
By default HEVM creates a VM where `vmoptAllowFFI` is set to false:

https://github.com/dapphub/dapptools/blob/a2b96cc2dbc28508c9fe699d6438bf6eccafc2ad/src/hevm/src/EVM/Exec.hs#L21-L46

We can add a flag in Echidna to set this to true (or just always enable it to true if it does not impact performance).

**Comment by patrickd-** [comment]
Rather than impacting peformance, true-by-default may impact developer's local security, so a flag would probably be preferable

>It is generally advised to use this cheat code as a last resort, and to not enable it by default, as anyone who can change the tests of a project will be able to execute arbitrary commands on devices that run the tests. ([from foundry docs](https://book.getfoundry.sh/reference/cheatcodes.html#ffi))

**Comment by ggrieco-tob** [comment]
I'm working on this in #750, it should work if you want to test it.

**Comment by ggrieco-tob** [comment]
Already in `master`.
