### ISSUE TITLE
Is Etheno still in usage together with Echidna?

### ISSUE THREAD

**Issue by BarrySauce** [crytic/echidna#753]
I am referring to the tutorial of Echidna (https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/end-to-end-testing.md), which is using Echidna with Etheno and Ganache. 

I know the basic process is to deploy the contracts on Ganache using truffle or hardhat, and Etheno which runs at the backend would collect information and generate an init file. Echidna can use that init file to replay the information in hevm to realize complex deployment. 

However, currently when I use Etheno with Ganache-cli in node 12.22.11, there would be error occuring:
<img width="1512" alt="Screenshot 2022-04-11 at 10 17 50 AM" src="https://user-images.githubusercontent.com/84897434/162655979-a0196ae0-596f-4fe1-86c3-a440cbc7864c.png">

May I know if Etheno is still in usage with Echidna (since Etheno lastest update was about 2 years ago)? And if it has been abandoned for usage, may I know if there's other ways to deploy the contracts with constructor in need of inputs to hevm? If it is possible, may I get an example on how to use Echidna on a detailed smart contract project?

I am new in the contract fuzzing field, and I am really eager to know more about this amazing tool, would really be appreciate it if you guys can answer my questions. Thank you!

**Comment by ggrieco-tob** [comment]
Etheno is still usable with Echidna, but this looks like an etheno issue, so I'm closing this issue in favor of the discussion in the etheno repository. Also feel free to join EmpireHacking slack for chating with us on how to test with smart contract fuzzing :smiley:

**Comment by BarrySauce** [comment]
Ok sir, thank you for your reply! Then I believe it is the problem of Ganache-cli, maybe it does not support node 12 anymore. I will switch to the Etheno repositry to continue discussion of the problem with you :)

**Comment by BarrySauce** [comment]
And sir, may I ask for now is Etheno frequently used together with Echidna in the fuzzing scenario? Or there are more straight-forward method to perform fuzzing?
I browse online and find another tutorial to use proxy contract to perform fuzzing with Echidna. I am referring to this tutorial: https://github.com/crytic/echidna/wiki/How-to-use-Echidna-with-multiple-contracts

**Comment by BarrySauce** [comment]
> Ok sir, thank you for your reply! Then I believe it is the problem of Ganache-cli, maybe it does not support node 12 anymore. I will switch to the Etheno repositry to continue discussion of the problem with you :)

Ok sir, thank you for your reply! Then I believe it is the problem of Ganache-cli, maybe it does not support node 12 anymore. I will switch to the Etheno repositry to continue discussion of the problem with you :)

**Comment by BarrySauce** [comment]
> Etheno is still usable with Echidna, but this looks like an etheno issue, so I'm closing this issue in favor of the discussion in the etheno repository. Also feel free to join EmpireHacking slack for chating with us on how to test with smart contract fuzzing 😃

And sir, may I ask for now is Etheno frequently used together with Echidna in the fuzzing scenario? Or there are more straight-forward method to perform fuzzing?
I browse online and find another tutorial to use proxy contract to perform fuzzing with Echidna. I am referring to this tutorial: https://github.com/crytic/echidna/wiki/How-to-use-Echidna-with-multiple-contracts

**Comment by ggrieco-tob** [comment]
Hi @BarrySauce 

Echidna is sometimes used with Echidna, usually in complex scenarios (multiple contracts that are initialized with a specific procedure). If you want to start using our tool, it is better to do it without etheno, to make sure you understand how to create properties. Make sure you review all the documentation here: https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna

Regarding this other tutorial, it shows a way to manually proxy several contracts, but it is unrelated with the usage of etheno. The wiki contained some old documentation that will be redone and moved into building-secure-contracts.

**Comment by BarrySauce** [comment]
@ggrieco-tob  ok sir, thank you for your explanation. I will try both methods and see which method I prefer.
