### ISSUE TITLE
Handling eth transfer transactions with "0x0" as data in Etheno initialization file

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#754]
I've modified etheno to be able to handle simple eth transactions where there is no `data` in the transaction.

Quick snippet:
```
# transaction["data"],   # this line crashes with simple eth transfers
transaction["data"] if "data" in transaction else "0x0",
```

Echidna doesn't like this. I get the following error:
```
echidna-test: Error parsing Etheno initialization file: Error in $[12]: could not decode hexstring: invalid bytestring size
```

This is what my etheno initialization file entry looks like:
```
 {
    "event": "FunctionCall",
    "from": "0x5409ed021d9299bf6814279a6a1411a7e866a631",
    "to": "0x1dc4c1cefef38a777b15aa20260a54e584b16c48",
    "gas_used": "0x19b3b",
    "gas_price": "0x4a817c800",
    "data": "0x0",
    "value": "0x3635c9adc5dea00000"
  }
```
If i change `data` to something else (for example `"data": "0x9f1c08ee",`) it works.

Is this a bug? 

If nessecary I could also change the data into something different than `0x0`.

Thanks

**Comment by rappie** [comment]
I've tested setting `data` to the ABI function signature of `receive()` and this works. So I have a workaround solution for now.

Example:
```
{
    "event": "FunctionCall",
    "from": "0x5409ed021d9299bf6814279a6a1411a7e866a631",
    "to": "0x1dc4c1cefef38a777b15aa20260a54e584b16c48",
    "gas_used": "0x19b3b",
    "gas_price": "0x4a817c800",
    "data": "0xa3e76c0f",
    "value": "0x3635c9adc5dea00000"
  }
```

https://www.4byte.directory/signatures/?bytes4_signature=0xa3e76c0f

**Comment by ggrieco-tob** [comment]
great, but this needs to be fixed, let me take a quick look

**Comment by ggrieco-tob** [comment]
@rappie use etheno to encode the empty as "0x00", I think that should work. It will decode `\0` which is technically not the empty string, but it is good idea to allow to detect if the field is empty or not, in case some kind of error.

**Comment by rappie** [comment]
That works :smile: 

I've made a PR for this in etheno:
https://github.com/crytic/etheno/pull/96

**Comment by ggrieco-tob** [comment]
Uhm, can you also try "0x" as a workaround? I think I saw it in some tools and it is better to provide the empty data instead of a null byte.

**Comment by rappie** [comment]
Yes, this also works. I've updated the PR.

**Comment by ggrieco-tob** [comment]
The etheno PR is merged, let's close this one. Thanks for the help!
