### ISSUE TITLE
Echidna Does Not Decrement Sender Balance

### ISSUE THREAD

**Issue by DanielGelfand** [crytic/echidna#755]
```
pragma solidity ^0.8.0;

contract TestContract {

    uint256 public initBal;

    constructor() {
        initBal = address(0x10000).balance;
    }

   // This should fail as ETH can be sent through testPayable
    function echidna_check_bal_decreases() public returns (bool) {
        return address(0x10000).balance == initBal;
    }   

    function testPayable() public payable returns (bool) {
        require(msg.value > 0);
        return true;
    }

    function receive() public payable {}
}

```

The echidna_check_bal_decreases property passes even though there are payable functions that accept ETH. Echidna 2.0.1 was run with default parameters. Do the balances for the default senders never get decremented?

**Comment by ggrieco-tob** [comment]
This is odd, but expected. We don't keep track of the sender balances, and we can assume that users have an unlimited amount of ETH. Is there some use case that you need to check for balances from the senders?

**Comment by ggrieco-tob** [comment]
I think the best workaround is to use the testing contract (e.g. `address(this)`) with certain amount of Ether and avoid payable functions. You will be able to send ether and the balance should be updated correctly. 

If you are wondering why we don't keep track of EOA balances is to avoid payable transactions to revert with out of balance. It is difficult to estimate how much ether we can send in every transaction if this can change. Attackers can have large amount of funds or manipulate their balance in any way. We will still keep this issue open to see if there are improvements to do.

**Comment by ggrieco-tob** [comment]
Uhm it looks like this was already in an older issue (https://github.com/crytic/echidna/issues/573) so I will close this as duplicated, but feel free to continue the discussion there. :smiley:
