### ISSUE TITLE
Fuzzings hangs on second .call

### ISSUE THREAD

**Issue by EVLRBT-01** [crytic/echidna#759]
Hey! 

New to Solidity and have managed to implement a test suite with Forge along with Slither analysis. I am now trying out Echidna and seem to be facing a scenario which hangs the fuzzing. 

I have a withdraw function on a contract which uses OpenZeppelin Address to send a split payment, but the second `Address.sendValue()` seems to cause the fuzzing to hang. I also tried using just `payable(address(1).call{value: amount}("");` from the `Address.sendValue()` implementation (i.e. without the `require`s) but the same occurs - unless I comment out the second line. 

A simple example:
```
pragma solidity 0.8.9;

import "@openzeppelin/contracts/utils/Address.sol";

contract Test {

    function withdraw() external {
        uint256 balance = address(this).balance;
        Address.sendValue(payable(address(1)), balance * 500/1000);
        Address.sendValue(payable(address(2)), balance * 500/1000);
    }

    function echidna_Test() public view returns(bool){
         return true;
    }
}
```

Any ideas/workarounds?

**Comment by ggrieco-tob** [comment]
Hi,

A few questions for you:

* Which version of Echidna are you using? 
* What do you mean with 'seems to cause the fuzzing to hang'?
* Have you configured your fuzzing campaign to send ether to the `Test` contract? I believe the balance should be always 0.

Finally: 0x1 and 0x2 are precompile contracts, which are not usually a good idea to send balance. Can you retry with other addresses instead (e.g. 0x42).

**Comment by EVLRBT-01** [comment]
Thanks for your response!

- Latest version: Echidna 2.0.1
- It shows the dashboard but it remains 'blank' and doesn't advance through the fuzzing, like it does when I comment out the second transfer.
With both transfers:
![image](https://user-images.githubusercontent.com/60948618/165257481-84871194-af94-43c4-9b92-7026287a0470.png)
Second transfer commented out:
![image](https://user-images.githubusercontent.com/60948618/165257149-f1dab26e-fd78-4dc8-9c42-e9c61c7457ba.png)
- I have now added `balanceContract: 100000000000000000000 # 100 eth` to the config file and running with `echidna-test . --contract Test --config echidna.config.yml` has the same result (unless I comment out the second transfer).
 
I have tried with new contract addresses as suggested (see below) but same result. I added the payable constructor to get around https://github.com/crytic/echidna/issues/446 when using balanceContract.
```
pragma solidity 0.8.9;

import "@openzeppelin/contracts/utils/Address.sol";

contract Test {

    constructor() public payable { }

    function withdraw() external {
        uint256 balance = address(this).balance;
        Address.sendValue(payable(address(0x42)), balance * 500/1000);
        Address.sendValue(payable(address(0x43)), balance * 500/1000);
    }

    function echidna_Test() public view returns(bool){
         return true;
    }
}
```
 
PS - If I watch the process usage, it rises for a bit and then drops to zero, whereas with the second transfer line commented out it stays around 12% until the 50,000 fuzz tests are completed and then drops to zero.

**Comment by ggrieco-tob** [comment]
Can you please re-try using `--format text` in your command line?

**Comment by EVLRBT-01** [comment]
Thanks, that seems to have uncovered something!

`echidna-test: VM failed for unhandled reason, Query <EVM.Query: fetch contract 0x0000000000000000000000000000000000000043>. This shouldn't happen. Please file a ticket with this error message and steps to reproduce!`

**Comment by ggrieco-tob** [comment]
This is an issue in our code, please test #760, which should work properly with your code.

**Comment by EVLRBT-01** [comment]
Seems to be working, thanks for the quick turnaround! I had trouble getting a manual build on Arch Linux, so eventually just used the https://github.com/crytic/echidna/suites/6278403752/artifacts/224513612 artifact.

Thanks again!

**Comment by ggrieco-tob** [comment]
Awesome!, I have a fix for ArchLinux build, I noticed that the compilation won't link unless you made some small changes in the package file. I will create a PR about that soon.
