### ISSUE TITLE
Validate config to avoid VM errors

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/echidna#765]
If a config file has large values, it causes an error that is only evident when running `--format text` e.g. `echidna: VM attempted an illegal operation: IllegalOverflow`
Ex: 
```
propMaxGas: 0xfffffffffffffffffffffffffffff
testMaxGas: 0xfffffffffffffffffffffffffffff
codeSize: 0xfffffffffffffffffffffffffffff
```
Add data validation to config parsing

**Comment by ggrieco-tob** [comment]
Please test #792. Note that I cannot reproduce this issue with latest echidna with small contract (perhaps it can be triggered with large ones)

**Comment by arcz** [comment]
This is fixed https://github.com/crytic/echidna/pull/935.
