### ISSUE TITLE
Feature request: label last reverting line to indicate root cause and aid debugging in coverage report

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/echidna#767]
In the coverage report, `r`'s will indicate a path that is reverting. It would be nice for the last line/ instructions that cause the failure to have a unique symbol instead of just `r`. This would improve debugging and help developers iterate more quickly when working to increase coverage. There may be multiple paths that cause reverts so the new symbol may appear in multiple places. See below for example. I chose `t` for "termination" but it could be anything as long as it's documented how to use this new feature.
Current:
```
r    |  function test() external {
r    |     _internal_revert();
     | }
     |
     | function _internal_revert() internal {
r    |     revert InternalRevert();
     |}
```
Desired:
```
r    |  function test() external {
r    |     _internal_revert();
     | }
     |
     | function _internal_revert() internal {
t    |     revert InternalRevert();
     |}
```

**Comment by ggrieco-tob** [comment]
This is already implemented here: https://github.com/crytic/echidna/pull/746 but it wasn't merged because it needs to be optimized

**Comment by ggrieco-tob** [comment]
In fact, this is a duplicated of #732
