### ISSUE TITLE
Bug: Echidna doesn't detect compilation errors when there are older compiled contracts available

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#779]
I have only tested this using hardhat.

How to reproduce:
* Set up a working echidna fuzzing campaign
* Add a syntax error to one of the contracts. Ex. `echo "}" > contracts/simple.sol`
* Run echidna with the same command. This should not work but works with the old code.
* Run `npx hardhat clean` to remove older compiled contracts
* Run echidna again. Now it crashes with `echidna-test: Couldn't compile given file` (and a lot more stuff)

This bug is actually a lot more annoying than it looks at first sight. I've had many times where I spent like 15 minues trying to figure out why echidna doesnt find anything when it turned out I had a simple syntax error somewhere else in my code.

**Comment by anishnaik** [comment]
Hey @rappie, as a quick fix you can always run these commands in sequence: `npx hardhat clean && npx hardhat compile && echidna-test . --contract MyContract`

This will guarantee that echidna is running on your latest compiled code.

**Comment by ggrieco-tob** [comment]
This is an issue in crytic-compile. Can you migrate this issue to [the corresponding issue tracker](https://github.com/crytic/crytic-compile/issues)? :slightly_smiling_face:
