### ISSUE TITLE
Bug: `block.timestamp` doesn't give the actual date

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#780]
I've tested this using the following contract:
```
contract E2E {
    event Debug(uint256 _timestamp);

    function testSomething() public {
        emit Debug(block.timestamp);
        assert(false);
    }
}
```

The result I get is:
```
Event sequence: Panic(1), Debug(1524785993) from: E2E@0x6Ecbe1DB9EF729CBe972C83Fb886247691Fb6beb
```

`1524785993` translates to Thursday, April 26, 2018 11:39:53 PM

**Comment by ggrieco-tob** [comment]
This is the expected result. Echidna starts with a fixed timestamp. We use like that to be able to easily reproduce issues regardless of the timestamp/block number. I will create a tutorial about handling timestamps soon. If you want to use an arbitrary timestamp or block number, [use hevm cheatcodes](https://github.com/dapphub/dapptools/tree/master/src/hevm#cheat-codes).

**Comment by ggrieco-tob** [comment]
> What about adding a setting to echidnas config where you can set the begin timestamp? Or maybe even an option to use the current date? Let me know what you think, I'll make a seperate feature request if you're into it.

Using current date is really not recommended and it won't match what you in etheno (since it is not possible to capture etheno transaction and run echidna at the same time), but we can give the users that possibility if they want. Feel free to create a feature request with that.

**Comment by rappie** [comment]
Ahh ofcourse, I didn't think this through well enough :smile:

I will think about it more before I write the feature request.
