### ISSUE TITLE
Deploying many large interacting contracts

### ISSUE THREAD

**Issue by elizabethdinella** [crytic/echidna#782]
I am trying to write tests for the [AvvenireAuction](https://etherscan.io/address/0x7bF109cEa662AC66b07c189c2fc8F1cE909ad350#code) contract.  

AvvenireAuction interacts with an externally deployed contract [AvvenireCitizens](https://etherscan.io/address/0x42ef5eb48586757b2f69a37569b6f35120f2515e#code).

AvvenireCitizens interacts with 2 externally deployed byte code contracts. 

To deploy the bytecode contracts, I paste the bytecodes in my config using `deployBytecodes` at the addresses `0x9559067eBb005c002EAd3CD0e09D97C39177ba34` and `0x8F4d063621DDE21d17129c68174a90A67aFC74Fa`. 

When I execute the constructor below, echidna  hangs indefinitely. 

```
constructor() {
        address dataContractAddress = 0x9559067eBb005c002EAd3CD0e09D97C39177ba34;

        citizens = new AvvenireCitizens("AvvenireCitizens", "AVC", "https://av.mypinata.cloud/ipfs/QmYwCridML3Qo3vGSR2QrCs2rvofrTcyL2hd1z9AXqSduN/", 
                                       "",  dataContractAddress, 0x8F4d063621DDE21d17129c68174a90A67aFC74Fa);

        auction = new AvvenireAuction(2, 5000, 1000, 100, address(citizens));
    }
```

Alternatively, I explored deploying AvvenireCitizens using the `deployContracts` flag. However, AvvenireCitizens takes constructor arguments. How can I specify those in the config?

**Comment by ggrieco-tob** [comment]
I'm trying to reproduce this issue, I haven't finish, but it seems that using `codeSize: 0xffffffffff` in the config file allow me deploy `AvvenireCitizens`, but I'm still working on the other ones.

**Comment by elizabethdinella** [comment]
Hi, just checking, is there any update on this?

**Comment by ggrieco-tob** [comment]
It seems that at least one of the contracts, the one deployed at `0x9559067eBb005c002EAd3CD0e09D97C39177ba34` fails when redeployed inside Echidna using its bytecode.

`echidna-test: Deploying the contract 0x9559067eBb005c002EAd3CD0e09D97C39177ba34 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)` 

without source code or more information about this contract, it is impossible to debug, I'm afraid.

**Comment by ggrieco-tob** [comment]
Same with the other one at `0x8F4d063621DDE21d17129c68174a90A67aFC74Fa`.

**Comment by elizabethdinella** [comment]
Ah okay, so there is some require failing in the byte code?
(Rather than something wrong with the way I am deploying the byte code)

**Comment by ggrieco-tob** [comment]
Yes, something inside that CREATE transactions  is reverting. It could be a timestamp requirement, a lack of balance or an external call or something else :thinking:

**Comment by elizabethdinella** [comment]
Great, I had a suspicion this was the case. 
How did you figure this out? I was having trouble since the error message was vague.  

`echidna-test: Deploying the contract 0x9559067eBb005c002EAd3CD0e09D97C39177ba34 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)`

**Comment by brucdarc** [comment]
Also getting this on deploying a large contract system with echidna, is there any way to increase the gas limits? 

``` Analyzing contract: /home/dak/Desktop/harmony/total/aave-v2-modified/total-v1/contracts/TotalV1/test/SimpleEchidnaTest.sol:SimpleEchidnaTest
echidna-test: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)
```

**Comment by ggrieco-tob** [comment]
If the contract is very large, you should using `codeSize: 0xffffffffff`. Otherwise, perhaps reverts for another reason. Please try #871

**Comment by Silur** [comment]
> Please try #871

How?

**Comment by elopez** [comment]
> > Please try #871
> 
> How?

the change in #871 has been merged, if you install the latest echidna version (2.0.5) it should be included in it 👍

**Comment by Silur** [comment]
okay but there's no documentation on how to enable this feature, and I didn't manege to dig it out from the haskell code :)

**Comment by ggrieco-tob** [comment]
@elizabethdinella can you try using the state network forking feature from 2.1.0?

**Comment by ggrieco-tob** [comment]
Closing this one, please reopen if something is wrong.
