### ISSUE TITLE
Feature request: Show contract name in fuzzing results

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#783]
When end-to-end testing multiple contracts it would be nice to see which contracts has been called to fail the test.

Current output
```
testBet(): failed!💥
  Call sequence, shrinking (1736/5000):
    setLp(0x0)
    testBet()
```

Suggested output
```
testBet(): failed!💥
  Call sequence, shrinking (1736/5000):
    Core.setLp(0x0)
    E2E.testBet()
```

**Comment by arcz** [comment]
Fixed in https://github.com/crytic/echidna/pull/1181.
