### ISSUE TITLE
message sign with HEVM sign cheat code fail to verify sometimes

### ISSUE THREAD

**Issue by yuchangyuan** [crytic/echidna#788]
I am not sure this is a bug of my code,  echidna,  upstream hevm, or the code from openzepplin, so I report bug here. Below is the code that may contain bugs, see [here](https://github.com/yuchangyuan/echidna_hevm_sign_and_verify) for full code.

``` solidity
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "./utils/cryptography/ECDSA.sol";
import "./utils/Strings.sol";

import "./IHEVM.sol";

contract T {
    using ECDSA for bytes32;

    IHEVM HEVM = IHEVM(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);

    address constant ADDR1 = address(0x5409ED021D9299bf6814279A6A1411A7e866A631);
    uint256 constant SK1 = 0xf2f48ee19680706196e2e339e5da3491186e0c4c5030670656b0e0164837257d;

    address constant ADDR2 = address(0x6Ecbe1DB9EF729CBe972C83Fb886247691Fb6beb);
    uint256 constant SK2 = 0x5d862464fe9303452126c8bc94274b8c5f9874cbd219789b3eb2128075a76f72;

    bytes32 constant HASH = 0xd36559b60daeb61527567d584bdb80b3226b4a6ab152452abbba4315256da519;
    event AssertionFailed(string message);

    function t(address addr, uint256 sk, bytes32 hash) internal {
        (uint8 v, bytes32 r, bytes32 s) = HEVM.sign(sk, hash);

        bytes memory p_sig = abi.encodePacked(r, s, v);
        (address ra, ) = hash.tryRecover(p_sig);

        assert(ra == addr);

        string memory str = string(abi.encodePacked("sk = ", Strings.toHexString(sk),
                                                    ", hash = ", Strings.toHexString(uint256(hash)),
                                                    ", v = ", Strings.toHexString(v),
                                                    ", r = ", Strings.toHexString(uint256(r)),
                                                    ", s = ", Strings.toHexString(uint256(s))));
        //emit AssertionFailed(str);
    }

    function t1() public {
        t(ADDR1, SK1, HASH);
    }

    function t2() public {
        t(ADDR2, SK2, HASH);
    }

    function t3() public {
        t(ADDR1, SK1, 0x3ac225168df54212a25c1c01fd35bebfea408fdac2e31ddd6f80a4bbf9a5f1cb);
    }
}
```

test `t2` & `t3` pass but `t1` fail in `assertion` mode, both `t1` & `t3` with same key/address pair, but different hash to sign, and both `t1` & `t2` with same hash to sign, so if `t2` & `t3` pass test, then `t1` should not fail.

NOTE: files in `utils` directory is copied from openzepplin 4.5.0.

**Comment by technovision99** [comment]
Hello,

There are a couple things I would like to note:

Firstly, I wasn't able to recreate test `t2` and `t3` failing. I was able to make test `t1()` fail, and the reason is because the `s` value generated is greater than the curve order. See this comment in the ECDSA library for more details: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/83277ff916ac4f58fec072b8f28a252c1245c2f1/contracts/utils/cryptography/ECDSA.sol#L154
Here is the code I used to address the issue: 
```
 if (uint(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            s = bytes32(uint(0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) - uint(s));
            v = v == 28 ? 27: 28;
        } 
```

 I ran all `t1()`, `t2()` and `t3()` with this modified version and did not find any issues. Let me know if this helps!

**Comment by yuchangyuan** [comment]
> Hello,
> 
> There are a couple things I would like to note:
> 
> Firstly, I wasn't able to recreate test `t2` and `t3` failing. I was able to make test `t1()` fail, and the reason is because the `s` value generated is greater than the curve order. See this comment in the ECDSA library for more details: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/83277ff916ac4f58fec072b8f28a252c1245c2f1/contracts/utils/cryptography/ECDSA.sol#L154 Here is the code I used to address the issue:

what you observe is right, test `t2` and `t3` will **PASS** the test, only `t1` will fail
> 
> ```
>  if (uint(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
>             s = bytes32(uint(0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) - uint(s));
>             v = v == 28 ? 27: 28;
>         } 
> ```
> 
> I ran all `t1()`, `t2()` and `t3()` with this modified version and did not find any issues. Let me know if this helps!

This helps very much, thank you, I will close this issue.

**Comment by technovision99** [comment]
There is one slight error in the code actually, in order to get the correct two's complement byte representation of `s`, you would have to wrap the code in an `unchecked()` block. Sorry for the confusion!
```
 if (uint(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            unchecked {
                s = bytes32(uint(0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) - uint(s));
                v = v == 28 ? 27: 28;
                }
       }
```

**Comment by yuchangyuan** [comment]
Thank you for your clarification, the code is enough for a demonstration even without `unchecked`. Actually, I fix my code according to the [comment in ECDSA.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/83277ff916ac4f58fec072b8f28a252c1245c2f1/contracts/utils/cryptography/ECDSA.sol#L160), as below, which should have the same effect of your code:
``` solidity
        if (uint256(s) > 0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0) {
            s = bytes32(0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 - uint256(s));
            v = (v == 28) ? 27 : 28;
        }
```
