### ISSUE TITLE
Feature request: Interactive commands while echidna is running

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#800]
It would be nice to have control over certain parameters while echidna is running, instead of having to edit the config file and restart echidna.

I would particularly like this so I can play around with the `seqLen` setting while echidna is running.

Some possibly useful commands I can think of right off the bat:
- `seqLen` as mentioned above
- Length of the total run
- Timelimit of total run
- Write corpus (and coverage) to disk
- Reload corpus from disk? (if possible)
- Time/block delay

**Comment by ggrieco-tob** [comment]
You want to be able to adjust this parameters during a fuzzing campaign? If this is the case, AFAIK, this is very unusual to do this during fuzzing (either of smart contract or normal programs), but perhaps if we see some piece of research or specific use case, we can try to implement it.

**Comment by rappie** [comment]
I wouldn't use this during the real fuzzing campaign but during research, experimentation, setting up property tests, etc.

For example: When trying to improve coverage I often want to test how fast Echidna reaches certain points in the code. If i use a big `seqLen` (250 or more) it can take a pretty long time to reach a certain corpus size (lets say 80). It would be very handy to start off with a `seqLen` of 10 and interactively increase it when ready.

There's more examples like this.

**Comment by ggrieco-tob** [comment]
Echidna can be monitored using json events over the local network, but we don't have support for changing its state.

**Comment by rappie** [comment]
This is a very old idea and issue of me. I'm ok with it being closed :slightly_smiling_face:
