### ISSUE TITLE
Logging events without an assertion failure

### ISSUE THREAD

**Issue by elizabethdinella** [crytic/echidna#801]
Hi, upon triggering an assertion failure, Echidna prints the event sequence. 
Is there a way to log all events emitted even when the execution passes?

**Comment by ggrieco-tob** [comment]
Currently, there is no way to do it, but you can still invert the test to force a failure and then inspect the events.

**Comment by elizabethdinella** [comment]
Thanks! Is this because of the overhead of logging?

**Comment by ggrieco-tob** [comment]
yes but also it is unclear how to show these to the user during runtime (the amount of information can be very large in real contracts)
