### ISSUE TITLE
ERROR:CryticCompile:Invalid solc compilation Invalid option selected, must specify either --bin or --abi

### ISSUE THREAD

**Issue by Arinerron** [crytic/echidna#802]
output:
```
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Invalid solc compilation Invalid option selected, must specify either --bin or --abi
```

cmdline:
```
PATH="$PWD/solc:$PATH" echidna-test FuzzingContract.sol --contract FuzzingTest --config ./echidna.config.yaml --format text
```

solc wrapper to get solc's cmdline:
```
$ ls solc 
abi.js    LICENSE    node_modules  README.md      smtsolver.js  solcjs      translate.js
index.js  linker.js  package.json  smtchecker.js  solc          soljson.js  wrapper.js

$ cat solc/solc
#!/bin/sh

cd "$(dirname "$0")"

echo "echidna is internally running: $0 $@" | tee -a /tmp/cmds
./solcjs "$@"
```

Then `/tmp/cmds` shows echidna internally running this:

```
internally running: $PWD/solc/solc --version
internally running: $PWD/solc/solc FuzzingContract.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --allow-paths . FuzzingContract.sol
```

I also tried installing solc with `npm install -g solc@0.8.12` then running with the same args to see if it'd work:

```
$ /usr/lib/node_modules/solc/solc.js FuzzingContract.sol --combined-json abi,ast,bin,bin-runtime,srcmap,srcmap-runtime,userdoc,devdoc,hashes,compact-format --allow-paths . FuzzingContract.sol
error: unknown option '--combined-json'
```

nope :( am I missing something here or using the wrong solc or smth?

**Comment by elopez** [comment]
Hi @Arinerron! As far as I recall, you need to use the binary solc, not solcjs. solcjs has different CLI arguments, and will not be compatible, as explained on their docs: 

> The commandline options of solcjs are not compatible with solc and tools (such as geth) expecting the behaviour of solc will not work with solcjs.
-- https://docs.soliditylang.org/en/develop/installing-solidity.html#npm-node-js

You can get solc installed from the official packages (eg [for linux](https://docs.soliditylang.org/en/develop/installing-solidity.html#linux-packages)) or using solc-select if you are looking for an easy way to maintain your solc installations: https://github.com/crytic/solc-select

**Comment by Arinerron** [comment]
thank you @elopez!

**Comment by Saniabuh** [comment]
ERROR:CryticCompile:Invalid solc compilation test.sol:17:37: Error: Expected token Comma got 'Colon'
        require(c / a == b, SafeMath: multiplication overflow);

**Comment by ggrieco-tob** [comment]
Hi @Saniabuh

You are getting a compilation error, please check [the Solidity documentation](https://docs.soliditylang.org/en/v0.8.20/) to solve it.
