### ISSUE TITLE
initialize fuzzing contract with ether?

### ISSUE THREAD

**Issue by Arinerron** [crytic/echidna#804]
Hi! To fuzz the target contracts, I need a pretty high ether balance (without making modifications to the target contracts, at least). Is there a way to mint ether or initialize the fuzzing constructor with more ether?

**Comment by elopez** [comment]
Hi @Arinerron! Would the `balanceContract` or `balanceAddr` [echidna options](https://github.com/crytic/echidna/wiki/Config) address your use case?

**Comment by Arinerron** [comment]
Yes! These will work. Sorry, I'd searched that page. I don't know how I didn't see that option. Thank you again!
