### ISSUE TITLE
Echidna freezes at startup 

### ISSUE THREAD

**Issue by OxMarco** [crytic/echidna#808]
Echidna freezes showing *Starting up, please wait...* for more than 1 hour without anything else happening.

**Command:**
`./echidna-test . --contract MockTokenTest`

**Env:**
macOS Monterey - Apple M1 Pro
Python 3.8.9
Echidna 2.0.2 with default config file

**Test file:**
```solidity
pragma solidity >=0.8.12;

import { MockToken } from "./MockToken.sol";

contract MockTokenTest is MockToken {
    constructor() MockToken("test", "TST", 18) {}

    function echidna_test_staking() public view returns (bool) {
        return balanceOf(address(this)) > 0;
    }
}
```

**Contract being tested:**
```solidity
pragma solidity >=0.8.12;

import { ERC20 } from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import { Ownable } from "@openzeppelin/contracts/access/Ownable.sol";

contract MockToken is ERC20, Ownable {
    mapping(address => uint256) private throttledMinters;
    mapping(address => bool) private blockedMinters;
    uint256 private throttlingPeriod;
    uint8 private immutable decimalPlaces;

    constructor(
        string memory _name,
        string memory _symbol,
        uint8 _decimals
    ) ERC20(_name, _symbol) {
        decimalPlaces = _decimals;
    }

    function toggleBlock(address account) external onlyOwner {
        blockedMinters[account] = !blockedMinters[account];
    }

    function setThrottlingPeriod(uint256 period) external onlyOwner {
        throttlingPeriod = period;
    }

    function mintTo(address to, uint256 amount) external onlyOwner {
        _mint(to, amount);
    }

    function mint() external {
        address to = msg.sender;
        require(!blockedMinters[to], "MockToken: Blocked account");
        require(block.timestamp - throttledMinters[to] >= throttlingPeriod, "MockToken: Too many requests");
        _mint(to, 1000 * 10**decimals());
        throttledMinters[to] = block.timestamp;
    }

    function decimals() public view override returns (uint8) {
        return decimalPlaces;
    }
}
```

**Comment by elopez** [comment]
Hi, thanks for the report. I tried to reproduce the problem locally, but echidna ran fine:
![Screen Shot 2022-07-29 at 16 38 42](https://user-images.githubusercontent.com/2642849/181832142-5f43ed27-e556-4b4d-9911-f1ede608da34.png)

```
% npm i @openzeppelin/contracts
% echidna-test --crytic-args="--solc-remaps @openzeppelin/=node_modules/@openzeppelin/" test.sol --contract MockTokenTest
```


Can you try running echidna with `--format text` and see if there is any error printed on your machine? Also, can you check if your slither-analyzer and crytic-compile are up to date?

```
% slither --version
0.8.3
% crytic-compile --version
0.2.3
```

**Comment by OxMarco** [comment]
Tried to run with `--format text` parameter and it outputs the following error
`echidna-test: NonEmpty.fromList: empty list`

**Comment by elopez** [comment]
Yeah, it looks like you are using a compilation framework, but I did not know which one or how it's set up, so I tried it with just the code you pasted here and a manual remap for the dependencies. Would you be able to share your complete test setup on a git repo to help reproduce the problem?

**Comment by OxMarco** [comment]
To expand on that, I tested integrating your additional arguments as follows:
`./echidna-test . --contract MockTokenTest contracts/test/MockTokenTest.sol --format text --crytic-args="--solc-remaps @openzeppelin/=node_modules/@openzeppelin/"`

and I get 
```bash
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Invalid solc compilation Compiler error: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable value0 is 1 slot(s) too deep inside the stack.
```
which clearly isn't possible as the smart contract is quite simple

**Comment by OxMarco** [comment]
Avoid having `bytecodeHash: "none"` in the hardhat configuration. Commenting the line out solved the issue
