### ISSUE TITLE
Revert on constructor call

### ISSUE THREAD

**Issue by cdgmachado0** [crytic/echidna#820]
Echidna throws the error `Deploying the contract XXXX failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)` when running these two contracts as they are.

Commenting out the `handleInit()` call on `Mock`'s constructor makes echidna run smoothly.  

```js
contract TestMock is Mock {
    constructor() Mock(
        setInit(),
        setAddresses()
    ) {}

    function setAddresses() public returns(address[] memory) { 
        //returns the array...
    }

    function setInit() public returns(address) { 
        //returns the address...
    }
}
```
```js
contract Mock {
    event ThrowVar(address x);

    constructor(
        address init_,
        address[] memory addresses_ 
    ) payable {        
        handleInit(init_); // ------> throws no error if this gets commented out
        emit ThrowVar(addresses_[0]);
    }

    function no_revert() public {
        assert(false);
    }

    function handleInit(address init2_) internal { // changing visibility has no effect
        assert(false);
    }
}
```

**Comment by elopez** [comment]
Thanks for the report @cdgmachado0. This error seems to be accurate, echidna is letting you know your `TestMock` constructor is failing (it calls the `Mock` constructor which calls `handleInit` which runs `assert(false)`) and therefore deployment fails. Could you expand on what the issue is?

**Comment by cdgmachado0** [comment]
Thank you @elopez and my apologies, I was looking at this all wrong. You're right.
