### ISSUE TITLE
Failing to generate proper inputs

### ISSUE THREAD

**Issue by cdgmachado0** [crytic/echidna#821]
Echidna is failing to generate the requiring inputs that would allow to successfully complete the test (which would fail in the example from below) and it's passing the test altogether (not expected).
```js
contract A is OtherContract {
   struct UserConfig { 
      address user;
      address userToken;
      uint userSlippage; 
   }

   modifier filterDetails(UserConfig calldata userDetails_) {
        require(userDetails_.user != address(0)); 
        require(userDetails_.userToken != address(0));
        require(userDetails_.userSlippage > 0);
        require(s.tokenDatabase[userDetails_.userToken]); // <---- commenting this out makes test() from below fails (expected)
        _;
    }

   function test(UserConfig calldata userDetails_) public filterDetails(userDetails_) {
        B b = new B();
        b.testContractB(userDetails_); // <----- passes (it should fail)
    }

   function test_tokenDb() public { // <------- fails in echidna (expected - proves that s.tokenDatabase was configured properly)
        address USDT = 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9;
        if (s.tokenDatabase[USDT]) {
            assert(false);
        } else {
            assert(true);
        }
    }
}
```
```js
contract B {
   function testContractB(
        UserConfig calldata userDetails_
    ) external {
        assert(false);
    }
}
```

**Comment by ggrieco-tob** [comment]
Which testing mode are you using?

**Comment by cdgmachado0** [comment]
assertion @ggrieco-tob

**Comment by ggrieco-tob** [comment]
We will need to look at the complete example to debug it.

**Comment by cdgmachado0** [comment]
I started getting ready the code that you requested using the minimum example from above (since my complete code is kinda long) and got it to work. Then went back to my code and it turned out all that I needed to do was to bump up the test limit to get the desired behavior. 

It seems like a lot of inputs needed to be generated in order for the troubling condition to pass (`s.tokenDatabase[userDetails_.userToken]`). I guess due to the complexity of the code. 

Thanks for your help!

**Comment by cdgmachado0** [comment]
I wanted to ask you, @ggrieco-tob (don't want to open an issue again for something that might be already in place but I just can't find it), is it possible to specify a `msg.value` on the entry tx for an echidna test (assertion mode)?

The test from below reverts because there isn't a `msg.value` specified, but you can't specify it on a delegatecall since `msg.value` get transmitted from the original call, but I can't seem to find the way to set that up since it's echidna who makes that entry call. 

```js
contract A {

   function test_exchangeUserToken(
        UserConfig calldata userDetails_
    ) external payable  { 
        (bool success, ) = address(ozlTestF).delegatecall( // <--- if I use `.call{value: 1 ether}(data)` instead, it passes
            abi.encodeWithSelector(
                ozlTestF.exchangeToUserToken.selector, 
                userDetails_
            )
        );
        assert(success); 
    }

}
```
```js
contract B {
   function exchangeToUserToken(
        UserConfig calldata userDetails_
    ) external payable { 
        require(msg.value > 0); // <----- reverts here (if I comment this out, it passes)
        assert(true); 
   }
}
```

The closest piece of info I could find was `maxValue` on the config file which describes the `Max amount of value in each randomly generated transaction`, but couldn't get it to work after playing around with it for a while. 

Thanks!

**Comment by cdgmachado0** [comment]
That's not valid solidity syntax though, and the compiles throws an error on it @ggrieco-tob 
```
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Invalid solc compilation Error: Member "call" not found or not visible after argument-dependent lookup in function (bytes memory) returns (bool,bytes memory).
   --> contracts/testing-files/echidna/DiamondTest.sol:209:28:
    |
209 |         (bool success, ) = address(ozlTestF).delegatecall.call{value: msg.value}(
    |
```

Based on what I'm seeing, Echidna generates value for all payable functions when `msg.value` is specified (that's why `.call{value: msg.value}(data)` works), but you can't specify `msg.value` on a delegatecall (since the opcode works forwarding the value -among other variables like the sender- from the original call).

**Comment by cdgmachado0** [comment]
It's not possible either to specify `msg.value` in the `value` field of the call options.

**Comment by cdgmachado0** [comment]
Or something like:
```js
function test(uint num) {
   (bool success, ) = address(ozlTestF).delegatecall{value: num}(
            abi.encodeWithSelector(
                ozlTestF.exchangeToUserToken.selector, 
                userDetails_
            )
        );
}
```

**Comment by cdgmachado0** [comment]
It could be something that Echidna generates a value for all payable functions that it has to call, but using delegatecall, Echdina doesn't call the second function in the second contract. It's called by the first contract which forwards the value from the 1st Echidna call, which is not being generated (at least not when using delegatecall)

**Comment by cdgmachado0** [comment]
After going through this all day, I think it's an issue so I opened it as such #822 . If it's not let me know and I'll close it.
