### ISSUE TITLE
echidna-test: (^?!): empty Fold 

### ISSUE THREAD

**Issue by AsfndAmin** [crytic/echidna#824]
getting this error when running ./echidna-test contract.sol

**Comment by AsfndAmin** [comment]
CallStack (from HasCallStack):   error, called at src/Control/Lens/Fold.hs:1296:28 in lens-4.19.2-7Q00MKR54DVFFru2tZkQiv:Control.Lens.Fold   ^?!, called at src/EVM/Solidity.hs:433:19 in hevm-0.48.0-3yc97MaS5pIDvLZRLvuryr:EVM.Solidity

**Comment by elopez** [comment]
Hi! Thanks for the report @AsfndAmin!. Could you let us know which slither and echidna versions you are using?

```sh
echidna-test --version
slither --version
```

If you can also provide a copy of the solidity code that causes this error, that would be great.

**Comment by ggrieco-tob** [comment]
Please reopen if necessary, we need more information to track down the issue.
