### ISSUE TITLE
Long lines are cut off in the UI

### ISSUE THREAD

**Issue by arcz** [crytic/echidna#831]
Wrap long lines so the whole text is readable in the UI:
![Screenshot from 2022-09-23 11-31-08](https://user-images.githubusercontent.com/4679721/191958524-ff38eaa6-14d9-4556-a7cb-00bb6132e8fd.png)

**Comment by ggrieco-tob** [comment]
This is an issue, but difficult to solve, since the user can resize the window and it is non-trivial to know how cut "long" values such as number or strings

**Comment by arcz** [comment]
I think this could be solved with brick's functions such as https://hackage.haskell.org/package/brick-1.1/docs/Brick-Widgets-Core.html#v:txtWrap
