### ISSUE TITLE
echidna-test: unlinked libraries detected in bytecode

### ISSUE THREAD

**Issue by kevzettler** [crytic/echidna#836]
Trying to run `echinda` against a hardhat project and getting this error in `Solidity.hs`
```
kevzettler@kevs-mbp-3 contracts % /Users/kevzettler/Downloads/echidna-test-2.0.3-MacOS-aarch64/echidna-test --crytic-args --hardhat-artifacts-directory=./build/contracts .
echidna-test: unlinked libraries detected in bytecode
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:546:18 in hevm-0.49.0-5Yg1p6l5Ed93myLfeFGsax:EVM.Solidity
  ```

**Comment by ggrieco-tob** [comment]
Do you have a Solidity library that you want to test?

**Comment by kevzettler** [comment]
@ggrieco-tob trying to test a contract that is dependent on a library.

**Comment by ggrieco-tob** [comment]
You need to use Solidity libraries with only internal functions. We are developing a workaround for easily testing libraries with public functions, but it is too difficult to use right now :disappointed:

**Comment by dokzai** [comment]
I am running into this issue due to library dependency too. What is the workaround for libraries with public functions? 
Is it possible to replace the bytecode and deployed bytecode used by echidna?

Thank you!

**Comment by ChristianDahdah** [comment]
@dokzai I am having the same problem, and tried to use the flag `--solc-args "--libraries @path-to-library/Library.sol:Library=0x1234567890123456789012345678901234567890"` where I put the expected address of the library.
Seems to compile but cannot tell if it really work since I am running into other problems with slither.

**Comment by richie444** [comment]
```Richie@Labs-MacBook-Pro 2022-12-tigris % echidna-test .
echidna-test: unlinked libraries detected in bytecode
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:547:18 in hevm-0.49.0-J2vJ1J8N27Q1k0k0eyS65Y:EVM.Solidity```

I am experiencing the same problem when testing smart contracts using openzeppelin libraries

**Comment by ChristianDahdah** [comment]
The solution turned out to be simple.

Create a `config.yaml` file for echidna and define in it:
`solcLibs: ["path-to-lib/Library.sol:LibraryName"]`
And run:
`$ echidna-test Contract.sol --config config.yaml`

This is only required for libraries with `external` or `public` functions.

**Comment by ggrieco-tob** [comment]
This should work, but only when using a single solidity file. We haven't tested in truffle/hardhat/foundry yet.

**Comment by rafales** [comment]
I'm running into the same issue without any libraries being used. Actually it seems that this error is shown even before the contract is selected as it's raised before echidna can figure out that given contract doesn't really exist:

```
> echidna-test . --contract Sss    
echidna-test: unlinked libraries detected in bytecode
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:551:18 in hevm-0.50.2-JOFIXI8LW6Z58eVLau9dlt:EVM.Solidity
```

**Comment by asmitadhungana** [comment]
Getting the same error even after I applied this solution: https://github.com/crytic/echidna/issues/836#issuecomment-1351325734
```
Warning: unused option: intialize
echidna-test: unlinked libraries detected in bytecode
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:551:18 in hevm-0.50.2-JOFIXI8LW6Z58eVLau9dlt:EVM.Solidity
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brucdarc** [comment]
I'm having this issue too, I've been looking around the repo, and I'm curious if the deployContracts and deployBytecodes options in the config could be used in a work around to this problem. I don't see these fields listed in the documentation though, are they currently supported, or place holders for the future? And if they are supported, is there any example anywhere of how to use them?

**Comment by brucdarc** [comment]
I've developed a work around I can use for my project, here a github repo with an example of what I did https://github.com/brucdarc/Echidna-Linking

**Comment by ggrieco-tob** [comment]
We already have official documentation on how to do it in secure-contracts: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/advanced/working-with-libraries.md
