### ISSUE TITLE
Echidna test with proxy contract to initialise

### ISSUE THREAD

**Issue by bogdynator** [crytic/echidna#862]
Hello, I have an issues when I try to initialise a contract. Below is the code and the error is:
`echidna-test: Deploying the contract 0x00a329c0648769A73afAc7F9381E08FB43dBEA72 failed (revert, out-of-gas, sending ether to an non-payable constructor, etc.)`
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract Deployer {
    function deployContractsAndSet()
        public
        returns (
            ERC20,
            ERC20
        )
    {
        ERC20 contract1 = new ERC20("a", "b");
        ERC20 contract2 = new ERC20("a2", "b2");

        return (contract1, contract2);
    }
}

contract EchidnaTest {
    ERC20 a;
    ERC20 b;

    constructor() {
        Deployer deployer = new Deployer();
        (a, b) = deployer.deployContractsAndSet();
    }

    function echidna_da()public view returns(bool){
        return true;
    }
}
```
Can somebody tell me why this is happening?

**Comment by ggrieco-tob** [comment]
Can you try using this code instead, to test that everything works as expected:

```solidity
contract ERC20 {}

contract Deployer {
    function deployContractsAndSet()
        public
        returns (
            ERC20,
            ERC20
        )
    {
        ERC20 contract1 = new ERC20();
        ERC20 contract2 = new ERC20();

        return (contract1, contract2);
    }
}

contract EchidnaTest {
    ERC20 a;
    ERC20 b;

    constructor() {
        Deployer deployer = new Deployer();
        (a, b) = deployer.deployContractsAndSet();
    }

    function echidna_da()public view returns(bool){
        return true;
    }
}
```

**Comment by bogdynator** [comment]
ok, now this mocked example works. There is a way to see a more detailed raport of the error? Bcs in my contracts I have more functions called in `deployContractsAndSet ` and I wish to see if they are failing with a known reason or there is another problem that I am not aware of.

**Comment by bogdynator** [comment]
or any other method to understand what is wrong?

**Comment by ggrieco-tob** [comment]
Something is reverting inside your constructor. You will need to show the complete the example or debug it commenting lines one by one.

**Comment by ChmielewskiKamil** [comment]
Hi @bogdynator! Which testing framework do you use? I copied your code into Foundry, slightly changed imports and built it with no problem. 

> I wish to see if they are failing with a known reason or there is another problem that I am not aware of.

I've modified your code just a bit. I've moved the logic from the constructor in the `EchidnaTest` contract to the test function itself and added `try` & `catch` to handle potential errors. This is how your code would look with these modifications:
``` solidity
// ... snippet (the rest of the code stays the same as before)
contract EchidnaTest {
    ERC20 a;
    ERC20 b;
    function echidna_test_erc_deployed() public returns (bool) {
        Deployer deployer = new Deployer();
        try deployer.deployContractsAndSet() returns (ERC20 _a, ERC20 _b) {
            a = _a;
            b = _b;
        } catch (bytes memory error) {
        }
        // this will be true if the ERC20 was deployed correctly
        return (address(a) != address(0));
    }
}
```

This code, however, does not do anything in case of an error. We can improve upon that and add some `events`. I couldn't get events to work in the [property testing mode](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/testing-modes.md#boolean-properties), so let's switch to the assertion mode (change the `return` on the last line to the `assert` and delete `returns(bool)` in the function signature).  

```solidity
contract EchidnaTest {
    ERC20 a;
    ERC20 b;

    event ReturnedContracts(ERC20 firstContract, ERC20 secondContract);
    event DeploymentError(bytes error);

    function test_erc_deployed() public {
        Deployer deployer = new Deployer();
        try deployer.deployContractsAndSet() returns (ERC20 _a, ERC20 _b) {
            a = _a;
            b = _b;
            emit ReturnedContracts(_a, _b);
        } catch (bytes memory error) {
            emit DeploymentError(error);
        }
        assert(address(a) != address(0));
    }
}
```

With these events, if you, for example, change the assertion to `assert(address(a) == address(0))` it will fail and emit the debug events like so:
```
Event sequence: Panic(1), ReturnedContracts(@0xCe71065D4017F316EC606Fe4422e11eB2c47c246, @0x185a4dc360CE69bDCceE33b3784B0282f7961aea) from: EchidnaTest@0x00a329c0648769A73afAc7F9381E08FB43dBEA72
```

Not sure if this was helpful to you, but I had a similar problem recently and managed to solve it with `try` & `catch` blocks and a couple of debug events.

**Comment by ChmielewskiKamil** [comment]
If you want to play around with it, I've [published a repo to my GitHub](https://github.com/ChmielewskiKamil/proxy-contract). 

Run the test with ` echidna-test src/EchidnaTest.sol --contract EchidnaTest --config echidna_config.yaml`. It will also generate the [coverage report](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/collecting-a-corpus.md) so that you can check if your test even went through the deployment or reverted before that.

**Comment by bogdynator** [comment]
this issue can be closed, thank you so much @ChmielewskiKamil for your debug solution
