### ISSUE TITLE
Multiple arguments for --crytic-args doesn't seem to work. 

### ISSUE THREAD

**Issue by brucdarc** [crytic/echidna#864]
When running: 
```echidna-test . --contract SimpleEchidnaTest --crytic-args --compile-force-framework hardhat```

Outputs

```echidna-test: Couldn't compile given file
stdout:
stderr:
usage: crytic-compile contract.sol [flag]
crytic-compile: error: argument --compile-force-framework: expected one argument
```

I'm running an environment where I need to force hardhat to avoid errors. Is there any way to do this properly?

Im trying to pass 2 arguments to crytic, ```--compile-force-framework hardhat```

**Comment by 0xalpharush** [comment]
I believe quoting the args should suffice: `echidna-test . --contract SimpleEchidnaTest --crytic-args "--compile-force-framework hardhat"`

**Comment by brucdarc** [comment]
That worked, thanks!
