### ISSUE TITLE
echidna-test: No tests found in ABI

### ISSUE THREAD

**Issue by xihucuyu888** [crytic/echidna#873]
how to resolve

**Comment by ggrieco-tob** [comment]
Please take a look to: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/testing-modes.md and provide more information if needed.

**Comment by Saniabuh** [comment]
echidna: No tests found in ABI,

how do i solve this

**Comment by arcz** [comment]
@Saniabuh I've just improved this error message, see https://github.com/crytic/echidna/issues/1056.
