### ISSUE TITLE
Bug: NonEmpty.fromList: empty list

### ISSUE THREAD

**Issue by 0xPhaze** [crytic/echidna#887]
```solidity
contract Contract {
    bytes32 immutable HASH_INITIAL_MSG_SENDER = keccak256(abi.encode(msg.sender));

    function test_msg_sender_changed() public {
        assert(keccak256(abi.encode(msg.sender)) == HASH_INITIAL_MSG_SENDER);
    }
}
```
Running echidna gives the following output.
```
echidna-test . --contract Contract --test-mode assertion --format text
Analyzing contract: [...]/src/Contract.sol:Contract
echidna-test: NonEmpty.fromList: empty list
```

**Comment by ggrieco-tob** [comment]
Using the contract directly works as expected:

```
$ echidna-test crash.sol --test-mode assertion --contract Contract
Analyzing contract: /home/g/Code/echidna/crash.sol:Contract
test_msg_sender_changed(): failed!💥  
  Call sequence:
    test_msg_sender_changed()

Event sequence: Panic(1)
AssertionFailed(..):  fuzzing (8374/50000)
```

You should check if you are removing metadata, since that could cause a crash.

**Comment by 0xPhaze** [comment]
Yes, when specifying the file it does work. It also works when specifying the root directory and when including the metadata hash in the compiler settings. What's the reason for this?

**Comment by ggrieco-tob** [comment]
Can you still reproduce this issue?

**Comment by 0xPhaze** [comment]
Just tested this again (while providing the root directory and not including the metadata hash), and it seems to be fine now. Closing.
