### ISSUE TITLE
Bug: echidna terminal output freezes when crashing

### ISSUE THREAD

**Issue by 0xPhaze** [crytic/echidna#889]
If echidna runs into bugs during startup, the terminal output freezes:
<img width="853" alt="image" src="https://user-images.githubusercontent.com/103113487/210238717-26553119-cc8f-459f-888b-9aca8bf7ab4b.png">

If in these cases I add `--format text` I can actually see that echidna has crashed.
E.g for reproducibility #887 or #888 will freeze like above if `--format text` is left out.

**Comment by ChmielewskiKamil** [comment]
Had a little bit of a headache with this as well.
