### ISSUE TITLE
Bug: HEVM `store` cheat code is not affecting state variables

### ISSUE THREAD

**Issue by webthethird** [crytic/echidna#904]
See [TestStore.sol](https://github.com/webthethird/solidity-diff-fuzz-upgrades/blob/main/src/test/example/testStore.sol) for a very simple assertion test to reproduce this bug.

Using the HEVM cheat code `store` does appear to have some effect on the target contract's storage, because a subsequent call to the `load` cheat code returns the expected value. But when accessing the public state variable directly, i.e., by calling `c.owner()`, the value remains unchanged. The contract for which I am trying to change the state is about as simple as possible, with just a single public state variable and a constructor that sets it to `msg.sender`.

I had the same issue with both the 2.0.4 binary downloaded from the releases page and the one I got from the CI pipeline, built yesterday.

Here is the coverage report generated by Echidna when testing the contract linked above, in which you can see that `load` and `owner()` are returning different values, despite both loading from storage slot 0::
```solidity
/home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/compound/testStore.sol
  1 | r   | // SPDX-License-Identifier: MIT
  2 |     | pragma solidity ^0.8.0;
  3 |     | 
  4 |     | import "../example/Smartian_motiv.sol";
  5 |     | import "../helpers.sol";
  6 | r   | 
  7 |     | contract TestStore {
  8 |     |     address admin;
  9 |     |     C c;
 10 |     | 
 11 |     |     constructor() {
 12 |     |         admin = msg.sender;
 13 |     |     }
 14 |     | 
 15 | r   |     function testStore() public {
 16 | r   |         c = new C();
 17 | r   |         require(c.owner() == address(this));
 18 | r   |         CheatCodes(HEVM_ADDRESS).store(address(c), bytes32(0), bytes32(bytes20(admin)));
 19 | r   |         assert(address(bytes20(CheatCodes(HEVM_ADDRESS).load(address(c), bytes32(0)))) == admin);
 20 | r   |         assert(c.owner() == admin);
 21 |     |     }
 22 |     | }

/home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/example/simplest_example.sol
  1 |     | // SPDX-License-Identifier: MIT
  2 |     | pragma solidity ^0.8.0;
  3 | r   | 
  4 |     | contract C {
  5 | r   |   address public owner;
  6 |     | 
  7 |     |   constructor() { // Constructor
  8 |     |     owner = msg.sender;
  9 |     |   }
 10 |     | }
 ```
And here's a snippet from the Echidna output to the terminal:
```
Analyzing contract: /home/webthethird/Ethereum/solidity-diff-fuzz-upgrades/src/test/compound/testStore.sol:TestStore
testStore(): failed!💥  
  Call sequence:
    testStore()

Event sequence: Panic(1)
AssertionFailed(..):  fuzzing (48/999999)
```

**Comment by ggrieco-tob** [comment]
Thanks for the report. Please don't forget to add a similar report here: https://github.com/ethereum/hevm and link the issue back, since this looks like an issue upstream.

**Comment by ggrieco-tob** [comment]
Closing this since it the reproducer was wrong according to the hevm team.

**Comment by webthethird** [comment]
> Closing this since it the reproducer was wrong according to the hevm team.

By reproducer do you mean my TestStore.sol assertion test? If so, I'd like to know how I can fix it!

**Comment by ggrieco-tob** [comment]
It seems that this is a case of accessing the correct slot, with the correct data type in Solidity as opposed as an issue in echidna or hevm.

**Comment by webthethird** [comment]
You mean the `owner` variable in the contract C is somehow not in slot 0? Or is there a problem with the way the TestStore contract is calling `CheatCodes.store`?

**Comment by webthethird** [comment]
Perhaps the problem might have been that I didn't push the modification I made to `Smartian_motiv.sol`, which made the `owner` variable public. Instead I made a new `simplest_example.sol`, but forgot to change the import in `testStore.sol`. I've fixed that now. 
Other than that, I'm having trouble seeing where I went wrong.

**Comment by webthethird** [comment]
Nevermind, I figured it out! I had forgotten about how casting from address to bytes20 to bytes32 pads the value on the wrong side.
Case closed!
