### ISSUE TITLE
Problem while installing Echidna via `brew install --HEAD echidna`

### ISSUE THREAD

**Issue by ChmielewskiKamil** [crytic/echidna#907]
I've been trying to install the newest Echidna version to use the features from HEVM 0.50.2.

The last steps of the build process seem to have a problem. I am running `brew install --HEAD echidna`.

Here is the console log:
```
==> ./configure --prefix=/opt/homebrew/Cellar/echidna/HEAD-428483c --libdir=/opt/homebrew/Cellar/echidna/HEAD-428483c/lib --prefix=/opt/homebrew/Cellar/echidna/HEAD-428483c/libexec --libdir=/opt/homebrew/Cellar/echidna/HEAD-42848
==> make install
==> stack -j8 build --system-ghc --no-install-ghc --skip-ghc-check --extra-include-dirs=/opt/homebrew/opt/libff/include --extra-lib-dirs=/opt/homebrew/opt/libff/lib --extra-include-dirs=/opt/homebrew/Cellar/echidna/HEAD-428483c/l
Last 15 lines from /Users/kamilchmielewski/Library/Logs/Homebrew/echidna/04.stack:
           time-1.9.3 from Stack configuration does not match >=1.11.1.1 && <1.12 (latest matching
                      version is 1.11.1.2)
       needed due to echidna-2.0.4 -> hevm-0.50.2
       
       Some different approaches to resolving this:
       
         * Set 'allow-newer: true'
           in /private/tmp/echidna-20230114-61934-1o0r79k/.brew_home/.stack/config.yaml to ignore all version constraints and build anyway.
       
         * Recommended action: try adding the following to your extra-deps
           in /private/tmp/echidna-20230114-61934-1o0r79k/stack.yaml:
       
       - bytestring-0.11.4.0@sha256:55390b63bbd7846aab6b16b7b255cf5108a3a422798a1e9a3b674eb0c68ac20c,7491
       - time-1.11.1.2@sha256:a957467595420495c2dd440d9efa1f58c62277cf9438c7e7a515d7a4c65571ec,6287
```

I've tried adding the `extra-deps` to the `stack.yaml` file via the `nano` text editor. The problem is that this whole path does not exist: `/private/tmp/echidna-20230114-61934-1o0r79k/.brew_home/.stack/`

I've also tried creating this file via `touch`, but it does not work either. 

I am on an M1 Mac, and the `echidna-20230114-61934-1o0r79k` folder is not hidden. It is not showing after pressing `shift + command + .`

The `echidna-test` is also not appended to my PATH as it is in the case of normal `brew install echidna`. 

**Update** it is not appended to the path because the installation failed. Echidna is not listed in the `brew list`. 

I will be happy to provide additional details if you need them. 

Thanks!

**Comment by elopez** [comment]
Hi! There have been recent changes in Echidna, including upgrading the compiler version that needs to be used to build (GHC 9.2, previously 8.10) as well as other Haskell dependencies like HEVM, so building `--HEAD` in brew is broken at this time.

I have a few patches prepared to update the echidna formula for when the next release comes out [in this branch](https://github.com/Homebrew/homebrew-core/compare/master...elopez:homebrew-core:improve-echidna-secp256k1). Most of it is cleanup, so you can ignore the majority of the changes there; the main change that you'd need to do on the `echidna.rb` formula to get HEAD building is this one (bear in mind that this will also break building the 2.0.4 echidna version from source)

![screenshot](https://user-images.githubusercontent.com/2642849/212502765-cc197560-bbd2-42e9-955f-5980d721f9c9.jpg)

**Comment by ChmielewskiKamil** [comment]
Hi @elopez! Thank you so much for such a quick response!

> I have a few patches prepared to update the echidna formula for when the next release comes out [in this branch](https://github.com/Homebrew/homebrew-core/compare/master...elopez:homebrew-core:improve-echidna-secp256k1).

Do you have a specific date in mind for the next stable release?

> the main change that you'd need to do on the echidna.rb formula to get HEAD building is this one

I will check this one out. Thank you!

It's nothing urgent. I just wanted to poke around the new HEVM and report an issue along the way. Since you have patches prepared, we can close this issue now or wait for the fixes to be merged. 

Thanks again!

**Comment by elopez** [comment]
Echidna 2.0.5 is now on Homebrew, and building with `--HEAD` should be working again 👍  I'll close this issue but feel free to open a new one or ask in Slack if you encounter a similar problem in the future.

**Comment by ChmielewskiKamil** [comment]
> Echidna 2.0.5 is now on Homebrew

I've upgraded immediately. Thanks, @elopez!
