### ISSUE TITLE
Echidna won't start if the `ERC20` name or symbol begins with `0x`

### ISSUE THREAD

**Issue by ChmielewskiKamil** [crytic/echidna#909]
The contract below is taken from the [NaughtCoin level 15 of the Ethernaut wargame](https://github.com/OpenZeppelin/ethernaut/blob/master/contracts/contracts/levels/NaughtCoin.sol).

```solidity
// ...
contract NaughtCoin is ERC20 {
    // string public constant name = 'NaughtCoin';
    // string public constant symbol = '0x0';
    // uint public constant decimals = 18;
    uint256 public timeLock = block.timestamp + 10 * 365 days;
    uint256 public INITIAL_SUPPLY;
    address public player;

    constructor(address _player) ERC20("NaughtCoin", "0x0") {
        player = _player;
        INITIAL_SUPPLY = 1000000 * (10**uint256(decimals()));
        _mint(player, INITIAL_SUPPLY);
        emit Transfer(address(0), player, INITIAL_SUPPLY);
    }
// ...
```

If you import this contract into any Echidna test file, Echidna will freeze with the `Starting up, please wait...` log (similar to the [#889]). 

When run with the `--format text` flag it returns:
```
echidna-test: invalid b16 decoding of: "0x0"
CallStack (from HasCallStack):
  error, called at lib/Echidna/Processor.hs:123:31 in echidna-2.0.4-IHy1AKktzUiCzJpHK85UVS:Echidna.Processor
```

### Steps to reproduce the issue
[I've prepared an example repository](https://github.com/ChmielewskiKamil/naught-coin).

1. Clone the repo and cd into it: `git clone https://github.com/ChmielewskiKamil/naught-coin.git && cd naught-coin`
2. Run Echidna: `echidna-test src/TestNaughtCoin.sol --contract TestNaughtCoin --config src/config.yaml`
3. This results in: `echidna-test: invalid b16 decoding of: "0x0"`

As soon as you change the symbol to something different, like so:
```solidity
// change this
constructor(address _player) ERC20("NaughtCoin", "0x0")

// into this
constructor(address _player) ERC20("NaughtCoin", "ABC")
```
It starts fuzzing correctly.

If the token's name starts with `0x`, it does not work either.
```solidity
// this won't work
constructor(address _player) ERC20("0xNaughtCoin", "ABC")
```

This results in the same issue: `echidna-test: invalid b16 decoding of: "0xNaughtCoin"`.

### Additional info
This was a bit of a headache to debug as I had no idea about the `--format text` flag or the `format = text` option in the config. 

This option is mentioned [at the end of the FAQ section of the building secure contracts repo](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/frequently_asked_questions.md#echidna-stopped-working-for-some-reason-how-can-i-debug-it). I had this "freezing" problem a couple of times in the past and didn't know how to solve it. Adding the information about this `format text` debug option in a couple more places would be great for newer users to solve problems on their own.

I would be happy to help update the documentation. I had a couple of ideas where such info could be present:
- [Main Echidna README in the Getting Help section](https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/frequently_asked_questions.md#echidna-stopped-working-for-some-reason-how-can-i-debug-it)
- [Main README of the Program Analysis - Echidna section of the building secure contracts repo](https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna) 
- [Inside Echidna exercises](https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna/exercises)
- [In the wiki](https://github.com/crytic/echidna/wiki), it is not possible to make a PR to the wiki as a contributor tho...

Let me know what you think

Thanks!

**Comment by ChmielewskiKamil** [comment]
This is a pretty niche use case (symbols and names with `0x`) but there are a couple of tokens that use this:
| name | symbol |
| --- | --- |
| ZRX | 0x |
| 0xBTC | 0xBitcoin |
| 0XMR | 0xMonero |
| ZXC | 0xcert |

**Comment by ggrieco-tob** [comment]
This looks like a legitimate issue and I think I know why it fails. Thanks a lot for the report, we will try to fix it for the next release :smile:

**Comment by ChmielewskiKamil** [comment]
@ggrieco-tob Awesome, thank you!

**Comment by ggrieco-tob** [comment]
Small reproducer:
```solidity
contract A {
  string public x = "0xa";
  function f() public returns(string) { return x; }
}
```
