### ISSUE TITLE
Echidna generates input that has "\NUL" for string, bytes types

### ISSUE THREAD

**Issue by Yingtong-Liu** [crytic/echidna#910]
I have a question about the random inputs generated by echidna. 

I have a test function as: test_encodeString(string memory data). Echidna generated the inputs as "\NUL" or "\NUL\NUL\NUL" that make my test fail. I want to restrain the inputs not to contain "\NUL" but I don't really know what "\NUL" means for bytes or string in echidna's case. It's simply not 0x0 and the '\' escape sequence is not valid in solidity's sytax.

**Comment by ggrieco-tob** [comment]
´\NUL´ is the 0 byte in either strings or bytes. It is displayed like that because it uses Haskell's escape format.

**Comment by Yingtong-Liu** [comment]
@ggrieco-tob Thanks. If so, when I try to constrain the input not to be 0 byte, what I tried to do in solidity is (dapptest mode):
`require(keccak256(bytes("0")) != keccak256(bytes(input)), "FOUNDRY::ASSUME"); `

The thing is echidna still generates input as '\NUL' for me. If I am wrong, I wonder what is the correctly to do this?

**Comment by ggrieco-tob** [comment]
`bytes("0")` is incorrect, as "0" is a string with the ascii number 0x30 (zero).

**Comment by Yingtong-Liu** [comment]
@ggrieco-tob Thanks. `bytes(hex"00") `works for me.
