### ISSUE TITLE
Feature Request: Aliases for addresses in echidna's output

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#913]
It would be nice to have to option to use aliases for addresses.
1. It's easier to recognize which contract/EOA is being used
2. Keeps the UI cleaner (makes the lines shorter)

Example
`testDeposit(<TargetContract>,123,123,<Attacker>,true)`

This could possibly be combined with: https://github.com/crytic/echidna/issues/861

**Comment by ggrieco-tob** [comment]
Related to #273

**Comment by 0xalpharush** [comment]
Foundry has a vm.label cheatcode that does this and would improve Echidna's parity https://book.getfoundry.sh/cheatcodes/label?highlight=labe#label

**Comment by ggrieco-tob** [comment]
This is already supported :tada:
