### ISSUE TITLE
Add proper support for enums

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#918]
This would be nice for situations where you want to test for a limited amount of options/values (but more than 2)

For example I would use this in combination with `hevm.prank()` to simulate a couple of users by using a mapping from the enum value to an address.

**Comment by samalws** [comment]
Once the slither version on this repo is bumped high enough that https://github.com/crytic/slither/pull/1665 is included, enums will be supported without any change to echidna code needed

**Comment by ggrieco-tob** [comment]
This is great, but keep in mind that echidna will still be testing inputs outside the enum range. Moreover, it will not distinguish between possible enum types so the speedup will not scale for large contracts :disappointed:

**Comment by ggrieco-tob** [comment]
Already released in slither, so the support improved. It is not completely solved, but I think we close this one.
