### ISSUE TITLE
deployContracts mentioned twice instead of the deployBytecodes in wiki

### ISSUE THREAD

**Issue by ahpaleus** [crytic/echidna#923]
> - deployContracts
> 
> Type: [⁠[⁠Address, String⁠]⁠]
> Default: []
> Description: Addresses and contract names to deploy using the available source code. The deployer address is the same as the contract to test. Echidna will error if the deployment fails.
> 
> - deployContracts
> 
> Type: [⁠[⁠Address, String⁠]⁠]
> Default: []
> Description: Addresses and bytecodes to deploy. The deployer address is the same as the contract to test. Echidna will error if the deployment fails.

The second one should be `deployBytecodes`.

**Comment by ggrieco-tob** [comment]
Good catch!, it seems you already fixed it.

**Comment by ahpaleus** [comment]
Yeah, I didn't know I had access rights to edit the wiki. Done.
