### ISSUE TITLE
feat: generate .lcov coverage report

### ISSUE THREAD

**Issue by 0xPhaze** [crytic/echidna#936]
Echidna currently generates a .txt and a .html file when recording coverage. It would be nice if a .lcov file could also be generated. This could then be leveraged by existing tools to display [code coverage in VSCode](https://marketplace.visualstudio.com/items?itemName=semasquare.vscode-coverage-gutters) for example.

**Comment by hellwolf** [comment]
I would be very happy if we could do that.

In our github workflow, we [publish lcovs from both hardhat testing and foundry testing](https://github.com/superfluid-finance/protocol-monorepo/blob/d15b3b2d02656d4a5483b9a0194cb4cb00e7a5fd/.github/workflows/ci.canary.yml#L177) and upload them to codecov; we also test echidna build with 1000 runs for now just for sanity check. If we had lcov, we could do a long running test and upload it to codecov too.

**Comment by PatStiles** [comment]
I'm interested in trying this out

**Comment by tusuii** [comment]
:+1:
