### ISSUE TITLE
Improve text output

### ISSUE THREAD

**Issue by arcz** [crytic/echidna#945]
The text output mode doesn't give any status updates on what's going on. Ideally, it should provide the same information as the interactive UI, just in a less convenient way.

Print out a status line every X seconds similar to libFuzzer or if any interesting event happens like when coverage increases or an invariant is broken.

**Comment by aviggiano** [comment]
As a reference, this was also addressed by https://github.com/crytic/optik/issues/36

> [echidna] currently displays its logs in the terminal while running. While this is great to know what goes on under the hood, it is not very practical to scroll through it. This is especially true when running a large number of Echidna campaigns and detecting a log of potential new paths, which makes the log very verbose.
We should add a command line option to let users decide whether they want the logs to be written in a file or to the terminal with --logs or --logs . If the option is stdout or not specified, we should then display some user-friendly info in the terminal:
> - current task: running echidna / replaying inputs / solving inputs
> - current task progress: with a counter, e.g Solving 4/256, and a progress bar
> - global stats: number of bugs found, number of new inputs generated, number of solver timeouts, etc...

**Comment by arcz** [comment]
This works already, especially with the new event system from 2.2.0.
