### ISSUE TITLE
README examples are outdated and wrong

### ISSUE THREAD

**Issue by japesinator** [crytic/echidna#95]
Since the big config refactor, our examples in the README are pretty incorrect. We should fix those. Can we get them in CI?

**Comment by elenadimitrova** [comment]
That would be really nice. I am struggling to find answers to even basic questions, e.g. how to handle contracts  under test that require imports, how to do test harness setup (via test contract constructor or otherwise) etc

**Comment by ggrieco-tob** [comment]
README is better, but perhaps we need better examples?

**Comment by ggrieco-tob** [comment]
README is better now. I improved a little the examples and removed old flags.
