### ISSUE TITLE
Feature Request: HTML report when fuzzing is done

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#959]
The current output in the console works fine but it often lacks specific information I want to know. It would be nice to have a detailed/interactive report in HTML.

Some ideas:
- Add this: https://github.com/crytic/echidna/issues/656#issuecomment-1342570956
- Foldable trace of all functions called
- Emitted events
- (Token) balance changes

Basically it could eventually be a transaction explorer like Phalcon:
https://phalcon.blocksec.com/tx/eth/0x6200bf5c43c214caa1177c3676293442059b4f39eb5dbae6cfd4e6ad16305668

**Comment by ggrieco-tob** [comment]
Done
