### ISSUE TITLE
Getting rate-limited when using Infura RPC URL

### ISSUE THREAD

**Issue by webthethird** [crytic/echidna#964]
When trying to reproduce the COMP distribution bug, Echidna is crashing due to rate-limiting from my Infura RPC url endpoint.

![image](https://user-images.githubusercontent.com/6509209/221716450-0edd16db-e7f2-4298-9fa5-ae63385cae94.png)

**Comment by ggrieco-tob** [comment]
@arcz let's fix this crash before the new release

**Comment by ggrieco-tob** [comment]
I think this should be fixed. You will still be rate limited, but it shouldn't crash.

**Comment by ggrieco-tob** [comment]
This was already fixed
