### ISSUE TITLE
User-friendly terminal display for echidna

### ISSUE THREAD

**Issue by aviggiano** [crytic/echidna#975]
I am running echidna in a remote environment, which makes the current log display behavior not very practical. It would be good to have the same feature as https://github.com/crytic/optik/issues/36

> [echidna] currently displays its logs in the terminal while running. While this is great to know what goes on under the hood, it is not very practical to scroll through it. This is especially true when running a large number of Echidna campaigns and detecting a log of potential new paths, which makes the log very verbose.
> We should add a command line option to let users decide whether they want the logs to be written in a file or to the terminal with --logs <file> or --logs <stdout>. If the option is stdout or not specified, we should then display some user-friendly info in the terminal:
> - current task: running echidna / replaying inputs / solving inputs
> - current task progress: with a counter, e.g Solving 4/256, and a progress bar
> - global stats: number of bugs found, number of new inputs generated, number of solver timeouts, etc...

**Comment by arcz** [comment]
@aviggiano isn't this similar to https://github.com/crytic/echidna/issues/945?

**Comment by aviggiano** [comment]
Thanks, I think it's the same thing.
I'll close this one and track the other.
