### ISSUE TITLE
log what echidna is doing at different stages e.g. startup/ shutdown

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/echidna#979]
It'd be nice if Echidna gave more feedback on startup like "I'm running this command to compile smart contracts". On shutdown, it'd be nice to say "I'm writing the corpus to the disk here" (assuming a corpus dir was passed). Otherwise, it is unclear that everything is working correctly and progressing and something exceptional hasn't occurred (especially for something time consuming like writing the corpus to disk).

**Comment by ggrieco-tob** [comment]
This is already in master
