### ISSUE TITLE
*no transactions made*

### ISSUE THREAD

**Issue by rapidAman** [crytic/echidna#987]
### Describe the issue:

I have created one erc 20 token . one setup file for that. and test file.

// my token file

// contracts/WinToken.sol
// SPDX-License-Identifier: None
pragma solidity >=0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract WinToken is ERC20 {
    constructor(uint256 totalSupply) ERC20("Win", "WIN") {
        _mint(msg.sender, totalSupply * (10 ** decimals()));
    }
}

// setup file 
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.1;

import "./WinToken.sol";
contract WinTokenSetup {   
    WinToken wintoken;
    constructor() {
        wintoken = new WinToken(500000000000000000);
        
    }
}

but is showing transaction not done. 
![image](https://user-images.githubusercontent.com/95608931/226288570-e4d9f4e7-b3a0-4414-82c9-26073c1d4eab.png)
 

### Code example to reproduce the issue:

// test file 
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.1;

import "./WinTokenSetup.sol";

contract WinTokenTest is WinTokenSetup {
    
    function echidna_testwinToken() public view returns (bool) {
        return wintoken.balanceOf(address(this)) <= 500000000000000000;
    }
    
}

### Version:

Echidna 2.1.0
slither 0.9.2

### Relevant log output:

```shell
┌─────────────────────────────────────────────────────Echidna 2.0.1────────────────────────────────────────────────────┐                                    │ Tests found: 1                                                                                                       │                                    │ Seed: 7633847963726703830                                                                                            │                                    │ Unique instructions: 27                                                                                              │                                    │ Unique codehashes: 1                                                                                                 │                                    │ Corpus size: 1                                                                                                       │                                    │─────────────────────────────────────────────────────────Tests────────────────────────────────────────────────────────│                                    │ echidna_testwinToken: FAILED!                                                                                        │                                    │                                                                                                                      │                                    │ *no transactions made*                                                                                               │                                    └──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘                                                                             Campaign complete, C-c or esc to exit
```

**Comment by ggrieco-tob** [comment]
This means that the original property `wintoken.balanceOf(address(this)) <= 500000000000000000` is false or it reverts when the contract is deployed.

**Comment by rapidAman** [comment]
can you help me where I need to change the code so that it works.

**Comment by ggrieco-tob** [comment]
We need to see the complete code in order to help.

**Comment by rapidAman** [comment]
above i provided all the file
1. token file 
2. setup file 
3. test file

**Comment by ggrieco-tob** [comment]
Please create a public github repository with your files, so we can easily test it.

**Comment by rapidAman** [comment]
https://github.com/rapidAman/WinToken.git

**Comment by ggrieco-tob** [comment]
The repository should include all the files needed to compile (e.g. how to install OZ libs and stuff).

**Comment by ggrieco-tob** [comment]
Closing this because lack of information, reopen if necessary
